### ISSUE TITLE
Clean out brew

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#103]
We are running into some cases where brew is installing stuff that competes with our packages. We should start cleaning this stuff out so we don't need workarounds. For instance, brew provides its own gmp, which clashes with the one we distribute. See this [thread]( https://github.com/conda-forge/staged-recipes/pull/133#discussion_r57533828 ) for an example of handling this problem and this [issue]( https://github.com/conda-forge/glpk-feedstock/issues/3 ) caused by the brew gmp. Here is [some code]( https://github.com/ukoethe/vigra/blob/master/.travis.yml#L47 ) that I wrote, which would help purge brew.

Here is a list that @ocefpaf compiled of things that `brew` installed.

    - apple-gcc42
    - autoconf
    - automake
    - boost
    - cgal
    - cloog
    - cloog-ppl015
    - cloog018
    - cmake
    - freexl
    - gcc
    - gcc46
    - gcc48
    - gdal
    - geos
    - giflib
    - gmp
    - gmp4
    - go
    - gpp
    - isl
    - isl011
    - jpeg
    - json-c
    - libgeotiff
    - libgpg-error
    - libksba
    - liblwgeom
    - libmpc
    - libmpc08
    - libpng
    - libspatialite
    - libtiff
    - libtool
    - libxml2
    - libyaml
    - lzlib
    - maven
    - mercurial
    - mpfr
    - mpfr2
    - node
    - openssl
    - ossp-uuid
    - pkg-config
    - postgis
    - postgresql
    - ppl011
    - proj
    - pyenv
    - readline
    - sfcgal
    - sqlite
    - subversion
    - wget
    - xctool

**Comment by jjhelmus** [comment]
I'm in favor of this.  The one holdout I am interested in would be gfortran since Xcode does not provide a Fortran compiler as far as I know.  That said, I do not think extensions compiled with brew's gfortran are portable (they will depend on libgfortran) so we may need to find a better method for providing a Fortran compiler on Mac anyway.

**Comment by jakirkham** [comment]
So, last discussion with @msarahan on [this point]( https://github.com/conda-forge/conda-forge.github.io/issues/29#issuecomment-200045986 ) was that `gfortran`/`libgfortran` will need to be packaged for Mac.

**Comment by pelson** [comment]
:+1: on this

> Here is some code that I wrote, which would help purge brew.

```rm -rf /usr/local```? :wink:

**Comment by jakirkham** [comment]
Cool, I'll try and write this at some point (or copy and paste :wink:).

**Comment by jakirkham** [comment]
Just one comment, we should slowly roll this out to feedstocks. We may find that some of them are not installing all the dependencies they should and will need time to get them back into working order.

**Comment by jakirkham** [comment]
Seems @ocefpaf beat me to it. See PR ( https://github.com/conda-forge/conda-smithy/pull/114 ).
