### ISSUE TITLE
Linter should not suggest noarch when scripts present in setup.py

### ISSUE THREAD

**Issue by tkelman** [conda-forge/conda-smithy#1030]
Ref https://github.com/conda-forge/conda-smithy/pull/1021 - suggest relying on the migrator bot to do the noarch suggestion instead of the linter, since the bot PR's list all prerequisites. Unless the linter checks all of them it's going to repeatedly suggest doing something that shouldn't be done on a number of packages.

**Comment by CJ-Wright** [comment]
FYI, the migrator bot is not currently running noarch migrations.

**Comment by tkelman** [comment]
Was that temporary? The code for it must still exist?

**Comment by CJ-Wright** [comment]
The code still exists, but it was mostly a drive to get things over before the compiler/python/r migration. My hope is that we catch most of the noarch-able packages before they get through staged-recipes. We also ended up having the bot issue some bad PRs and so decided to turn it off.

**Comment by tkelman** [comment]
Does the linter know the difference between staged-recipes vs feedstocks when it decides what message to post?

**Comment by isuruf** [comment]
Yes, https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/lint_recipe.py#L448

**Comment by tkelman** [comment]
Thanks, so what about something like https://github.com/tkelman/conda-smithy/commit/6b9f6941c86b1e793974e44e6a7880ea1b3b9337, so the #1021 lint message comes across in staged-recipes but not feedstocks?

**Comment by isuruf** [comment]
I'm okay with that. (I would change the condition to `and (is_staged_recipes or not conda_forge)` )

**Comment by tkelman** [comment]
Can open a PR from that branch later, any thoughts before I do @jan-janssen ?

**Comment by jan-janssen** [comment]
Sounds good to me - I have to admit I was not aware of this option before.
