### ISSUE TITLE
linter: Ensure downloads have a checksum

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#104]
Would be nice to ensure all downloads have a checksum. Could possibly also verify that it is correct.

**Comment by pelson** [comment]
:+1: 

> Could possibly also verify that it is correct.

:-1: - the linter doesn't check that ```build.sh``` builds a package - that is the job of the builder. I think the same argument could be made for the checksum.

Anyway, it is a nice easy PR. If we aren't in a rush, might be a good one for a conference sprint.

**Comment by jakirkham** [comment]
Fair, I thought the verification was a reach. Mainly was just borrowing this from how `conda skeleton pypi` works (download the package and computes the checksum). Honestly verification will already happen through the build so I doubt it is necessary for the linter to do this. To me, simply checking that there is a checksum (maybe the right length) and warning if not is already quite helpful.

**Comment by pelson** [comment]
Closed by #130

**Comment by jakirkham** [comment]
Thanks @pelson.
