### ISSUE TITLE
Move to travis-ci.com for new feedstocks

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#1047]
This way feedstocks are automatically registered and we don't have to register it ourselves.

**Comment by mariusvniekerk** [comment]
What's involved with this?

**Comment by isuruf** [comment]
Changing the URL to .com depending on if it's a new feedstock or not

**Comment by mariusvniekerk** [comment]
How do we determine if something is a new feedstock

**Comment by isuruf** [comment]
An option in conda-build.yml?

**Comment by mariusvniekerk** [comment]
or can we just assume it by default.  I don't know of anything other than staged recipes that calls this

**Comment by jakirkham** [comment]
The main thing, which I was wanting to bring up earlier, is we need to create the Anaconda upload token. Does the API work with the .com endpoint?

**Comment by isuruf** [comment]
> or can we just assume it by default. I don't know of anything other than staged recipes that calls this

the badges are different.

**Comment by jakirkham** [comment]
Closing as I believe this is done at this point. Though please feel free to reopen if that's not the case.
