### ISSUE TITLE
document who to ping to merge PRs on a feedstock

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-smithy#1073]
We should add instructions to ping @conda-forge/<name of feedstock> when PRs are ready to merge.

**Comment by CJ-Wright** [comment]
You could put it in the PR template also (maybe even the linter bot all clear messages)

**Comment by beckermr** [comment]
Yup. I’ve been swamped with work. I’ll try to make a pr but no promises

**Comment by isuruf** [comment]
Or create a CODEOWNERS file so that maintainers are automatically review requested.

**Comment by beckermr** [comment]
Ohhh that’s a nice feature. Probably best to do both.

**Comment by jakirkham** [comment]
There’s also the mergify bot. That was brought up elsewhere.

**Comment by beckermr** [comment]
Lol. Mergify? I don’t know anything about that one...

**Comment by jakirkham** [comment]
Yep, please issue ( https://github.com/conda-forge/conda-forge.github.io/issues/722 ) for the discussion on mergify.

**Comment by jakirkham** [comment]
@beckermr, did PR ( https://github.com/conda-forge/conda-smithy/pull/1086 ) resolve this or is there more still needed?

**Comment by beckermr** [comment]
The codeowners file pings ppl automatically, but it does so at the start of the PR, not the end. So telling people explicitly might still be good. However, I am happy if this one is closed also.

**Comment by jakirkham** [comment]
Yes. We also [document them in the README]( https://github.com/conda-forge/conda-smithy/blob/ebf20d5145e00bcba06a875d6c036103032db792/conda_smithy/templates/README.md.tmpl#L262-L268 ).

No objection to more improvements here. Though are we suggesting repurposing the issue and changing the goal? Or would that make more sense as a new issue?

**Comment by beckermr** [comment]
I don’t have strong feelings here. Happy to close.

**Comment by jakirkham** [comment]
Me neither. Just triaged a bunch of issues and was leaning towards closing here. Ok to keep open. Maybe I'm just not understanding the intended change.

**Comment by beckermr** [comment]
Nah let's close.
