### ISSUE TITLE
Proper handling of compatible release ~= version spec

### ISSUE THREAD

**Issue by hajapy** [conda-forge/conda-smithy#1075]
Recently, I contributed two recipes that made use of the [PEP-440 compatible release "~=" specifier](https://www.python.org/dev/peps/pep-0440/#compatible-release), since the upstream packages used this spec. This is [supported by conda >=4.6](https://docs.conda.io/projects/conda/en/latest/release-notes.html#id53), but caused at least one noticeable issue within conda-forge infrastructure: when the feedstocks were generated, I was not properly added as a maintainer of those. Regardless, one concern is that such packages are not compatible with old conda versions. It might be worthwhile to add a linting rule to at least warn contributors of this use and suggest an alternate / safer form to use. In my case, I converted specs like `six ~=1.11` into `six >=1.11,<2`.

**Comment by ltalirz** [comment]
Switching to `~=` operator did at least not affect the listed maintainers in my case, but it certainly led to [strange linter recommendations](https://github.com/conda-forge/aiida-core-feedstock/pull/24#issuecomment-585255884).
I guess the linter should simply say that `~=` should not be used?
