### ISSUE TITLE
Drone CI registration

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#1079]
Recently we added support for rendering feedstock content needed to build packages on Drone for ARM ( https://github.com/conda-forge/conda-smithy/pull/1069 ). However this does not currently include support for registering new (or existing) feedstocks on the Drone CI service. It would be good to do this as well so maintainers can use Drone on their feedstocks.

**Comment by jakirkham** [comment]
@conda-forge/core, can someone please confirm if this is completed and if so close it? Thanks!

**Comment by mariusvniekerk** [comment]
This has been done.
