### ISSUE TITLE
re-rendering is adding a __pycache__/ directory

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/conda-smithy#1082]
Latest conda-smithy is adding a `__pycache__/` to the feedstocks, not sure if that was intentional.

**Comment by scopatz** [comment]
That is not intentional.  Is it in the .gitignore at least? Or is it being checked in?

**Comment by ocefpaf** [comment]
It is being checked in. We need to update the gitignore and make conda-smithy remove those in the next release.

I also noticed that if you try to rerender in the `recioe` directory conda-smithy creates some of the files there before it fails. So some feedstocks are geeting contaminated with things like a `.github` directory in the `recipe` dir.

**Comment by scopatz** [comment]
Yeah, agreed.  Happy to review / push out a new release for this

**Comment by jakirkham** [comment]
> I also noticed that if you try to rerender in the `recioe` directory conda-smithy creates some of the files there before it fails. So some feedstocks are geeting contaminated with things like a `.github` directory in the `recipe` dir.

For this we could default to the git root directory of the current working directory instead of just the current working directory.

**Comment by jakirkham** [comment]
> > I also noticed that if you try to rerender in the `recioe` directory conda-smithy creates some of the files there before it fails. So some feedstocks are geeting contaminated with things like a `.github` directory in the `recipe` dir.
> 
> For this we could default to the git root directory of the current working directory instead of just the current working directory.

Raised as issue ( https://github.com/conda-forge/conda-smithy/issues/1084 ).

**Comment by jakirkham** [comment]
> We need to update the gitignore and make conda-smithy remove those in the next release.

Interestingly we [already do]( https://github.com/conda-forge/conda-smithy/blob/b49aca50ce695631d3798167faada00cf9c0b117/conda_smithy/feedstock_content/.gitignore#L1 ). Am curious why that doesn't work actually. 🤔

**Comment by jakirkham** [comment]
@scopatz, would you be willing to do the honors and cut a patch release?
