### ISSUE TITLE
Linter: Make license_file field required.

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#1088]
@conda-forge/core, thoughts?

For meta packages, the feedstock license can be packaged using `../LICENSE.txt`

**Comment by dougalsutherland** [comment]
:+1:, though maybe a hint instead of a requirement?

**Comment by scopatz** [comment]
Well, packages that are in the public domain don't have a license. I think whether or not it is required is somewhat dependent on the license / license family.

**Comment by jakirkham** [comment]
Generally agree. Though would also suggest hint instead.

Should add that there are some packages that are pushed to PyPI that never include a license file and do not have an issue tracker to report this issue. The result is there are a small number of things that don't have licenses even if they should.

**Comment by dougalsutherland** [comment]
We could make the lint conditional on the value of `license` for things like public domain.

**Comment by scopatz** [comment]
Yeah, I think it should be conditional.  Because for manhy licenses it is truly required.

**Comment by jakirkham** [comment]
> Should add that there are some packages that are pushed to PyPI that never include a license file and do not have an issue tracker to report this issue. The result is there are a small number of things that don't have licenses even if they should.

Any thoughts on this point? Should add I see this not just in PyPI packages, but in some C libraries where they reference a license, but never add the license file themselves. 🤷‍♂

**Comment by isuruf** [comment]
If they don't have a license file, the package should not be packaged in conda-forge.

**Comment by jakirkham** [comment]
I'm not sure I agree. Also there are already packages like this on conda-forge.

**Comment by jakirkham** [comment]
It also doesn't sound like the consensus we reached here either.

**Comment by isuruf** [comment]
I mean if they are released as public domain, the license is not required. If it is BSD where the copyright and license text is required and the package doesn't have a license file, you can't distribute it unless we have the copyright and license text from the sources.

**Comment by jakirkham** [comment]
We should certainly push upstream to be proactive and fix these issues as we have. Unfortunately this is a bit impractical.

**Comment by jakirkham** [comment]
I've submitted a PR ( https://github.com/conda-forge/conda-smithy/pull/1102 ) so we can discuss this further there.
