### ISSUE TITLE
Limit numpy versions

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-smithy#109]
We currently build against numpy:

 * 1.9
 * 1.10
 * 1.11

We should drop 1.9 from the template.

**Comment by ocefpaf** [comment]
I am OK. (Even though yesterday I spent some time preparing the `cdat-lite` and `cfchecker` recipes for staged-recipes :wink: )

**Comment by jakirkham** [comment]
Do we have an idea of how many 1.9 ABI linked packages are being downloaded? Also, it would be good if we could tease out what is coming from CI and what is actually being used in the wild (though this will be tricky).

**Comment by pelson** [comment]
I should have linked to it before, but https://github.com/conda-forge/conda-smithy/pull/111 limits to ```numpy >=1.10```.

Some analysis of what is being used would be helpful though I think.

**Comment by pelson** [comment]
So #111 was merged which removed 1.9
