### ISSUE TITLE
Skip Python 2.7

### ISSUE THREAD

**Issue by hgrecco** [conda-forge/conda-smithy#1110]
What is the right way to skip Python 2.7 builds? I want to build only for Python 3.6 and 3.7. I have tried setting `min_py_ver: '36'` but I am still getting 2.7.

**Comment by ocefpaf** [comment]
This is a conda-build questions and you can check the docs here:

https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#skipping-builds

TL;DR

```
skip: True  # [py2k]
```
