### ISSUE TITLE
Linter complains about disable_pip

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#1114]
`disable_pip` is a valid conda-build recipe option. ( https://github.com/conda/conda-build/pull/1311 ) However it is [raised as lint]( https://github.com/conda-forge/pip-feedstock/pull/31#issuecomment-514098420 ) currently. Would be good to correct the linter's behavior here.

**Comment by CJ-Wright** [comment]
I think the issue is that the conda build PR did not add it to ``conda_build.metadata.FIELDS`` so the linter doesn't know better.

**Comment by jakirkham** [comment]
`disable_pip` lives under `build`. I thought `FIELDS` was only for top-level metadata. Is that not correct?

**Comment by isuruf** [comment]
No, FIELDS has two levels. https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L485-L517

**Comment by jakirkham** [comment]
My mistake. Thanks for correcting me. Submitted PR ( https://github.com/conda/conda-build/pull/3627 ).
