### ISSUE TITLE
Customize .gitignore for feedstock repo

### ISSUE THREAD

**Issue by refraction-ray** [conda-forge/conda-smithy#1118]
Any suggestions on how to customize `.gitignore` file for feedstock repo rendered by conda smithy?  One might want to omit irrelevant files, say `.DS_Store`, by adding them into .gitignore.

From the source, it seems to me that these files are directly copied from `feedstock_content` dir everytime the repo gets `conda smithy rerender`ed.

One solution is to edit .gitignore file in feedstock_content dir directly in local machine. However, since conda-smithy is a site-package in general, it is not a good practice to hack any code there. Besides, one conda-smithy package could be responsible for rendering many feedstock repos, which probably require different items in their own .gitignore.

One can also directly edit the .gitignore file in feedstock repo after conda smithy rerender. However, this file would revert back (to only .pyc lines) everytime you rerender the repo.

Is there currently any good practice on this? Or should .gitignore file also go through a similar render function (which can take configurations from conda-forge.yml) like what we have done on rendering the readme file?

**Comment by scopatz** [comment]
I am pretty sure .gitignore is part of the render process. If you want to customize it, then yeah, the proper route is through `conda-forge.yml`

**Comment by mariusvniekerk** [comment]
Presently it is given by https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/feedstock_content/.gitignore

**Comment by refraction-ray** [comment]
> Presently it is given by https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/feedstock_content/.gitignore

Yep, that's what I mean. Since conda-smithy is in general downloaded as a site-package when using, i guess it is not a good move for the user to edit the .gitignore file directly in feedstock_content dir. So maybe we should make .gitignore file go through the same render process controlled by conda-forge.yml. But now, 
https://github.com/conda-forge/conda-smithy/blob/e37020eabebf39563accf1788c92f93a4abaabac/conda_smithy/configure_feedstock.py#L1198-L1200
it seems to me, the file is just directly copied to the rendered feedstock repo.

**Comment by mariusvniekerk** [comment]
Yep that's exactly what happens.  Feel free to make a PR to improve it with pieces that prevent certain silly files (like osx's ones) from accidentally entering the repo.
