### ISSUE TITLE
Building against multiple Docker images

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#1125]
Looking at PR ( https://github.com/conda-forge/conda-smithy/pull/1070 ), it seems we assume there should only be one relevant `docker_image` in each `config`. Am curious if there is a reason for that assumption? More importantly would it be reasonable to generalize this to allow more than one `docker_image`?

**Comment by jakirkham** [comment]
cc @isuruf @mariusvniekerk

**Comment by isuruf** [comment]
Each `config` should have one `docker_image`. If you want to build against multiple docker images, you can have multiple configs.

**Comment by jakirkham** [comment]
I don't quite follow. Was thinking `docker_image` could be a list in `conda_build_config.yaml` and it would try each one. However it appears to be grabbing the last value by sorted order. I'm guessing this will also be a problem when handing this for GPU packages generally ( https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/237 ). Take PR ( https://github.com/conda-forge/ucx-split-feedstock/pull/6 ) for example. Is there a different way I should be doing this or is this not possible without making changes to conda-smithy?

**Comment by isuruf** [comment]
You need to make `docker_image` or another variable that is zipped with it be a used `variable`.

**Comment by jakirkham** [comment]
Why is that needed?

**Comment by isuruf** [comment]
That's how conda-smithy works. Just because there are 3 python versions in `conda_build_config.yaml`, that doesn't mean there are 3 jobs for recipes not using python. You need to use `docker_image` somewhere in the recipe (or a variable zipped with it).

**Comment by jakirkham** [comment]
I see. So you just mean it needs to be used in the `meta.yaml` somehow. Yeah that makes sense. Thanks. 🙂
