### ISSUE TITLE
pycrypto is unmaintained and vulnerable

### ISSUE THREAD

**Issue by hajapy** [conda-forge/conda-smithy#1126]
Why is pycrypto used over pycryptodome?

https://github.com/conda-forge/conda-smithy/blob/507e638913454d32d5c8f3c9c9823555f6c42b05/conda_smithy.recipe/meta.yaml#L27

This project is no longer maintained: https://github.com/dlitz/pycrypto/issues/285

**Comment by jakirkham** [comment]
I don't know of any reason. Care to send a PR to update it?

**Comment by mingwandroid** [comment]
Debian maintain this now. I source CVE fixes from there.

**Comment by mingwandroid** [comment]
Well, they maintain it in the de-facto sense, not officially. Still, the sky is far from falling on us due to this.

**Comment by hajapy** [comment]
I'm not quite sure what you mean @mingwandroid. The 4 patches here: https://github.com/conda-forge/pycrypto-feedstock/tree/master/recipe don't seem related to CVE issues, just build / test workarounds. Perhaps you mean for conda itself? In any case, pycryptodome should be a drop in replacement and preferred where possible (and hence these two packages generate a ton of `ClobberError` if you install them together).

**Comment by hajapy** [comment]
@jakirkham PR opened.

**Comment by mingwandroid** [comment]
@hajapy: I support switching things out though for sure. I didn't realise a resync hadn't happened yet, aplogies.

Here is a PR to discuss that: https://github.com/conda-forge/pycrypto-feedstock/pull/15

Thanks for the reminder.

**Comment by mariusvniekerk** [comment]
Should we have a mutually exclusive mutex?

**Comment by mingwandroid** [comment]
Do they clobber each other? I guess they would. If so, would we require another big migration?

**Comment by hajapy** [comment]
They definitely clobber each other (I think that was the intent!). I don’t think there are a ton more packages that still use pycrypto but there are a few for sure.

**Comment by jakirkham** [comment]
If we switched to `pycryptodomex`, we wouldn't have a clobbering problem. Though we would need to update a couple of `import`s
