### ISSUE TITLE
linter: Provide line numbers for errors

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#115]
Brought up another issue and best summarized by [this comment]( https://github.com/conda-forge/conda-smithy/issues/97#issuecomment-202588603 ). Basically, we would want this feature so the linter commenting bot could comment on PR diffs thus providing context for users as to what is missing and where it needs to go, which is summarized this linter commenting bot issue ( https://github.com/conda-forge/conda-forge-webservices/issues/3 ).

**Comment by pelson** [comment]
Just linking this to https://github.com/conda-forge/conda-smithy/issues/105. :+1:

**Comment by jakirkham** [comment]
Ah, missed that one, sorry. Should we close this out then or would you prefer it remain also in a separate issue?

**Comment by pelson** [comment]
It's fine. When it gets fixed, we can close this issue. It's not like we are drowning in a sea of issues yet. :smile:

**Comment by jakirkham** [comment]
We are drowning in a sea of issues. 😆 Closing as a dup.
