### ISSUE TITLE
Question: 32bit Windows builds missing (intentional)?

### ISSUE THREAD

**Issue by MSeifert04** [conda-forge/conda-smithy#1150]
It's about my feedstock [iteration_utilities-feedstock
](https://github.com/conda-forge/iteration_utilities-feedstock) - and I hope this is the correct repository to ask such a question.

the builds "1 year and 2 months ago" (Juli 2018) included the 32bit windows builds, however after some re-renderings (Jan 3) these went missing. So I did another re-render today and it contained windows builds on azure (I assumed 32bit) and some on appveyor (I assume 64bit) and assumed that this would provide the win-32 builds again.

However after merging the re-render the 32bit builds for windows are still missing in the package-conda-channels [files](https://anaconda.org/conda-forge/iteration_utilities/files).

Was this some intentional change or am I just doing something wrong.

**Comment by isuruf** [comment]
Yes, it is. We dropped support for 32-bit windows builds

**Comment by MSeifert04** [comment]
Thank you for the clarification. :+1:
