### ISSUE TITLE
The build phase is set to "MSBuild" mode on AppVeyor

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda-forge/conda-smithy#1155]
Hi,

**regro-cf-autotick-bot** generated a PR to update a feedstock where I am skipping Windows builds:
https://github.com/conda-forge/gstreamer-orc-feedstock/pull/1

However, AppVeyor keeps kicking in and failing with:
```
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.
```

Is this expected?

Best regards,
Sebastian

**Comment by isuruf** [comment]
There were 2 appveyor repos registered. I removed the problematic one.
