### ISSUE TITLE
Extend skip_render

### ISSUE THREAD

**Issue by saraedum** [conda-forge/conda-smithy#1161]
conda-smithy takes a list of files in the `skip_render` option of the `conda-forge.yml`. These files are not modified as part of the rerender.

Currently, this only works for a small number of files such as the `README.md`.

I would like to extend this. However, it feels wrong to add more code blocks all over the place such as
```
if file in config.skip_render:
  log(skipping file…)
  continue
```

It appears to me that it would make more sense to push this out to `feedstock_io`, i.e., `feedstock_io` should completely ignore any files in `skip_render`. E.g., `write_file` would just open `os.devnull` when the file to be written is in the `skip_render` list.

However, for this to work, `feedstock_io` needs access to the conda forge config. I could of course pass in the config as an argument into every operation. But that again feels wrong to me.

So the config could either be a global variable (which also does not seem right) or every method in `feedstock_io` would be wrapped in a class that knows about the config (and potentially some other things.) A third option is for `feedstock_io` to search for the config itself just as it searches for the git repository itself already.

Such a change would touch quite a few lines of code. So before I begin to work on this… What do you think?

**Comment by isuruf** [comment]
What files do you want to skip?

**Comment by saraedum** [comment]
In my particular use case: `.gitattributes`, everything that goes into `.github`, `LICENSE.txt`, `README.md`, `.gitignore`, `build-locally.py`. Maybe I forget something that was added recently.

**Comment by isuruf** [comment]
`skip_render` can skip `.gitattributes, LICENSE.txt, README.md, .gitignore, build-locally.py`. So, you need a way to skip `.github/CODEOWNERS`? You can do that by removing the recipe-maintainers in meta.yaml with the 3.5.0

**Comment by saraedum** [comment]
Oh wow. I totally missed how these things had moved in the meantime it seems. Sorry for the noise then.

**Comment by saraedum** [comment]
One problem is certainly, that the value of the environment variable is shown in the build log:
```
/home/jule/proj/conda/miniconda3/lib/python3.7/site-packages/conda_build/environ.py:426: UserWarning: The environment variable 'MYVAR' is being passed through with value SECRETSECRETSECRET.  If you are splitting build and test phases with --no-test, please ensure that this value is also set similarly at test time.
```
