### ISSUE TITLE
Inject more secret tokens into conda build

### ISSUE THREAD

**Issue by saraedum** [conda-forge/conda-smithy#1162]
I am (ab)using conda-smithy for some generic CI tasks. For example I build nightlies for a project and create coverage statistics as part of the `build.sh`. See https://github.com/flatsurf/exact-real for an example.

I would like to be able to upload these coverage statistics to coveralls or similar. For this I need to be able to inject a secret into the conda build environment. Currently, only the `BINSTAR_TOKEN` is passed on.

Is this use case considered beyond the scope of conda-smithy, or should I work on a PR for such a feature?

Currently, I use a patched conda-smithy:

* I need to load them from the CI configuration:
```patch
--- a/conda_smithy/templates/azure-pipelines-linux.yml.tmpl
+++ b/conda_smithy/templates/azure-pipelines-linux.yml.tmpl
@@ -37,3 +37,4 @@ jobs:
     displayName: Run docker build
     env:
       BINSTAR_TOKEN: $(BINSTAR_TOKEN)
+      COVERALLS_REPO_TOKEN: $(COVERALLS_REPO_TOKEN)
```

* Make them available inside docker:
```patch
--- a/conda_smithy/templates/run_docker_build.sh.tmpl
+++ b/conda_smithy/templates/run_docker_build.sh.tmpl
@@ -63,6 +63,7 @@ export UPLOAD_PACKAGES="${UPLOAD_PACKAGES:-True}"
            -e CONFIG \
            -e BINSTAR_TOKEN \
            -e HOST_USER_ID \
+           -e COVERALLS_REPO_TOKEN \
            -e UPLOAD_PACKAGES \
            -e GIT_BRANCH \
            -e UPLOAD_ON_BRANCH \
```

* Make them available to conda-build:
```patch
--- a/conda_smithy/templates/build_steps.sh.tmpl
+++ b/conda_smithy/templates/build_steps.sh.tmpl
@@ -12,3 +12,7 @@ export RECIPE_ROOT="${RECIPE_ROOT:-/home/conda/recipe_root}"
 export CI_SUPPORT="${FEEDSTOCK_ROOT}/.ci_support"
 export CONFIG_FILE="${CI_SUPPORT}/${CONFIG}.yaml"
 
+# Inject secrets into conda-build which filters the environment. If we
+# whitelisted explicitly in meta.yaml, these would be publicly readable in the
+# uploaded package at anaconda.org.
+export -p | grep COVERALLS_REPO_TOKEN >> /tmp/secrets || true
```

The last step is really not pretty. I am happy to hear any better ideas on how to achieve this :)

**Comment by isuruf** [comment]
>  If we whitelisted explicitly in meta.yaml, these would be publicly readable in the uploaded package at anaconda.org.

I don't understand. Do you have an example?

**Comment by saraedum** [comment]
Let me verify that this is still the case actually.

**Comment by saraedum** [comment]
One problem is certainly, that the value of the environment variable is shown in the build log when using `build.script_env` in `meta.yml`:
```
/home/jule/proj/conda/miniconda3/lib/python3.7/site-packages/conda_build/environ.py:426: UserWarning: The environment variable 'MYVAR' is being passed through with value SECRETSECRETSECRET.  If you are splitting build and test phases with --no-test, please ensure that this value is also set similarly at test time.
```

**Comment by saraedum** [comment]
@isuruf: Ok. So the value of the variable is not in the anconda upload (anymore?) But it shows up in the logs which is pretty bad of course.

**Comment by saraedum** [comment]
If I remember correctly, azure hides these variables but that wouldn't work with other CIs probably.

**Comment by isuruf** [comment]
We used to allow customizing `upload_or_check_non_existence.py` at https://github.com/conda-forge/conda-smithy/blob/6837490e2ba0e90abe909242abfa4338f256c084/conda_smithy/configure_feedstock.py#L633, but somebody has removed it. We should bring that back.

**Comment by isuruf** [comment]
Or add a line at https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/master/recipe/conda_forge_ci_setup/build_utils.py#L142 checking if there's a `recipe/post_process.py` and run that script.

**Comment by saraedum** [comment]
Unfortunately, I need these variables in `build.sh`. What you are proposing happens after conda-build has finished, correct?
(I need them in build.sh because I need all the build artifacts intact. I could of course package all the build artifacts and the unzip them again later but it's probably annoying to figure out all the paths then when the environment variables set by conda-build are not around anymore.)

**Comment by isuruf** [comment]
Okay. How about fixing `conda-build` to not echo those env variables?

**Comment by saraedum** [comment]
That's probably a good idea. Then I'd just add the first two patches to conda-smithy.

**Comment by saraedum** [comment]
@isuruf, the PR to conda-build passes tests. Feel free to weigh in there if you have anything to add :)

**Comment by saraedum** [comment]
I created #1343 to address this. @isuruf, what do you think about this approach?
