### ISSUE TITLE
Check for duplicate package additions

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#117]
If someone tries to add a package twice (e.g. to staged-recipes when it is already a feedstock), it would be nice if the linter politely told one to get rid of it and PR the changes.

Better still would be if staged-recipes could take the difference and PR them against the correct feedstock. However, that is a separate issue ( https://github.com/conda-forge/staged-recipes/issues/272 ).

**Comment by pelson** [comment]
> If someone tries to add a package twice (e.g. to staged-recipes when it is already a feedstock), it would be nice if the linter politely told one to get rid of it and PR the changes.

:+1: 

I think this is a job for another webservice. All it needs to do is look at staged-recipe pulls, and determine if there is already a feedstock with that name. I think it still lives in https://github.com/conda-forge/conda-forge-webservices though.

**Comment by jakirkham** [comment]
However, you think it should be done is fine with me. Will this run in the same Heroku instance then or will it get its own?

**Comment by jakirkham** [comment]
Starting to wonder if conda-forge-webservices deserves (  https://xkcd.com/1629/ ) more. :wink:

**Comment by pelson** [comment]
> However, you think it should be done is fine with me. Will this run in the same Heroku instance then or will it get its own?

I named the heroku instance conda-forge rather than conda-linter for this reason :wink: - I'd re-use the existing one.

**Comment by jakirkham** [comment]
Agreed. Moving to webservices.

**Comment by jakirkham** [comment]
Issue moved to [conda-forge/conda-forge-webservices #42](https://github.com/conda-forge/conda-forge-webservices/issues/42) via [**ZenHub**](https://www.zenhub.com/)
