### ISSUE TITLE
Latest smithy breaks imports

### ISSUE THREAD

**Issue by peterhurford** [conda-forge/conda-smithy#1172]
I [made a PR](https://github.com/conda-forge/datarobot-feedstock/pull/22) to update [my feedstock](https://github.com/conda-forge/datarobot-feedstock) and [the build](https://github.com/conda-forge/datarobot-feedstock/pull/22/checks?check_run_id=251074572) breaks [with](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=78696) `ModuleNotFoundError: No module named 'urllib3'`.

The only change made in the PR is `@conda-forge-admin, please rerender`, thus the rerendering script must be breaking something with imports.

PR: https://github.com/conda-forge/datarobot-feedstock/pull/22
Build: https://github.com/conda-forge/datarobot-feedstock/pull/22/checks?check_run_id=251074572
Build error: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=78696

**Comment by peterhurford** [comment]
Possibly related to https://github.com/conda-forge/conda-smithy/issues/817

**Comment by isuruf** [comment]
This is unrelated
