### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#1177]
Thoughts on doing a new release?

cc @conda-forge/core

**Comment by mariusvniekerk** [comment]
Punch it!

**Comment by jakirkham** [comment]
Tagged [v3.6.0]( https://github.com/conda-forge/conda-smithy/releases/tag/v3.6.0 ) and submitted the feedstock update PR ( https://github.com/conda-forge/conda-smithy-feedstock/pull/167 ).

**Comment by jakirkham** [comment]
Release deployed! The webservice bot has also been redeployed with this release. 😄
