### ISSUE TITLE
Release 3.6.0 yields failing drone builds

### ISSUE THREAD

**Issue by fhoehle** [conda-forge/conda-smithy#1179]
I'm facing some issues related to recent release and drone builds see https://github.com/conda-forge/tktable-feedstock/pull/4.
Release 3.6.0 renames `.azure-pipelines/build_steps.sh` → `.scripts/build_steps.sh` and deletes the corresponding drone specific script. Both `build_steps.sh ` have a slight difference:

```
diff -u .drone/build_steps.sh .azure-pipelines/build_steps.sh
--- .drone/build_steps.sh	2019-10-13 10:52:26.000000000 +0200
+++ .azure-pipelines/build_steps.sh	2019-10-13 10:52:26.000000000 +0200
@@ -24,7 +24,8 @@
 # set up the condarc
 setup_conda_rc "${FEEDSTOCK_ROOT}" "${RECIPE_ROOT}" "${CONFIG_FILE}"
 
-run_conda_forge_build_setup
+source run_conda_forge_build_setup
+
 
 # Install the yum requirements defined canonically in the
 # "recipe/yum_requirements.txt" file. After updating that file,
```

The added `source` yields a failing:
```
touch /drone/src/build_artifacts/conda-forge-build-done-linux_aarch64_ 
```
see https://cloud.drone.io/conda-forge/tktable-feedstock/4/1/2, which was fine without sourcing.

I'm not sure if this is the right place to raise that issue since it could be related to environment variables and docker images used in drone builds. Local testing `./build-locally.py linux_aarch64_` is successful.
Thanks for help.

**Comment by isuruf** [comment]
I think the issue is with https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/master/recipe/run_conda_forge_build_setup_linux#L9 where `/home/conda/feedstock_root` is not correct. It should just use `export "CONDA_BLD_PATH=$FEEDSTOCK_ROOT/build_artifacts"`

**Comment by jakirkham** [comment]
Fixed in PR ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/65 ).
