### ISSUE TITLE
Create a no build badge

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/conda-smithy#119]
The README looks broken when we don't have a Windows build.

![appv](https://cloud.githubusercontent.com/assets/950575/14286128/6418fac2-fb24-11e5-99b9-48870be35b9f.png)

**Comment by pelson** [comment]
:+1: 

Relates to #79

**Comment by ocefpaf** [comment]
We could use

![nobuild](https://ci.appveyor.com/api/projects/status/32r7s2skrgm9ubva?svg=true)

but I am don't know how to create an if-clause with jinja inside for the template.

**Comment by jakirkham** [comment]
Sounds like a good idea to have something other than a broken link.

I just wonder if saying build passing will come across as deceptive (even though that is clearly not the intention). Maybe we could look at other images AppVeyor has for something that fits.

**Comment by ocefpaf** [comment]
That was not the image I wanted! I guess I messed up the links. I meant build pending.

**Comment by jakirkham** [comment]
Oh ok, no worries. Pending sounds promising.

**Comment by jakirkham** [comment]
A bit off topic, but this site ( http://shields.io/ ) is pretty great for badges too. We could look at generating custom badges for things like licenses or metadata we get from other places.

**Comment by ocefpaf** [comment]
I liked this one:

[![Visual Studio Team services](https://img.shields.io/vso/build/larsbrinkhoff/953a34b9-5966-4923-a48a-c41874cfb5f5/1.svg)]()

**Comment by pelson** [comment]
👍 - that or "skipped"

**Comment by jakirkham** [comment]
Yeah, both of these sound good and are even better than pending. Honestly no preference between the two.

One thought though. We might want to save the badge in the repo just to ensure we have it.

**Comment by jakirkham** [comment]
How about this one?

![]( https://img.shields.io/badge/build-disabled-lightgray.svg )

**Comment by jakirkham** [comment]
I'm renaming this to no build as this is now a larger use case than it was before.

**Comment by jakirkham** [comment]
cc @janschulz

**Comment by jakirkham** [comment]
I think this amounts to having the CI rendering steps add some value to the `config` if they will build at all. That info can then be used in the Readme. See this [line]( https://github.com/conda-forge/conda-smithy/blob/4bf4aac0b5231d9bdf3d79f84b71d4cb3053b4cb/conda_smithy/configure_feedstock.py#L365 ). I'd be happy to do it if people would like, but it might not be for a few days.

**Comment by jakirkham** [comment]
Should add that I think we should include whatever substitute badge in the feedstock content. I know ( http://shields.io/ ) has had some caching issues in the past. If we have 100s of Readmes pointing there it might give them some issues, which could be easily avoided.

**Comment by jakirkham** [comment]
Basically we need to pass state from the CI steps to the Readme re-rendering step. So, I see 3 main ways to go about this.

1. Muck with `forge_config`/`config` to denote which CIs are building.
2. Return some sort of status/info from each CI step.
3. Check which CI files exist and update the Readme accordingly.

IMHO 1 or 2 sound better. 3 sounds pretty hacky, but is doable. What do we think about this?

**Comment by jakirkham** [comment]
I put this PR ( https://github.com/conda-forge/conda-smithy/pull/228 ) together which basically works. Sorry @ocefpaf I felt a little pressure to get this done after I went and disabled everyone's unused CIs leaving ugly badges behind. This should help prettify things.

**Comment by melund** [comment]
This should also work the other way. When no Linux or Mac builds are available. The AnyPyTools feedstock has this:

![image](https://cloud.githubusercontent.com/assets/1038978/17116320/8b3b916a-52b7-11e6-8dc2-a191ad03da12.png)

Which looks a bit ugly.

**Comment by jakirkham** [comment]
Absolutely, that's what PR ( https://github.com/conda-forge/conda-smithy/pull/228 ) does. See this [example]( https://github.com/conda-forge/inkscape-feedstock/blob/2b6b80faac9a79880707e8909f8c2086f7a09f89/README.md ) with Inkscape, which also only builds on Windows ATM. Though it will hide badges of whichever CIs are skipped regardless of what they might be.

The failure on CircleCI for AnyPyTools is an oddity that seems to be because CircleCI failed to skip for some reason. This is the first time I have seen this issue. I raised this issue with CircleCI in this [post]( https://discuss.circleci.com/t/circleci-built-skipped-branch-commit/5285 ). PR ( https://github.com/conda-forge/conda-smithy/pull/242 ) will fast finish CircleCI builds if they ignore skip so they will at least pass. Though we still plan to hide the badge in any event.

**Comment by melund** [comment]
Thanks. Do I need to rerender the feedstock, or do I get this automatically the next time I make a new release? Btw. Awesome that I can install inkscape through conda :)

**Comment by jakirkham** [comment]
It hasn't been accepted yet, but it is close. Once it is in a release either one can do the re-rendering themselves or (once it is back up and running) the bot will do a re-rendering for you.
