### ISSUE TITLE
linter should suggest spdx license string names or warn on them

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-smithy#1196]
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by scopatz** [comment]
I think we should have these in the documentation before we lint against them

**Comment by CJ-Wright** [comment]
Also I would appreciate some regex to fix the existing ones (I can put it into a piggy back migrator)

**Comment by beckermr** [comment]
Yeah that will be hard since it has been very wild west. :/

**Comment by jakirkham** [comment]
This has come up before. Some licenses just don't have SPDX equivalents. Like [HDF5]( https://github.com/conda-forge/hdf5-feedstock/blob/3dc150443a4048d9dbddec75d02c6e2b5b09d35d/recipe/meta.yaml#L191 ). Some are [difficult to describe succinctly]( https://github.com/conda-forge/miktex-feedstock/blob/52075aeb20a01cac8b69c683f43b8fb97a83e2f0/recipe/meta.yaml#L36 ). It could be interesting to approach this, but we need to be careful.

cc @conda-forge/core

**Comment by beckermr** [comment]
I don't feel strongly on this. I'm happy to use them if we can but otherwise not.
