### ISSUE TITLE
Change travis.yml from linux-ppc64le to separte os and arch tags for travsi-ci.com

### ISSUE THREAD

**Issue by jayfurmanek** [conda-forge/conda-smithy#1198]
Issue: travis-ci.com needs different os/arch defines in the travis.yml

https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z

We currently use the method below, which is now marked legacy:
```
os: linux-ppc64le
```

For the new style, we need to use:
```
os: linux
arch: ppc64le
```

**Comment by jakirkham** [comment]
Is this something you feel comfortable tackling, @jayfurmanek? 🙂

**Comment by jayfurmanek** [comment]
There’s a bit more than just this change I think. I’ve tried on some of my non-forge local repos and the new instances fired up super fast (containers vs VMs) but quickly errored.

I’ll try to at least identify what’s needed here and update this issue.

**Comment by jakirkham** [comment]
Ah ok. Thanks for clarifying. Yeah additional guidance would be good.

**Comment by jayfurmanek** [comment]
The new travis-ci.com uses LXD containers. Running Docker in LXD containers is weird.

It seems there is not TTY, so the `-ti` arguments won't work.
Dropping that gets us further, but then we hit:

```
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Unable to find image 'condaforge/linux-anvil-ppc64le:latest' locally
latest: Pulling from condaforge/linux-anvil-ppc64le
23bd9eb8fdc0: Pulling fs layer
293c34575e17: Pulling fs layer
23bd9eb8fdc0: Download complete
293c34575e17: Verifying Checksum
293c34575e17: Download complete
23bd9eb8fdc0: Pull complete
docker: failed to register layer: Error processing tar file(exit status 1): lchown /opt/conda/LICENSE.txt: invalid argument.

See 'docker run --help'.

The command "./ci_support/run_docker_build.sh" exited with 1.
```

Which is an issue with the overlay storage driver that docker uses not working right in an LXD environment. A similar issue over in the kube community: https://github.com/kubernetes/minikube/issues/946

I'll try a few things.

**Comment by mariusvniekerk** [comment]
So on my chromebook which also runs linux in an lxd container the storage driver for docker is
`btrfs` which seems to work fine.  This is obviously dependant on the host OS using that.

**Comment by jayfurmanek** [comment]
I tried to have it start up just a hello-world container and that worked ok.
So there is something specific to that layer in the anvil image where the `/opt/conda/LICENSE` file is that is causing the permissions issue.

**Comment by mariusvniekerk** [comment]
@jayfurmanek do you have a sample repository that we can play around with for this?

**Comment by mariusvniekerk** [comment]
I've dug into the images, and found the cause for the issue.  Will make the changes soonish after landing the new image builds

**Comment by jayfurmanek** [comment]
Nice! 
Oh and not sure if you still need an sample directory, I just set up a barebones repo and enabled the trigger to Travis-ci.com.  Seems like you are good to go though?

**Comment by mariusvniekerk** [comment]
https://travis-ci.com/conda-forge/zlib-feedstock/builds/138350723
