### ISSUE TITLE
Syncing with Drone exhausts GitHub API requests

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#1221]
It appears that syncing with Drone exhausts our GitHub API requests. Would be good to find an alternative way to add a repo to Drone without syncing. Perhaps they would also be willing to work with us on this problem.

**Comment by isuruf** [comment]
It's Travis-CI that exhausts the Github API. We are using the same github user for both Travis-CI and Drone-CI

**Comment by jakirkham** [comment]
Certainly true of Travis CI historically. Though I thought we move away from that mechanism when adding repos. Did this change? Am I misremembering?

I've seen this issue with Drone when clicking the sync UI button as well. How are we performing repo additions with Drone?

**Comment by jakirkham** [comment]
Maybe it is worth breaking out CI registration into two separate CLIs addition to CI and syncing. That way we can do multiple additions without syncing and then call sync once afterwards.

**Comment by isuruf** [comment]
> I've seen this issue with Drone when clicking the sync UI button as well. How are we performing repo additions with Drone?

No, drone uses only ~100 API requests. It's only travis-ci that exhausts the rate limit.

**Comment by isuruf** [comment]
Having two different accounts for drone and travis, fixed this error
