### ISSUE TITLE
Azure warning on OSX

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#1234]
> This pipeline uses a Microsoft-hosted agent image that will be removed on March 23, 2020 (MacOS-10.13). You must make changes to your pipeline before that date, or else your pipeline will fail. Learn more (https://aka.ms/removing-older-images-hosted-pools).

**Comment by timsnyder** [comment]
I got hit by the "rolling brownout" of macos-10.13 today.  See https://github.com/microsoft/azure-pipelines-image-generation/blob/master/README.md#rolling-brownouts-for-vs2015-win2012r2-macos-1013-win1803 

I'm happy to submit a PR for this, how do you usually test these things?  Change them and see what falls out?

**Comment by timsnyder** [comment]
Nevermind what I said about a PR.  Looks like this was already updated yesterday in #1239 and I just need to rerender.

**Comment by timsnyder** [comment]
@isuruf do you want to close this issue since it was fixed by #1239 ?

**Comment by jakirkham** [comment]
Let's go ahead and close. This should be solved by just re-rendering. If other things come up, we can always open a new issue 🙂
