### ISSUE TITLE
Generate .github/workflows/main.yml regardless of the automerge option

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#1235]
So that I can just add `[bot-automerge]` (or just `[automerge]`) to the title after a PR is sent

**Comment by isuruf** [comment]
Instead of `[automerge]` in the title which anybody can change, let's go with a label, so that only maintainers can set it.

**Comment by beckermr** [comment]
We don't use labels because the autotick bot cannot add them.

**Comment by beckermr** [comment]
The bot gets around this by checking who made the PR and only allowing automerge for PRs from the autotick bot user. 

We can stick to titles and add the maintainers to the good list of users. Or we can address this issue: https://github.com/regro/cf-autotick-bot-action/issues/28

**Comment by isuruf** [comment]
If either of the 2 checks pass, then we can merge,
1. [bot-automerge] in the PR title, PR sent by the bot and the `conda-forge.yml` has `bot: automerge: True`
2. PR has `automerge` label.

**Comment by beckermr** [comment]
yup exactly

but this does not effect turning this on globally since 1 already works

we just need to add 2 to the  regro/cf-autotick-bot-action code

**Comment by beckermr** [comment]
We made need to put in an additional check for the last item in 1

**Comment by jakirkham** [comment]
> Instead of `[automerge]` in the title which anybody can change, let's go with a label, so that only maintainers can set it.

By anybody, do you mean the PR author? Seems like all other cases would be a maintainer action. Or am I missing other ones?

**Comment by isuruf** [comment]
> By anybody, do you mean the PR author? 

Yes

**Comment by jakirkham** [comment]
Thanks. Agree label makes sense.
