### ISSUE TITLE
CFEP-09 migrations can't be updated

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#1243]
If a migration file needs to be updated for some reason, but doesn't need to be rebuilt, then we have to change thousands of feedstocks.

For eg: to add pypy, we have to enforce cpython for existing builds which means a change in `conda_build_config.yaml` and the python38 migrator, but we can't enforce cpython builds in python38 migrator because that is in feedstocks.

cc @conda-forge/core

**Comment by CJ-Wright** [comment]
Is this because we're going to ad that cpython constraint in the metadata patch? We need all future builds to have that constraint, but we can't force rerenders on all packages?

**Comment by isuruf** [comment]
@CJ-Wright, yes. Also, some versions of `python38.yaml` have python 2.7 aarch64 enabled and some don't (later ones) and adding the cpython constraint gives builds with cpython constraint and one without due to some weird interactions.
