### ISSUE TITLE
Migrator triggering child (postgis) before gdal/libgdal migrate

### ISSUE THREAD

**Issue by xylar** [conda-forge/conda-smithy#1260]
A feedstock (postgis) has a [pull request](https://github.com/conda-forge/postgis-feedstock/pull/40) for migration to `geos-3.8.1` even though one of its dependencies, `libgdal`, has not yet migrated.  The bot may be getting confused because there is an archived `libgdal-feedstock` but the current `libgdal` package is produced as part of the `gdal-feedstock`, which has (as of this writing) not yet migrated to `geos-3.8.1`: https://github.com/conda-forge/gdal-feedstock/pull/369

**Comment by scopatz** [comment]
This should probably be reported to regro/cf-scripts

**Comment by xylar** [comment]
@scopatz, thanks, I wasn't sure where would be best.  It's not always easy to follow the relationship between the different tools used by conda-forge.

**Comment by scopatz** [comment]
Yeah, I understand the confusion.  Migrators are implemented in cf-scripts, though :wink:
