### ISSUE TITLE
Allowing `Other (...)` for atypical `license` fields

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#1263]
For some atypical licenses, SPDX is not sufficient. It would help to have some syntax that allows users to specify the unusual nature of the license without running afoul of the linter. [One suggestion]( https://github.com/conda-forge/conda-smithy/pull/1220#issuecomment-600924602 ) is to allow `Other (...)`. Though really any variant of this should be fine.

cc @isuruf

**Comment by mbargull** [comment]
We could just stay within the SPDX spec and use the `LicenseRef-` prefix for this.

---
https://github.com/spdx/spdx-spec/blame/25c499eadbb2ffa1ab4e7dda7a2e6b364e876fe2/chapters/appendix-V-using-SPDX-short-identifiers-in-source-files.md#L57-L59 :
> Alternatively, you can use a `LicenseRef-` custom license identifier to refer to a license that is not on the SPDX License List, such as the following:
> 
>    SPDX-License-Identifier: LicenseRef-my-special-license

`my-special-license` is an "`idstring`" consisting of alphanumeric characters, `.` and `-`.
https://github.com/spdx/spdx-spec/blame/25c499eadbb2ffa1ab4e7dda7a2e6b364e876fe2/chapters/appendix-IV-SPDX-license-expressions.md#L11 :
> The exact syntax of license expressions is described below in [ABNF](http://tools.ietf.org/html/rfc5234).
> 
> idstring = 1*(ALPHA / DIGIT / "-" / "." )

----
Sure, `Other (free form text)` is more eye-pleasing than `LicenseRef-kebap-case--with.dots`, but
- this is for exceptions only,
- defined by a simple grammar, i.e. easily parsable by machine,
- we avoid future maintenance burden by not "rolling our own thing".

Plus, we can build on SPDX's future work, e.g., https://github.com/spdx/spdx-spec/issues/113 .

**Comment by isuruf** [comment]
I can implement either. @jakirkham ?

**Comment by jakirkham** [comment]
I don’t have strong feelings about direction here. Just as long as we have the option 🙂
