### ISSUE TITLE
Do not use deprecated SPDX identifiers

### ISSUE THREAD

**Issue by scopatz** [conda-forge/conda-smithy#1265]
As listed here: https://spdx.org/licenses

**Comment by mbargull** [comment]
Also note that the list is versioned and available in a tagged Git repository at https://github.com/spdx/license-list-data/blob/v3.8/licenses.md and programmatically accessible, see https://github.com/spdx/license-list-data/blob/v3.8/accessingLicenses.md#license-list-table-of-contents .

**Comment by isuruf** [comment]
@mbargull are license exceptions programmatically accessible as well? Couldn't find it.

**Comment by mbargull** [comment]
@isuruf, sure, https://github.com/spdx/license-list-data/tree/v3.8/json has `licenses.json` and `exceptions.json`.

**Comment by isuruf** [comment]
Download it everytime or make a conda package?

**Comment by mbargull** [comment]
Copying it over to this repository, i.e., shipping it with smithy should also be fine (while giving attribution, see https://github.com/spdx/license-list-data/blob/v3.8/accessingLicenses.md#tech-report-license). Whatever seems more convenient for you!
