### ISSUE TITLE
Pull migrations information from dynamic central store not the pinning package

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-smithy#1270]
Currently conda-smithy uses the pinning package to know which migrations need to be performed. This requires that new pinning versions be created for each migration. This causes a bunch of UX problems for the pinnings repo, since now the version/build number need to be bumped accordingly. Since the pinning package uses a date based versioning this can make things more difficult for users, since many times they will need to go into a PR and amend the version/build number. Additionally requiring that the migration go through a full package build and upload to the CDN adds an unneeded delay to the migration start.

I think that this system would be better if it pulled the migrations from a GitHub repo (most likely the pinning repo itself) directly, as this would eliminate the need for the new pinning package to made, reduce the number of downloads needed to perform a rerender, and restore the easier UX for migrations in the pinning repo.

**Comment by isuruf** [comment]
> This causes a bunch of UX problems for the pinnings repo, since now the version/build number need to be bumped accordingly.

We already need the CFP repo for rerendering. So, this is not a problem IMO.

> Since the pinning package uses a date based versioning this can make things more difficult for users, since many times they will need to go into a PR and amend the version/build number

For versioning we can use jinja for the date and add the hour and minute to the date as well.

> as this would eliminate the need for the new pinning package to made, reduce the number of downloads needed to perform a rerender,

This would increase downloads as we need to download the migrations for each rerendering.

**Comment by CJ-Wright** [comment]
> We already need the CFP conda package for rerendering. So, this is not a problem IMO.

Yes but now people will need to update their local CFP at least twice as often to rerender locally, with little benefit from newly downloaded data. I think this is less a "number of bytes downloaded" issue an more of a "I can't rerender, I need to conda install CFP again!" issue. The UX around rerendering when your CFP is out of date is kinda rough (it adds two more actions to an otherwise single command) so maybe the problem is there.

> For versioning we can use jinja for the date and add the hour and minute to the date as well.

This sounds good.

> This would increase downloads as we need to download the migrations for each rerendering.

Yes, but again this would be hidden from the UX so I'm less worried about it (esp since the amount of data pulled is low).

**Comment by CJ-Wright** [comment]
@isuruf how do you want to get the datetime into the jinja2?

**Comment by isuruf** [comment]
> I think this is less a "number of bytes downloaded" issue an more of a "I can't rerender, I need to conda install CFP again!" issue. The UX around rerendering when your CFP is out of date is kinda rough (it adds two more actions to an otherwise single command) so maybe the problem is there.

This same issue is there for `conda_build_config.yaml`. I agree. We can just update the conda env instead of exiting.

> how do you want to get the datetime into the jinja2?

`conda-build` passes `datetime` to jinja2 rendering, so we can use that.

**Comment by isuruf** [comment]
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/39/files

**Comment by CJ-Wright** [comment]
How should we address https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/39#issuecomment-380959260

**Comment by isuruf** [comment]
That was because we didn't have migration bot before. cc @jakirkham

**Comment by isuruf** [comment]
@CJ-Wright, do you want to open an issue about automatically updating CFP package?

**Comment by beckermr** [comment]
What does that mean @isuruf? I don't follow.

**Comment by isuruf** [comment]
> I think this is less a "number of bytes downloaded" issue an more of a "I can't rerender, I need to conda install CFP again!" issue. The UX around rerendering when your CFP is out of date is kinda rough (it adds two more actions to an otherwise single command) so maybe the problem is there.

@beckermr, the above issue is not fixed

**Comment by beckermr** [comment]
Right yeah. I don't think smithy automatically updating the pinnings package in your env if it is out of date is a great idea. I honestly don't think this should ever be fixed. The error message is clear, the burden on users is small, and we have provided much easier ways to rerender that work most of the time.
