### ISSUE TITLE
Linter failing to validate license field

### ISSUE THREAD

**Issue by hhslepicka** [conda-forge/conda-smithy#1272]
Issue:
Recently the linter started reporting suggestions on the license, which it was not before as many of our packages use the license as `SLAC Open`. See (https://github.com/conda-forge/staged-recipes/pull/11122).

@isuruf suggested to change from `SLAC Open` to `LicenseRef-SLAC` but now the linter complains:
```
The recipe license should not include the word "License".
```

<br/>
Environment (<code>conda list</code>):
PR https://github.com/conda-forge/staged-recipes/pull/11122

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>
PR https://github.com/conda-forge/staged-recipes/pull/11122
</details>

**Comment by isuruf** [comment]
We should move the code at https://github.com/conda-forge/conda-smithy/blob/38581061c88c6699581089fb1c94eacb07679dad/conda_smithy/lint_recipe.py#L199-L202 to https://github.com/conda-forge/conda-smithy/blob/38581061c88c6699581089fb1c94eacb07679dad/conda_smithy/lint_recipe.py#L638. Can you send a PR?

**Comment by hhslepicka** [comment]
@isuruf I'm not familiar with the codebase of `conda_smithy` to add this change. Sorry about that.
As much as I would like to do it I think that I will hit and miss miserably.

**Comment by isuruf** [comment]
This is fixed now
