### ISSUE TITLE
conda update being run after the ci install version is set on osx

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-smithy#1292]
The osx env is updated after the ci setup script package is installed so the 2.* is not respected.

**Comment by beckermr** [comment]
This problem is likely general. I think ci setup package should inject its version into the pinned file.

**Comment by beckermr** [comment]
or we need to patch the smithy recipe with the correct pin

**Comment by beckermr** [comment]
or we can put the pinning injection into the ci scripts by hand

**Comment by beckermr** [comment]
cc @isuruf

**Comment by isuruf** [comment]
We could use https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/run_osx_build.sh.tmpl on azure too and switch to miniforge.

**Comment by beckermr** [comment]
Is that robust enough? I am wondering if we want to directly pin the 2.* requirement in smithy's recipe.

**Comment by beckermr** [comment]
> We could use https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/run_osx_build.sh.tmpl on azure too and switch to miniforge.

I 100% agree with this change for the record. Right now the build scripts are pretty annoying to keep in sync. Having one per platform except windows is a big win.

**Comment by isuruf** [comment]
That script is osx specific. I think the conda update is because the root environment is already there with `defaults`. If we use conda-forge as the root environment, we don't need to update.

**Comment by beckermr** [comment]
> That script is osx specific. I think the conda update is because the root environment is already there with defaults. If we use conda-forge as the root environment, we don't need to update.

Yup. We'd have build_script.sh (or w/e it is called) on linux, and the one above for osx, which is one per platform except for windows.

**Comment by pkgw** [comment]
I suspect that everyone participating in this thread realizes this, but this is breaking at least some CI processing, e.g. conda-forge/rust-feedstock#51.

**Comment by beckermr** [comment]
I pulled the offending package, so try again it should work.
