### ISSUE TITLE
./.scripts/run_osx_build.sh: line 49: make_build_number: command not found

### ISSUE THREAD

**Issue by stuertz** [conda-forge/conda-smithy#1312]
Issue:
The OSX build fails after rerendering with `Re-rendered with conda-build 3.19.2, conda-smithy 3.7.0, and conda-forge-pinning 2020.05.06.22.15.02` in a `rebuild for pypy` pull  request, as in https://github.com/conda-forge/pyscss-feedstock/pull/12 with
```
./.scripts/run_osx_build.sh: line 49: make_build_number: command not found
```

Looks like the sh script is missing

**Comment by isuruf** [comment]
This was due to https://www.githubstatus.com/incidents/1p369ttzrnqy
