### ISSUE TITLE
use proper feedstock name in CFEP-13 validation

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-smithy#1322]
Right now we are not always getting the proper feedstock name in the CFEP-13 validation. 

see eg https://github.com/conda-forge/lalframe-feedstock/pull/17

This is likely due to rerendering in a clone of the repo to a dir that does not have the same name as its parent repo.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by duncanmmacleod** [comment]
For the `lalframe-feedstock` I have it cloned into a directory called `lalframe` on my host. It looks like @jakirkham tried to support this in #323:

https://github.com/conda-forge/conda-smithy/blob/360b332df9ae771e1ce6ebff6fff6eaa82d87103/conda_smithy/configure_feedstock.py#L1553-L1555

but that isn't used (perhaps as of #1295):

https://github.com/conda-forge/conda-smithy/blob/360b332df9ae771e1ce6ebff6fff6eaa82d87103/conda_smithy/configure_feedstock.py#L1827-L1828

**Comment by beckermr** [comment]
Right it is more complicated than this due to how the code works. We actually need the exact name of the github repo which may never match the cloned dir even with add "-feedstock". We also cannot compute it from the meta.yaml because the top-level package name can change over time. We'll have to extract the right name from the CI service live, which should be possible and always work.

**Comment by beckermr** [comment]
We can use the following.

 - **circle**: CIRCLE_PROJECT_REPONAME
- **travis**: TRAVIS_REPO_SLUG

I still need to lookup the vars for drone and azure.
