### ISSUE TITLE
Upload with `--private` on anaconda

### ISSUE THREAD

**Issue by hadim** [conda-forge/conda-smithy#1333]
The idea is to be able to specify to upload using a `--private` flag.

Here is an associated issue https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/97 and the associated PR: https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/98

On the `conda-smithy` side, we need to somehow propagate a `private_upload` key in `./ci_support/*.yaml`.

Two questions:

- are you guys ok with this feature?
- does that make sense to add it to `conda-forge.yml`? if it does with what key? and how can I propagate that to `./ci_support/*.yaml`?

As soon as I have your green light I'll make a PR.

**Comment by beckermr** [comment]
Feature seems fine. There is a large dictionary in the configure_feedstock.py file. Add a default of False for the flag for your feature there. Then edit the ci script templates to add the flag if that key is set. 

Note that right now you are doing this by putting the flag in. ci support scripts. It should not be in there.

**Comment by hadim** [comment]
Let's continue there: https://github.com/conda-forge/conda-smithy/pull/1334

**Comment by hadim** [comment]
Fixed by #1334
