### ISSUE TITLE
Should feedstock READMEs mention strict channel priority ?

### ISSUE THREAD

**Issue by phil-blain** [conda-forge/conda-smithy#1348]
Issue: Strict channel priority is mentioned at https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge, but the feedstock READMEs only mention adding the conda-forge channel:

> Installing git from the conda-forge channel can be achieved by adding conda-forge to your channels with:
>
>     conda config --add channels conda-forge

Should 

    conda config --set channel_priority strict

be added  ?

@conda-forge/core

**Comment by phil-blain** [comment]
@conda-forge-admin, please ping core

**Comment by beckermr** [comment]
Sure go for it!
