### ISSUE TITLE
Enabling s390x for conda-forge

### ISSUE THREAD

**Issue by vibhaKulka** [conda-forge/conda-smithy#1359]
Hello,

I am looking forward to add support to build conda packages for s390x (IBM LinuxONE) architecture by conda-forge community.

Travis CI is supported on s390x platform. Below links provides more information.
https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z

This has been verified and jobs can now be scheduled on s390x using https://travis-ci.com/ 

Support for conda, conda-build, constructor for s390x is addressed via issue https://github.com/conda/conda/issues/9791. 

The changes have been approved and merged into the upstream. Please find the PR information below. 
https://github.com/conda/constructor/pull/346
https://github.com/conda/conda-build/pull/3949
https://github.com/conda/conda/pull/9933
https://github.com/conda/conda/pull/10051

I will be happy to understand the requirements of CICD support to build conda, conda-forge feedstocks and other packages as we progress. 
Let us collaborate together and add s390x support. Please feel free to suggest.

Thank you

**Comment by beckermr** [comment]
Thanks for opening this issue! 

Bumping the rest of @conda-forge/core for their thoughts.

**Comment by CJ-Wright** [comment]
I don't see a strong reason not to do this, we've gotten very good at these kinds of rebuilds. Can you tell us more about the user base for this chipset (who uses it, what for, etc.)? Also who is able to support this? We have a dedicated team for handling our existing chipset rebuilds.

**Comment by scopatz** [comment]
I am in favor of this if folks want to put in the effort to have it

**Comment by jakirkham** [comment]
One technical question, we support `ppc64le` on Travis CI as well. Would these "compete" for runtime in the queue? Or are `s390x` builds part of a separate queue from  `ppc64le` builds?

**Comment by chandrureddy** [comment]
First of all thank you so much for your interest and support so far. I really appreciate and looking forward to collaborate more with the community to support s390x platform.

In general they are two different architectures (ppc64le and s390x) so in my opinion ideally they should not unless travis job have such requirements. I will be happy to engage with community and see if we can help here. 

Thank you !

**Comment by chandrureddy** [comment]
@CJ-Wright IBM LinuxONE platform is growing a lot in the past several years in supporting open source based modern workloads, containerized applications and now focusing more into Data and AI space(Via IBM Cloud Paks on Redhat OpenShift Platform)

https://www.ibm.com/in-en/analytics/data-and-ai-on-ibm-z

Lot of traction going on in this area !

**Comment by jakirkham** [comment]
cc @jayfurmanek

**Comment by isuruf** [comment]
I don't see any issues with adding `s390x` support to conda-smithy. For `s390x` support on conda-forge feedstocks, we'll need a set of dedicated people to help out in any issues in supporting `s390x`. This is a big ongoing commitment and needs more than one person.

**Comment by jjhelmus** [comment]
In addition to dedicated people to guide the builds, a Miniforge like installer as well as conda-build and it's dependencies would be needed for the `linux-s390x` platform.  

For `linux-aarch64` a separate channel was used initially as a source of these packages until `conda-forge` had build a sufficient portion of the stack that this was unnecessary.  A similar approach could be done for `s390x`.

**Comment by isuruf** [comment]
Or add support to conda-smithy for cross compiling.

**Comment by chandrureddy** [comment]
@jjhelmus @isuruf we can have a look into both of those options.

**Comment by isuruf** [comment]
conda-smithy already supports s390x because travis does. (That doesn't mean we can build packages yet)

**Comment by isuruf** [comment]
Can you create an issue in `conda-forge/conda-forge.github.io` about building packages?
