### ISSUE TITLE
Improve lint messages on whitespace

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/conda-smithy#136]
The message about the spacing for selectors isn't clear to see the problem in the number of spaces:

```Selectors are suggested to take a " # []" form.```

It would be clearer to have a message like: ```<two spaces> # <one space> [selector]```

**Comment by pelson** [comment]
I agree. I've tried to get some way of rendering it in github appropriately to no avail:

``` "  # []" ```

form doesn't do what is expected, though it looks like

```
  # []
```
does. Trying various attempts:

`  # []`

`&nbsp;&nbsp;#&nbsp;[]`

"&nbsp;&nbsp;#&nbsp;[]"


No matter what, having (``<two spaces>#<one space>[<expression>]``) also helps.

If you are interested in doing it @dopplershift, the line is https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/lint_recipe.py#L75.
