### ISSUE TITLE
Extend support for 'local' conda-forge-ci-setup package handling

### ISSUE THREAD

**Issue by tom--pollard** [conda-forge/conda-smithy#1366]
As it stands, if a feedstock wants to override the default conda installed  `conda-forge-ci-setup` the requirement is to have a local copy of it in the recipe root of a feedstock, to which it is then pip installed.

This has a few obvious issues, including potentially having to have the same package source included in multiple feedstocks, and the pip install circumventing any dependency management. Having a way for this package to be handled remotely could be a nice improvement when manipulating multiple feedstocks with the same setup package.

The handling of local `run_conda_forge_build_setup*` could also be folded into this issue.

**Comment by beckermr** [comment]
PRs welcome but we have to preserve the current behavior too.

**Comment by tom--pollard** [comment]
https://github.com/conda-forge/conda-smithy/pull/1382 was aimed to be part of this, but has been closed due to unintended behaviour

**Comment by tom--pollard** [comment]
https://github.com/conda-forge/conda-smithy/pull/1388 has now merged, providing a way to to install a 'alternate' setup package from a conda channel, allowing for dependencies to be resolved and separation of source

**Comment by beckermr** [comment]
ok great! closing!
