### ISSUE TITLE
Lint: assert certain libraries are pinned

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-smithy#139]
https://github.com/conda-forge/libtiff-feedstock/pull/5 pinned the version of libtiff rather than being promiscuous with supported versions.

According to conda-forge policy (TBD), we can verify that specific common packages are pinned. Whilst this can't be done in general (e.g. numpy), it is rare to not want to pin things like zlib, libtiff etc.

**Comment by jakirkham** [comment]
There are a lot of cases where we need access to the pinnings. Maybe it is worthwhile to just have a package that contains a `json` file with the pinnings. Thoughts?

**Comment by pelson** [comment]
> There are a lot of cases where we need access to the pinnings. Maybe it is worthwhile to just have a package that contains a json file with the pinnings. Thoughts?

Sure. I even think we should have a service which checks they are up to date for us, but I don't really think that belongs in the linter per-se. Perhaps in the linting service on conda-forge-maint, but not as part of the recipe-lint CLI. Fair?

**Comment by croth1** [comment]
Big +1 here. Enabling the linter to check the pinning should make things a lot easier.

**Comment by jakirkham** [comment]
> Perhaps in the linting service on conda-forge-maint, but not as part of the recipe-lint CLI. Fair?

Not sure. Though I think once we better organize how we do pinnings. We will be in good shape for placing that functionality wherever it needs to live.

**Comment by croth1** [comment]
Excuse me for warming this up again. Is there any progress here? Maintaining and updating the pinned dependencies is still a pain point of conda-forge for me.

**Comment by jakirkham** [comment]
I think this should be raised as a topic for issue ( https://github.com/conda-forge/conda-forge.github.io/issues/460 ).

**Comment by jakirkham** [comment]
I think this is no longer needed with conda-build 3. How pinning is handled is not really at all similar to what is discussed here. Pinning is either handled via `run_exports` or `conda-forge-pinning`. Both of which don't require downstream packages to explicitly pin upstream dependencies.
