### ISSUE TITLE
Generate link for license to https://spdx.org/licenses/ 

### ISSUE THREAD

**Issue by jwillemsen** [conda-forge/conda-smithy#1394]
Issue: Generate link for license to https://spdx.org/licenses/

For license SPDX identifiers are used but there are no links generated to https://spdx.org/licenses/. For example for ace (see https://github.com/conda-forge/ace-feedstock) a package license link could be generated in the README.md to https://spdx.org/licenses/DOC and at https://anaconda.org/conda-forge/ace instead of a search http://opensource.org/search/node/DOC a direct link can be generated

**Comment by jwillemsen** [comment]
Related to #1299

**Comment by jakirkham** [comment]
Not sure what is being proposed here. We don't have that much control over what https://anaconda.org/ does. So there's not too much we can do in terms of what links it does or doesn't use.

**Comment by jwillemsen** [comment]
Ok, so anaconda.org is not an option to change, but in the generated README.md which is part of the feedstock a link to the spdx.org license could be generated, so instead of just saying DOC generated a DOC with a link to https://spdx.org/licenses/DOC

**Comment by jwillemsen** [comment]
Ok, sounds this is not just one field with one license, so seems not a real small change

**Comment by jakirkham** [comment]
That's true packages could be under multiple licenses, which would make this tricky.

There is a [`license_url` field in `about`]( https://docs.conda.io/projects/conda-build/en/latest/resources/package-spec.html?highlight=license_url#info-about-json ). The documentation on it is a bit spotty ( https://github.com/conda/conda-build/issues/3712 ), but that could be used. I don't think we make much use of it today. In the few cases we do use it, typically we link to an online copy of the license from the software (perhaps on GitHub).

**Comment by jwillemsen** [comment]
> There is a [`license_url` field in `about`](https://docs.conda.io/projects/conda-build/en/latest/resources/package-spec.html?highlight=license_url#info-about-json). The documentation on it is a bit spotty ( [conda/conda-build#3712](https://github.com/conda/conda-build/issues/3712) ), but that could be used. I don't think we make much use of it today. In the few cases we do use it, typically we link to an online copy of the license from the software (perhaps on GitHub).

See https://github.com/conda-forge/conda-smithy/pull/1397
