### ISSUE TITLE
Add support for manual trigger the rerender workflow through github actions

### ISSUE THREAD

**Issue by jwillemsen** [conda-forge/conda-smithy#1402]
Issue: For some time it is possible manually trigger an action on github action, this could be used for manually trigger a rerender action for a feedstock, this can be done using the `workflow_dispatch` trigger, see https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

**Comment by jwillemsen** [comment]
Looks an easier alternative than install conda-smithy locally to just trigger the rerender, needs some docu additons to https://conda-forge.org/docs/maintainer/updating_pkgs.html when this would be added

**Comment by beckermr** [comment]
all rerenders are manual in any case - see the docs https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-rerender

**Comment by jwillemsen** [comment]
The current rerenders have all to be run as part of an issue or PR, through the actions tab it could be run more easily using the workflow_dispatch, could not require a dummy issue or PR just to trigger a rerender

**Comment by beckermr** [comment]
No this is a bad idea. All changes to feedstocks must happen through PRs on forks. Any branch on the feedstock will be uploaded to anaconda.org. We don't want to upload intermediate releases when ppl are hacking.

**Comment by jwillemsen** [comment]
Ok, see your point, yes, with any branch on the feedstock being uploaded this will not work
