### ISSUE TITLE
noarch suggested to have lower bound on python version - what to do?

### ISSUE THREAD

**Issue by johnomotani** [conda-forge/conda-smithy#1429]
The linter just gave me a suggestion (on the bot-created PR for a new version https://github.com/conda-forge/xbout-feedstock/pull/1):

> For recipe:
>
> noarch: python recipes are recommended to have a lower bound on the python version. This recommendation will become a requirement in the future.

I'd like to follow the suggestion, but it's not obvious to me how to do so. 1) Can anyone help with that? 2) I think it would be nice if the suggestion had a link to some documentation saying what to do.

**Comment by beckermr** [comment]
Use `python >=3.6` instead of `python` in the recipe requirements in both host and run.

**Comment by johnomotani** [comment]
Thanks @beckermr!

**Comment by beckermr** [comment]
+1 closing!
