### ISSUE TITLE
Allow multiple URLs for docs and dev

### ISSUE THREAD

**Issue by BastianZim** [conda-forge/conda-smithy#1432]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
---
Hi,

not sure if this is the right repo to file this is so please shoot me a message in case it's incorrect.

I was wondering if the maintainers wouldn't mind adding something to the infrastructure that converts multiple `doc_urls` in a recipe into a proper list in the _README.md_, the same way Feedstock Maintainers are converted to a list?

Example:

One package I'm maintaining has multiple URLs for the docs (Different languages) and I specified them as following in the meta.yaml:

```yaml
  doc_url:
    - https://mocobeta.github.io/janome/en/
    - https://mocobeta.github.io/janome/
```

See: https://github.com/conda-forge/janome-feedstock/blob/b280b64d3c2f34362866c4bbd0bf96483d13eac6/recipe/meta.yaml#L41

The output is rendered as 

```markdown
Documentation: ['https://mocobeta.github.io/janome/en/', 'https://mocobeta.github.io/janome/']
```
which looks like:

Documentation: ['https://mocobeta.github.io/janome/en/', 'https://mocobeta.github.io/janome/']

but should be rendered as 

```markdown
Documentation:

* https://mocobeta.github.io/janome/en/
* https://mocobeta.github.io/janome/
```
which looks like:

Documentation:

* https://mocobeta.github.io/janome/en/
* https://mocobeta.github.io/janome/
---
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
N.A.
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
N.A.
```
</details>

**Comment by BastianZim** [comment]
I could take a stab at this but I have absolutely no idea where this is done in the code so if someone could give me a pointer to where to look, that would be great, thanks!

**Comment by BastianZim** [comment]
pinging @conda-forge/staged-recipes

**Comment by BastianZim** [comment]
Investigated it a bit, seems like it should be added here:

https://github.com/conda-forge/conda-smithy/blob/1e3c16fdb53c6eaf9eeb2d69b6c019489f96b212/conda_smithy/templates/README.md.tmpl#L21-L24

With a small function to check if there is only one URL and then an if, else block to choose the right format.

Like it's done here (With an added if-else should there only be one doc URL):

https://github.com/conda-forge/conda-smithy/blob/1e3c16fdb53c6eaf9eeb2d69b6c019489f96b212/conda_smithy/templates/README.md.tmpl#L273-L278

But since I'm not sure if that is even wanted by the maintainers, I would only continue investigating this if that's the case?

**Comment by chrisburr** [comment]
Have you checked how this is handled by conda-build and anaconda.org?

**Comment by BastianZim** [comment]
No, not yet. To my understanding that should only affect the README.md and nothing else, is that incorrect?
See: https://github.com/conda-forge/conda-smithy/search?q=doc_url

**Comment by chrisburr** [comment]
I can’t check at the moment but I think `conda index` includes it in the channel metadata

**Comment by BastianZim** [comment]
To be honest, that, I don't know. anaconda.org doesn't list anything but it is included in the _about.json_ so that could prohibit it, you're right.

**Comment by BastianZim** [comment]
Edit: Anaconda does list the URLs for some packages. Closing due to incompatibility.

**Comment by chrisburr** [comment]
They also find their way onto this page https://conda-static.anaconda.org/conda-forge/ which is generated by `conda index`. You'll also have a local copy in `$CONDA_PREFIX/conda-bld/index.html` for packages you've built locally.

I'd suggest building a package locally and uploading it to a personal channel on anaconda.org to see what happens, it might evem work already. If it does then this PR is a very welcome addition, if not you can always look in `conda-build` to see how practical it is to add.

(I'm sorry to be negative, it's a good idea that I've occasionally wanted as well.)

**Comment by BastianZim** [comment]
That sounds like a good idea, thanks for the suggestion, then I'll try that out!
I'm on holiday now though so I'll only be able to try it in Jan probably. 😄 

> (I'm sorry to be negative, it's a good idea that I've occasionally wanted as well.)

No worries totally understood and thanks for your help!

Also, just to add: I tried it in a package and the linter didn't complain so it might be good to add this there until I can verify that it's not causing any problems.

**Comment by BastianZim** [comment]
Seems to be impossible at the current stage.

**Comment by BastianZim** [comment]
Will re-open this once conda/Anaconda supports this.

**Comment by jakirkham** [comment]
See issue ( https://github.com/conda/conda/issues/10504 ), which is requesting this functionality
