### ISSUE TITLE
Optionally use `mambabuild`

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/conda-smithy#1440]
`conda` error messages are all but uninterpretable. The default advice is to manually try the install command with `mamba` which usually gives much better error messages.

It would be good to have an option to use `conda mambabuild` to short-circuit this process so users can get actionable error messages by default.

From gitter: https://gitter.im/conda-forge/conda-forge.github.io?at=6004a99299549911fc2ace33

**Comment by dhirschfeld** [comment]
@beckermr raised some potential issues which might need to be resolved first:
* https://github.com/mamba-org/boa/issues/110
* https://github.com/mamba-org/boa/issues/100
* https://github.com/mamba-org/boa/issues/102

**Comment by wolfv** [comment]
I fixed 110 and 102, but 100 is more difficult. 

I am willing to look into this _only if_ we want to actually produce builds using `conda mambabuild`.
If we only want `mambabuild` as a debug option then I'd like to skip that one for now.

**Comment by beckermr** [comment]
We can force smithy to disable uploads with mambabuild for now.
