### ISSUE TITLE
docker_image: cos7-cuda:10.2 chosen over cos7-x86_64 for os_version: { linux_64: cos7 }

### ISSUE THREAD

**Issue by mbargull** [conda-forge/conda-smithy#1459]
Re-rendered with conda-build 3.21.4, conda-smithy 3.9.0, and conda-forge-pinning 2021.03.02.12.06.47

If
```yaml
os_version:
  linux_64: cos7
```
is used in `conda-forge.yml`, re-rendering causes the `docker_image` key to get value `quay.io/condaforge/linux-anvil-cos7-cuda:10.2` rather than `quay.io/condaforge/linux-anvil-cos7-x86_64` even for non-CUDA recipes.

AFAICT, https://github.com/conda-forge/conda-smithy/blob/v3.9.0/conda_smithy/configure_feedstock.py#L197 sorts the configuration values which puts `...-cos7-cuda:10-2` before `..-cos7-x86_64` (since `"c" < "x"`, lexicographically). But https://github.com/conda-forge/conda-smithy/blob/v3.9.0/conda_smithy/configure_feedstock.py#L386 chooses the first value, which is likely supposed to be the first one from the original (`conda-forge-pinnings`') order, not from the sort-order.
Just omitting the sort would not work either since `conda-build`'s output is not deterministic and can either have `*-cos7-x86_64` or `*-cos7-cuda:10.2` as the first entry.

It's quite possible my assessment above isn't 100 % correct, but it should be enough to help fix it by someone who's more versed in the code base.

**Comment by beckermr** [comment]
cc @isuruf 

I think we might need to specify the sort order explicitly somehow?

**Comment by isuruf** [comment]
> I think we might need to specify the sort order explicitly somehow?

No, we should preserve the original order instead of sorting.

**Comment by beckermr** [comment]
I don't follow what you are saying. Can explain a bit more? 

In particular, this comment from @mbargull 

> Just omitting the sort would not work either since conda-build's output is not deterministic and can either have *-cos7-x86_64 or *-cos7-cuda:10.2 as the first entry.

seems to indicate that we have to keep the sorting in smithy. 

I don't see how to square those statements.

**Comment by isuruf** [comment]
conda-build's output is not deterministic, but we can sort the variants using the original order that they came from where `*-cos7-x86_64` comes first.

**Comment by beckermr** [comment]
Ah ok. So what I said above then.

**Comment by mbargull** [comment]
I just ran into a similar thing at https://github.com/conda-forge/python-feedstock/pull/656#discussion_r1428500644 .
@beckermr suggested to try out setting `PYTHONHASHSEED` to get a reproducer -- and I got lucky to quickly get one to pin down the current issue:
We get a different order of variants in
https://github.com/conda-forge/conda-smithy/blob/v3.30.1/conda_smithy/configure_feedstock.py#L350
in comparison to the one we get from
https://github.com/conda-forge/conda-smithy/blob/v3.30.1/conda_smithy/configure_feedstock.py#L345
which we later overwrite in
https://github.com/conda-forge/conda-smithy/blob/v3.30.1/conda_smithy/configure_feedstock.py#L394 .
As in, we get something like
```python
squished_input_variants = {..., 'channel_targets': ('conda-forge main', 'conda-forge python_debug'), 'build_type': ('release', 'debug'), ...}
squished_used_variants = {..., 'channel_targets': ('conda-forge python_debug', 'conda-forge main'), 'build_type': ('debug', 'release'), ...}
```
in the `python-feedstock` case.
This would probably all be fine, but later in
https://github.com/conda-forge/conda-smithy/blob/v3.30.1/conda_smithy/configure_feedstock.py#L397
we only partially overwrite some keys with the values order taken from `squished_input_variants` again.
For `python-feedstock` we have only `build_type` in `preserved_top_level_loops` but not `channel_targets` which then leads to mismatched `zip_keys` entries.

**Comment by mbargull** [comment]
It could be that the assumption from
https://github.com/conda-forge/conda-smithy/blob/v3.30.1/conda_smithy/configure_feedstock.py#L354-L355
fails because we add `top_level_vars` later in
https://github.com/conda-forge/conda-smithy/blob/v3.30.1/conda_smithy/configure_feedstock.py#L384
.
Meaning, possibly we only have to move the `preserve_top_level_loops` assignment after `all_used_vars` is completely populated, i.e., right before it gets used for `used_key_values` in
https://github.com/conda-forge/conda-smithy/blob/v3.30.1/conda_smithy/configure_feedstock.py#L386
onward.

**Comment by mbargull** [comment]
> It could be that the assumption from https://github.com/conda-forge/conda-smithy/blob/v3.30.1/conda_smithy/configure_feedstock.py#L354-L355 fails because we add `top_level_vars` later in https://github.com/conda-forge/conda-smithy/blob/v3.30.1/conda_smithy/configure_feedstock.py#L384 . Meaning, possibly we only have to move the `preserve_top_level_loops` assignment after `all_used_vars` is completely populated, i.e., right before it gets used for `used_key_values` in https://github.com/conda-forge/conda-smithy/blob/v3.30.1/conda_smithy/configure_feedstock.py#L386 onward.

This seems to do the trick indeed and is implemented in gh-1815.
