### ISSUE TITLE
Broken OSX uploads from Azure-Pipelines

### ISSUE THREAD

**Issue by mrakitin** [conda-forge/conda-smithy#1476]
Uploads of built artifacts for OSX seem to be broken. I encountered it with `nsls2forge` feedstocks (see e.g., https://dev.azure.com/nsls2forge/nsls2forge/_build/results?buildId=8278&view=results), but I just checked a conda-forge feedstock, and it seems there is a problem there too: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=309175&view=results.

Looks like it's related to the recently released version 3.10.1.

**Comment by beckermr** [comment]
See the chat on gitter and this PR: https://github.com/conda-forge/anaconda-client-feedstock/pull/27

this issue should fix itself in roughly an hour or so.

**Comment by beckermr** [comment]
I'm going to close this for now. Feel free to reopen if you are still seeing issues after waiting! Thank you!

**Comment by mrakitin** [comment]
Thanks, @beckermr! I am running a new job in https://dev.azure.com/nsls2forge/nsls2forge/_build/results?buildId=8285&view=logs&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00 to see if the fix is applied. I do see the new build is used there:
```
  anaconda-client    conda-forge/noarch::anaconda-client-1.7.2-pyhd8ed1ab_1
```

**Comment by mrakitin** [comment]
Thanks for the quick fix, @beckermr! The uploads are happening now:
![image](https://user-images.githubusercontent.com/13209176/116117905-c2dea180-a68a-11eb-8f1f-c38a6b91f6d0.png)
