### ISSUE TITLE
Linter incorrectly complains about build number

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#148]
Seems the linter is giving false positives in some cases with regards to `build/number`. See this [issue]( https://github.com/conda-forge/eigen-feedstock/issues/8 ) and [comment below]( https://github.com/conda-forge/eigen-feedstock/issues/8#issuecomment-215510123 ) for an example of this behavior. Another example can be seen in this [issue]( https://github.com/conda-forge/pandoc-feedstock/issues/7 ).

**Comment by jakirkham** [comment]
Here is another [example]( https://github.com/conda-forge/primesieve-feedstock/pull/3#issuecomment-215866998 ).

**Comment by pelson** [comment]
The problem was with the script, not the linter. I have submitted the script at https://github.com/conda-forge/conda-forge.github.io/pull/132 with this issue solved.
