### ISSUE TITLE
Cannot run build_locally.py again without removing miniforge3

### ISSUE THREAD

**Issue by ihnorton** [conda-forge/conda-smithy#1493]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: Cannot run build_locally.py again without removing miniforge3

<br/>
Environment (<code>conda list</code>):

<details>

```
conda                     4.10.1           py39h6e9494a_0    conda-forge
conda-build               3.21.4           py39h6e9494a_0    conda-forge
conda-forge-pinning       2021.06.24.13.08.40      hd8ed1ab_0    conda-forge
conda-package-handling    1.7.3            py39h89e85a6_0    conda-forge
conda-smithy              3.10.3             pyhd8ed1ab_0    conda-forge
...snip...
```

</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

---

Details:

I cannot run `./build-locally.py` more than once on macOS without deleting the miniforge3 folder created in the process of executing that script. After a single execution, subsequent runs of `./build-locally.py` fail with:

```
Installing a fresh version of Miniforge
+ MINIFORGE_URL=https://github.com/conda-forge/miniforge/releases/latest/download
+ MINIFORGE_FILE=Miniforge3-MacOSX-x86_64.sh
+ curl -L -O https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-x86_64.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   161  100   161    0     0   1045      0 --:--:-- --:--:-- --:--:--  1052
100   635  100   635    0     0   2533      0 --:--:-- --:--:-- --:--:--  2533
100 40.5M  100 40.5M    0     0  5495k      0  0:00:07  0:00:07 --:--:-- 6632k
+ bash Miniforge3-MacOSX-x86_64.sh -b -p /Users/inorton/work/git/tiledb-py-feedstock/./miniforge3
ERROR: File or directory already exists: '/Users/inorton/work/git/tiledb-py-feedstock/./miniforge3'
If you want to update an existing installation, use the -u option.
Traceback (most recent call last):
  File "/Users/inorton/work/git/tiledb-py-feedstock/./build-locally.py", line 96, in <module>
    main()
  File "/Users/inorton/work/git/tiledb-py-feedstock/./build-locally.py", line 92, in main
    run_osx_build(ns)
  File "/Users/inorton/work/git/tiledb-py-feedstock/./build-locally.py", line 33, in run_osx_build
    subprocess.check_call([script])
  File "/cmn/condaenvs/tiledb-release/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.scripts/run_osx_build.sh']' returned non-zero exit status 1.
```

Re-downloading/installing miniforge [happens here](https://github.com/conda-forge/conda-smithy/blob/330859340ffddfede55f458785cd1ba038ecdd4c/conda_smithy/templates/run_osx_build.sh.tmpl#L9-L16) in the template code, but based on [gitter discussion](https://gitter.im/conda-forge/conda-forge.github.io?at=60d4b6a5effd491d8c81b68e) it is unclear what is the overall expected behavior.

**Comment by isuruf** [comment]
I think we should just delete in the template code first.

**Comment by ihnorton** [comment]
Wouldn't that mean the (isolated?) miniforge env is never initialized?

**Comment by ihnorton** [comment]
Oh you mean delete `MINIFORGE_HOME` before running again?

**Comment by isuruf** [comment]
> Oh you mean delete MINIFORGE_HOME before proceeding inside run_osx_build.sh?

Yes. I mean this.

**Comment by isuruf** [comment]
Maybe delete at https://github.com/conda-forge/conda-smithy/blob/7823676f5632f7999cd16f7806b954a4c649dcdf/conda_smithy/feedstock_content/build-locally.py#L21
