### ISSUE TITLE
Fix AppVeyor badge URL

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#150]
Fix the AppVeyor badge URL as was done for the other AppVeyor URL here ( https://github.com/conda-forge/conda-smithy/pull/116 ). In particular, convert `_` to `-` in the feedstock name.

**Comment by whart222** [comment]
I dealt with a similar issue here: conda-forge/pyomo.extras-feedstock/pull/3

The pyomo.extras package has a period in its name, which needs to be propagated into the AppVeyor badge URL.

**Comment by jakirkham** [comment]
So, I think we fixed both of these issues in this PR ( https://github.com/conda-forge/conda-smithy/pull/159 ). See this [line]( https://github.com/conda-forge/conda-smithy/pull/159/files#diff-761fe9ab7b458354bfa62ed0268e948dR72 ). @pelson, any idea why @whart222 is still seeing this?

**Comment by pelson** [comment]
The image URL appears to maintain the period ``.``, but the link does not.

**Comment by pelson** [comment]
https://github.com/conda-forge/pyomo.extras-feedstock/pull/3/files

**Comment by jakirkham** [comment]
Ah, looking closely at the view of the README made @whart222's problem clear. The badge icon doesn't show up.

**Comment by pelson** [comment]
Closed by #195. This will either be in v0.10.5, or v1.0, depending which comes first.
