### ISSUE TITLE
Support for isolated osx builds

### ISSUE THREAD

**Issue by 183amir** [conda-forge/conda-smithy#1518]
Some feedstocks like https://github.com/conda-forge/tensorflow-feedstock take a long time to build.
I have spent some time building these packages in Bob's CI (where the CI can run for an unlimited time) in https://gitlab.idiap.ch/bob/conda/-/commits/conda-forge-tensorflow-feedstock but unfortunately the osx scripts assume that the CI machine can be freely modified.
In our CI, we use physical macos machines and the builds don't run in an isolated OS.
So, commands like modifying the any folder but the project folder, or using sudo should be avoided.
I was wondering how difficult would it be to modify conda-smithy or add an option here to generate CI scripts that would not modify the host machine.

**Comment by isuruf** [comment]
Can you send a PR for https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/master/recipe/conda_forge_ci_setup/build_utils.py#L91 ?

**Comment by 183amir** [comment]
Thank you for your help. The builds are working now.
