### ISSUE TITLE
Azure: Windows-2016 environment will be removed on March 15, 2022

### ISSUE THREAD

**Issue by mbargull** [conda-forge/conda-smithy#1536]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

See https://github.com/actions/virtual-environments/issues/4312 :
> ### Breaking changes
> 
> Windows 2016 hosted runners will be removed from GitHub actions and Azure DevOps. To raise awareness of the upcoming removal, we will temporarily fail jobs using Windows 2016 for two short 'brownout' periods. Builds that are scheduled to run during the brownout periods will fail. The brownouts are scheduled for the following dates and times:
> 
>     * December 1, 2021 4:00pm UTC – 10:00pm UTC
> 
>     * February 7, 2022 4:00pm UTC – 10:00pm UTC
> 
> 
> ### Target date
> 
> March 15, 2022
> ### The motivation for the changes
> 
> Windows Server 2016 Active support ends on 11 Jan 2022 and Windows Server 2022 VM image is going out of beta later this year. As part of our ongoing efforts to keep GitHub and Azure Devops hosted runners updated and secure, the Windows 2016 virtual environment will be removed from GitHub Actions and Azure DevOps.
> ### Possible impact
> 
> If your project depends on Windows 2016 environment and visual studio 2017 it can be broken.
> ### Virtual environments affected
> 
>     * [ ]  Ubuntu 16.04
> 
>     * [ ]  Ubuntu 18.04
> 
>     * [ ]  Ubuntu 20.04
> 
>     * [ ]  macOS 10.15
> 
>     * [ ]  macOS 11
> 
>     * [x]  Windows Server 2016
> 
>     * [ ]  Windows Server 2019
> 
>     * [ ]  Windows Server 2022
> 
> 
> ### Mitigation ways
> 
> We recommend you change jobs using `runs-on: windows-2016` to use `runs-on: windows-latest` which will ensure you're always running on the latest version of Windows Server.
> 
> If you need to pin your job to a specific version of Windows Server, you can see the full list of supported versions here https://github.com/actions/virtual-environments#available-environments

**Comment by jakirkham** [comment]
More discussion in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/1538 )

**Comment by mbargull** [comment]
Thanks for the ref John! Let's keep both open for now for visibility and continue discussion at the other issue.

**Comment by jaimergp** [comment]
Closed by https://github.com/conda-forge/conda-smithy/pull/1552 and https://github.com/conda-forge/staged-recipes/pull/17236
