### ISSUE TITLE
Remove recipe conda build config before building

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-smithy#1551]
Smithy processes the recipe conda build config with the global pinnings to produce ci support files that contain the config used for the build. However, when conda build is called, it still uses the contents in the recipe conda build config as far as I know. 

I may be wrong about this, but if I am not, maybe we should simply delete the recipe conda build config files before running the build?

**Comment by isuruf** [comment]
You implemented it. See https://github.com/conda-forge/conda-smithy/blob/main/conda_smithy/configure_feedstock.py#L640-L669

**Comment by isuruf** [comment]
Ah, you mean running the build

**Comment by isuruf** [comment]
Recipe cbc gets lower priority than `.ci_support` files.

**Comment by beckermr** [comment]
Right it gets lower priority but it still gets applied. I am seeing cases for mpi where somehow pin run as build for the mpi pins is not in the ci support files but remains in the conda build config. This isn't the solution for the mpi stuff. (I made separate prs.)

However, I do think we should be doing this at build time to make the final config easier to interpret and understand how it translates into values.

**Comment by isuruf** [comment]
Sometimes, conda-build doesn't think some pins are used in the build so they don't end up in .ci_support files. Doing what you are suggesting will break a number of packages.

**Comment by beckermr** [comment]
Ahhhhh. Ok so we are patching around a conda build bug of some sort. That's good to know. Thanks for the help! Closing!
