### ISSUE TITLE
Is `app` a valid outputs key or not?

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/conda-smithy#1557]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I have added an `app` section to one of the outputs in a multi-output recipe. The linter says is not a valid key, but `conda-build` does accept it. Is this an oversight or a deliberate choice?

* PR: https://github.com/conda-forge/napari-feedstock/pull/32
* Recipe: https://github.com/conda-forge/napari-feedstock/blob/846d5007a2c1a82c78f0948a628fd41355e77387/recipe/meta.yaml
* Error: https://github.com/conda-forge/napari-feedstock/pull/32#issuecomment-999495016

**Comment by isuruf** [comment]
We use the valid keys from https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L447-L462. Please open an issue in conda-build to fix this.
