### ISSUE TITLE
conda smithy does not keep the channel_sources order from conda_build_config.yaml

### ISSUE THREAD

**Issue by easz** [conda-forge/conda-smithy#1565]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I try to define `recipe/conda_build_config.yaml` in a feedstock with
~~~
channel_sources:
  - pytorch
  - conda-forge
  - defaults
~~~

After runnung `conda smithy rerender` the new generated `.ci_support/linux_64_python3.7.____cpython.yaml` has 
~~~
channel_sources:
- conda-forge
- defaults
- pytorch
~~~

The order is not kept. Is it intended?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

"MNT: Re-rendered with conda-build 3.21.7, conda-smithy 3.16.1, and conda-forge-pinning 2022.01.17.15.36.21"

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by isuruf** [comment]
See https://github.com/conda-forge/conda-smithy#making-a-new-feedstock on how to properly specify it

**Comment by easz** [comment]
I see..

I should define
~~~
channel_sources:
  - mysourcechannel1,mysourcechannel2,conda-forge,defaults
~~~

instead of
~~~
channel_sources:
  - mysourcechannel1
  - mysourcechannel2
  - conda-forge
  - defaults
~~~
in recipe/conda_build_config.yaml
