### ISSUE TITLE
Lint of `entry_points` in `outputs`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#1598]
When adding `entry_points` to a subpackage in `outputs`, the linter raises the following ( https://github.com/conda-forge/dask-feedstock/pull/172#issuecomment-1051392948 ):

> The outputs section contained an unexpected subsection name. entry_points is not a valid subsection name.

However this usage seems to be [covered by conda-build's own tests]( https://github.com/conda/conda-build/blob/3b99b2222a067e113a2282926871cd1e5406ee2b/tests/test-recipes/split-packages/_entry_points/meta.yaml#L19-L22 ). Additionally the recipe builds without errors using that field.

**Comment by jakirkham** [comment]
Think we are [just checking against conda-build's `FIELDS`]( https://github.com/conda-forge/conda-smithy/blob/695e549a2c580e876b41cd527319d8afab2260d4/conda_smithy/lint_recipe.py#L22 ). So this needs to fixed in conda-build. Submitted PR ( https://github.com/conda/conda-build/pull/4389 ).

**Comment by isuruf** [comment]
This is a conda-build bug tracked in https://github.com/conda/conda-build/pull/4389
