### ISSUE TITLE
`conda-grayskull` should post a link to the GHA workflow

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/conda-smithy#1608]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

`conda-grayskull` seemed to fail here:
https://github.com/conda-forge/equinox-feedstock/pull/1#issuecomment-1068423665

![image](https://user-images.githubusercontent.com/881019/158485428-216b8087-fb98-44cf-8408-090698ca0b34.png)

It's good that the user gets some feedback that something is happening, but if things go wrong there no way to debug.

On other services I've noted links to the GHA workflow are posted so that a user can click to investigate progress or problems. It might be useful if `conda-graskull` did the same (assuming it's implemented using GHA?)

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by jakirkham** [comment]
cc @conda-forge/bot

**Comment by beckermr** [comment]
That tool is not maintained by the bot team or in conda-smithy. 

Please contact Marcelo. 

This issue should be closed.

**Comment by dhirschfeld** [comment]
I'll check with @marcelotrevisani where I should open this issue...
