### ISSUE TITLE
Lint `conda-forge.yml`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#1616]
Sometimes issues in `conda-forge.yml` can crop up. It would be useful in these cases to have a way to lint `conda-forge.yml` and share this feedback with users in PRs before that content makes into `main`.

**Comment by bollwyvl** [comment]
Driving it with no-fooling JSON schema, and encouraging referring to it directly in the file via `$schema`, would be pretty excellent, as people's editors would then give them nice autocompletion and diagnostics from e.g. https://github.com/redhat-developer/yaml-language-server

**Comment by jaimergp** [comment]
Closed by #1756
