### ISSUE TITLE
exploration of adding cache to accelerate difficult builds

### ISSUE THREAD

**Issue by ngam** [conda-forge/conda-smithy#1625]
### Comment:

https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops

**Comment by ngam** [comment]
Not sure if there is a way to share caches between runs though :(

**Comment by jakirkham** [comment]
Yeah this sort of thing has come up before. Might be instructive to read past issues around this. In particular looking for `ccache` will surface a few things

The main points that come up:
1. Storage limits
2. Security
3. Cleaning schedule (by providers & self-imposed)
4. Portability (not a blocker, but not all CIs provide this)
5. Tooling changes

**Comment by ngam** [comment]
Thanks @jakirkham, I am going to try a few things. Maybe the first thing is a bazel remote/gcp cache for the tensorflow builds. If that works and makes the build run under 6 hours, then we can start thinking about it a little more seriously as a system-wide solution. Btw, did you see my PR regarding adding support for singularity here — I followed your pointer! :)

**Comment by ngam** [comment]
(Another tempting, but wild, idea is caching the entire build process as a docker image... essentially building the package but also building an associated docker image with it and caching that, that way it may even be more productive because the entire thing gets cached and split into OCIs, etc. --- anyway, just thoughts for now...)

**Comment by ngam** [comment]
@jakirkham do you see any immediate red flags in simply adding one task in the azure configs to trigger a cache? It would be isolated based on branch, repo, and run type. 

Re below, 
- storage: infinite
- security: unsure what exactly this means, we run stuff in the open anyway, or maybe you mean caching tokens, etc.? We can set up a token to access the cache too...
- cleaning: after 7 days of inactivity
- portability: dead-end (assume zero portability)
- tooling changes: moot if cache is cleaned so regularly (e.g. 7 days intervals)

> The main points that come up:
> 
> 1. Storage limits
> 2. Security
> 3. Cleaning schedule (by providers & self-imposed)
> 4. Portability (not a blocker, but not all CIs provide this)
> 5. Tooling changes

**Comment by ngam** [comment]
I am gonna close this as it is something I won't be able to rigorously pursue anytime soon. Will likely revisit later.
