### ISSUE TITLE
Authenticated Anaconda channel_sources?

### ISSUE THREAD

**Issue by ssnseawolf** [conda-forge/conda-smithy#1626]
Is there a way to have smithy pull from an authenticated Anaconda channel source?

It doesn't seem to respect `BINSTAR_TOKEN` in Azure CI for sources, only for targets. This may be unsupported as smithy is mainly for public sources, however being able to pull from authenticated Anaconda sources would be advantageous when using smithy outside of conda-forge.

I can't dig up any documentation that mentions this scenario, unfortunately.

**Comment by hmaarrfk** [comment]
I think you can add your token. In the channel name. Is that acceptable?

**Comment by ssnseawolf** [comment]
Thanks, you pointed me in the direction I needed to go.

For those running up against this in the future:
* [Anaconda Enterprise tokens API](https://docs.anaconda.com/anaconda-repository/user-guide/tasks/work-with-organizations/#repo-creating-orgs).
* If you're testing an authenticated URL, the arch is required, i.e.:
    - Doesn't show authenticated packages: https://conda.anaconda.org//t/<token>/<username_or_org>
    - Shows authenticated packages: https://conda.anaconda.org//t/<token>/<username_or_org>/linux-64

**Comment by ssnseawolf** [comment]
Thanks, you pointed me in the direction I needed to go.

### For those running up against this in the future

* Docs for [Anaconda Enterprise tokens API](https://docs.anaconda.com/anaconda-repository/user-guide/tasks/work-with-organizations/#repo-creating-orgs).
* If we test an authenticated URL the arch is required (unlike for unauthenticated URLs), i.e.:
    - Doesn't show authenticated packages: https://conda.anaconda.org/t/<token>/<username_or_org>
    - Shows authenticated packages: https://conda.anaconda.org/t/<token>/<username_or_org>/linux-64
* `channel_sources` allows properly formatted URLs
* `channel_sources` allows smithy variables such as BINSTAR_TOKEN
* `channel_sources` URLs must not contain an arch. They are formatted like: https://conda.anaconda.org/t/<token>/<username_or_org>

Putting it all together, we find that a proper `conda_build_config.yaml` for authenticated Anaconda repos has a `channel_sources` section resembling:

```
channel_sources:
  - https://conda.anaconda.org/t/$BINSTAR_TOKEN/<username_or_org>,conda-forge,defaults
```
### Note that
* This assumes our source and target channels are the same. We likely can change the variable to another token, i.e. `$SOURCE_TOKEN` if they are different (untested).
* We must define `BINSTAR_TOKEN` in Azure either as a secret variable or as a library secret, per usual
* Azure obfuscates our secret `BINSTAR_TOKEN` in the logs with `***`, but substitutes it correctly at runtime
