### ISSUE TITLE
Tests run on emulated builds when `test: native` is selected

### ISSUE THREAD

**Issue by carterbox** [conda-forge/conda-smithy#1640]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

https://github.com/conda-forge/astra-toolbox-feedstock/pull/6

In this PR, I have selected to run tests on native builds only by adding `test: native` to the config. However, tests are running on azure emulated builds anyways. They should only run if I I set `test: native_and_emulated`. In the logs, it looks like "--no-test" is not being passed to mambabuild as an argument.

### Installed packages

```shell
conda-build 3.21.9, conda-smithy 3.21.0, and conda-forge-pinning 2022.06.27.18.30.08
```

### Environment info

```shell
Azure ppc64le and arm linux emulated containers.
```

**Comment by isuruf** [comment]
Using azure for ppc64le means the whole OS is emulated and within the docker script, it acts as if it is native.
From `test: native_and_emulated` means native (either bare metal or full OS emulation) or emulation (cross-compile, but there's an emulator to run tests)

**Comment by carterbox** [comment]
🤦🏼 But the whole OS emulation doesn't behave the same as native on Travis where tests do pass (if the build doesn't crash/timeout), so I should just skip tests on a platform basis?

**Comment by isuruf** [comment]
In that case, skip the tests based on `# [CI='azure']` or move to cross compiling and then the tests will be skipped automatically.

**Comment by carterbox** [comment]
Thanks!
