### ISSUE TITLE
Add conda-smithy version to conda-forge.yml

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#168]
Just as the title says, we should add the `conda-smithy` version to `conda-forge.yml` so that we can tell what version we re-rendered (or rendered) with.

**Comment by pelson** [comment]
> Just as the title says, we should add the conda-smithy version to conda-forge.yml so that we can tell what version we re-rendered (or rendered) with.

I did think about this before, but then discarded it because it could very well be the only thing that changes between versions. Essentially, doing this would guarantee that *every* new version requires *every* feedstock to be updated - I'm not sure we need to impose that requirement.

I have been thinking about having a webservice which double checks the state of ```rerendering``` much like we do with linting. Maybe that would alleviate the concern about feedstocks getting out of date?

**Comment by jakirkham** [comment]
> ...it could very well be the only thing that changes between versions.

Good point. Maybe there is someway we can workaround this.

> I have been thinking about having a webservice which double checks the state of `rerendering` much like we do with linting.

Interestingly, I was thinking about this to make the load on such a service less.

**Comment by jakirkham** [comment]
Adding you here, @kwilcox, as this point came up again in this PR ( https://github.com/conda-forge/kombu-feedstock/pull/2 ).

**Comment by kwilcox** [comment]
Could we add another attribute to the yml to specify if the version requires a feedstock update?

**Comment by jakirkham** [comment]
What if we versioned renderings themselves? We would have to think about how granular we want to get with versions and how we want handle different combinations of CIs and NumPy `x.x` usage. In any event, we should be able to come up with fewer unneeded re-renderings.

**Comment by jakirkham** [comment]
I think PR ( https://github.com/conda-forge/conda-smithy/pull/307 ) was right on the money 💰. What we should be doing is standardizing our commits whether we re-render or the bot re-renders to make it easier to see what version we re-rendered with last. After all everything outside of the recipe directory should only be changed by re-renderings.

Beyond that, other tricks like git pre-commit hooks, automated re-rendering PR ( https://github.com/conda-forge/conda-forge-webservices/issues/74 ), and so on can be used make this a trivial nearly mindless background operation.

**Comment by pelson** [comment]
I think we can close this one out - it is conceivable to have a version string in the feedstock that is only updated when we re-render and **something other than the version** number has changed. For now though - I don't think we need to keep this one open - the commit convention gives feedstock users a reasonably good clue.
