### ISSUE TITLE
Advise: Add ability to run different templates (and more secure variables)?

### ISSUE THREAD

**Issue by janschulz** [conda-forge/conda-smithy#169]
The goal is to use the infrastructure/codebase of the conda-smithy for building wheels.

My current idea is basically 

* Add conda dependencies to the config file (manual step)
* add `twine`/PyPI user and pw as secure variables to the config file (by a smithy command)
* add a template which basically setups conda, creates a new env from the dependencies, actives the env, builds the wheels in that env and upload it via twine. Or only calls a batch file/shell script which does all this...

Most of this is already in the smithy, AFAIK there are two steps which would need to be generalized: 

* instead of the anaconda token, it would encrypt the pypi password -> would need something in conda-forge.yml which would trigger encrypting a different token, eg. `upload_token: "pypi"` and of that is not set would default to anaconda token
* there would need to be a way to change the templates.

So, would you take a patch which does this? Or is it best to simple fork the smithy, rework it and publish it under a different name?

**Comment by janschulz** [comment]
If you want to see my current evil workaround: wheel uploads in a conda recipe which is build by a staged-recipe-like repo  :-)

https://github.com/janschulz/package-builder/tree/master/recipes/pypandoc

**Comment by janschulz** [comment]
I looked a bit more into this and it seems that most is pretty specific to conda-forge. The only thing I found was the CI registering, which would only need a single tweak to three functions to make it more generic:

each `add_token_to_xxx` and `travis_token_update_conda_forge_config` would need to be made more general: `add_token_to_xxx(user, project, token_name, token_content) ([source](https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/ci_register.py#L32)) and this would then be called from the [register_CI](https://github.com/conda-forge/conda-smithy/blob/6c1856a51832b5a014bb9126467804d75d712029/conda_smithy/cli.py#L159) with the apprpriate token names and content.

That way I could simply import these functions...

@pelson would you be willing to take such a patch?

**Comment by pelson** [comment]
Definitely supportive of reusing the registration functions outside of conda-forge. As you observed, I think managing the templates is probably more challenging. Go ahead and submit a (small :wink:) PR which exposes those functions in a way that is helpful to you, and we can talk about it properly.

**Comment by jakirkham** [comment]
Is this resolved or is there something that still needs to be done here?

**Comment by janschulz** [comment]
I'm currently not working on this, so: close...
