### ISSUE TITLE
Release 3.23.1?

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-smithy#1725]
### Comment:

I merged https://github.com/conda-forge/conda-smithy/pull/1724 due to a typo that caused windows builds to fail strangely.

Any objections to a release 3.23.1?

I can try to make one with rever.

**Comment by timsnyder** [comment]
I'm also running into this on https://github.com/conda-forge/verilator-feedstock/pull/40

**Comment by jakirkham** [comment]
No objection from me. Here's [the diff]( https://github.com/conda-forge/conda-smithy/compare/v3.23.0...main )

Thoughts @conda-forge/core?

**Comment by beckermr** [comment]
go for it!

**Comment by timsnyder** [comment]
@hmaarrfk it would be awesome if you could push a release. There was [another post in the gitter channel ](https://matrix.to/#/!SOyumkgPRWoXfQYIFH:matrix.org/$167899709439ycsrP:gitter.im?via=matrix.org&via=gitter.im&via=cadair.com)asking about the azure artifacts on windows a few days ago.

**Comment by hmaarrfk** [comment]
it might have to wait till this weekend till I get enough mental space to learn the release process here. it is new to me..

**Comment by beckermr** [comment]
Let me try it tonight. Sorry for the delay.

**Comment by beckermr** [comment]
Done! Should hit the index in the next hour or so. https://github.com/conda-forge/conda-smithy-feedstock/pull/249

**Comment by jakirkham** [comment]
Thanks Matt! 🙏
