### ISSUE TITLE
Pin patchelf at 0.17.2 for now to avoid corrupting DSOs?

### ISSUE THREAD

**Issue by leofang** [conda-forge/conda-smithy#1737]
The latest patchelf 0.18.0 seems to cause the alignment bug (https://github.com/NixOS/patchelf/issues/492) that impacted some packages (https://github.com/conda/conda-build/issues/4881, https://github.com/conda-forge/cuda-cudart-feedstock/pull/10, https://github.com/conda-forge/cuda-cudart-feedstock/pull/11) Instead of setting `binary_relocation: False` in each feedstock, perhaps it's better to pin it globally for the time being?

cc: @isuruf (thx for reporting https://github.com/NixOS/patchelf/issues/492#issuecomment-1561316697) @jakirkham

**Comment by jakirkham** [comment]
Wonder if [setting `remote_ci_setup` in `conda-forge.yml`]( https://conda-forge.org/docs/maintainer/conda_forge_yml.html#remote-ci-setup ) could be an option

This is something we used to [workaround LIEF issues before]( https://github.com/conda-forge/conda-smithy/pull/1684 )

**Comment by leofang** [comment]
Yes that's what I thought too. I had that PR in mind.

**Comment by jakirkham** [comment]
Tried `remote_ci_setup`, but it alters Windows too, which is not viable in this case since `patchelf` is only available on Linux

Given the amount of trouble `patchelf` version `0.18.0` has caused, suggesting just marking it broken ( https://github.com/conda-forge/admin-requests/pull/746 )
