### ISSUE TITLE
ENH: Define package hints in a place that doesn't need a new linter version for updates

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-smithy#1740]
In #1734, I added a dictionary `specific_hints`, which built upon existing nudges (e.g. about matplotlib-base), and is meant to be both performant and extensible:

> As a [side note](https://github.com/conda-forge/conda-smithy/pull/1734#discussion_r1186575235), I made this a dictionary (rather than a chain of cases) because I expect this list to grow substantially and wanted to keep performance snappy (checking dict membership is fast in python).
> 
> The anticipated growth is not mainly due to renamings, but because I think it would be useful for all kinds of output-hygiene (e.g. packages from archived/abandoned/superseded feedstocks, like all the ancient "homegrown" cuda feedstocks).

 @beckermr noted:

> It'd be nice to store this metadata somewhere else so that we can add to it without making a smithy release. This can happen in another PR though.

I agree that this would be good. Opening this issue to discuss where we should keep that information, and how the linter would interface with it.

**Comment by beckermr** [comment]
I think we could simply serve it out of the docs repo and point back to a GitHub raw url.

**Comment by h-vetinari** [comment]
I was looking at this again. Do you have a preferred path in mind in the docs repo? Something like [`misc/`](https://github.com/conda-forge/conda-forge.github.io/blob/main/misc)?

I'm thinking it would be nice to make it a TOML file (instead of say, a json, like already present in `misc/`), so we can keep comments. Though YAML would also work of course, and is more wide-spread in our infra...

**Comment by beckermr** [comment]
Another option is to ship it as part of the conda-forge-metadata package, though this may have other implications. We could make the dependence optional. We could also put it in the pinnings repo. This last idea actually sounds better to me since the migrators for renames go there as well. We can add the hint when we write the migrator.

**Comment by h-vetinari** [comment]
Fine by me to do it in pinnings repo. Where would you like to put it? Under `recipe/linter`?

**Comment by beckermr** [comment]
Definitely inside the recipe dir. I don't care otherwise.

**Comment by h-vetinari** [comment]
PR: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4926

**Comment by h-vetinari** [comment]
Let's close this when we're actually using it.
