### ISSUE TITLE
How to regenerate CI files for python bindings with conda smithy?

### ISSUE THREAD

**Issue by ilya-lavrenov** [conda-forge/conda-smithy#1743]
### Comment:

I have a product with C++ and Python APIs. Obviously, I want to have multiple python versions supported by the product (and hence by conda build infra).
I have created conda_build_config.yml in recipe folder with the following content:
```
python:
  # part of a zip_keys: python, python_impl, numpy
  - 3.8.* *_cpython
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
```
Then I am trying to run `conda smithy regenerate recipe` from the root of the feedstock repo and have the following error:
```
ValueError: variant config in /openvino-feedstock/recipe/conda_build_config.yaml is ambiguous because it
does not fully implement all zipped keys (To be clear: missing ['numpy', 'python_impl'])
or specifies a subspace that is not fully implemented (To be clear:
.. we did not find ['3.11.* *_cpython'] from {'python': ['3.8.* *_cpython', '3.9.* *_cpython', '3.10.* *_cpython', '3.11.* *_cpython']} in python:['3.8.* *_cpython', '3.9.* *_cpython', '3.10.* *_cpython']).
```

Is there any end to end example? All conda documentation is written for conda developers, but not for conda users and it's very hard to find answers on (from the first glance) simple questions. 

I see multiple repositories don't even have conda_build_config.yml files, but supsisingly they have the generated .ci_support files. Example is OpenCV https://github.com/conda-forge/opencv-feedstock/blob/main/.ci_support/
How those files are generated in OpenCV without having conda smithy config?

**Comment by ilya-lavrenov** [comment]
CC @isuruf @xhochy

**Comment by xhochy** [comment]
You are missing a `python` dependency in `host` in your PR.
