### ISSUE TITLE
On appveyor, use already installed conda installations?

### ISSUE THREAD

**Issue by janschulz** [conda-forge/conda-smithy#176]
See here for a transitioned recipe: https://github.com/matplotlib/matplotlib/pull/6462

See also: https://github.com/appveyor/ci/issues/359 which seens to be the issue implementing it (from https://twitter.com/tacaswell/status/734460129928712192)

**Comment by ocefpaf** [comment]
We already do that in [`staged-recipes`](https://github.com/conda-forge/staged-recipes/blob/master/appveyor.yml#L66-L71) and [`conda-smithy`](https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/appveyor.yml.tmpl#L7).

But that is a nice idea to spread to other projects :wink:

**Comment by janschulz** [comment]
But why is it still using: https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/appveyor.yml.tmpl#L49

```
    - appveyor DownloadFile "https://raw.githubusercontent.com/pelson/Obvious-CI/master/bootstrap-obvious-ci-and-miniconda.py"
    - cmd: python bootstrap-obvious-ci-and-miniconda.py %CONDA_INSTALL_LOCN% %TARGET_ARCH% %CONDA_PY:~0,1% --without-obvci
    - cmd: set PATH=%CONDA_INSTALL_LOCN%;%CONDA_INSTALL_LOCN%\scripts;%PATH%
```

**Comment by ocefpaf** [comment]
Right. I missed that part. We should improve the smithy then. Not sure is the `bootstrap` is downloading or using the local version.

**Comment by pelson** [comment]
:+1: on doing this. I'd like this to be a coherent part of the simplification we need to do to the feedstocks for 1.0.

**Comment by janschulz** [comment]
I just made the experience that updating conda also updates the python in the root env and that update takes ages on appveyor up to the point that I disabled updating conda again (https://github.com/conda/conda/issues/1923#issuecomment-231365480) . So it might be better to always start with a uptodate conda install...

**Comment by jakirkham** [comment]
Already thinking about this, see @jjhelmus and my discussion beginning with this [comment]( https://github.com/conda-forge/staged-recipes/issues/610#issuecomment-227273497 ).

**Comment by jakirkham** [comment]
Though we already have to update `python` and `conda` in AppVeyor in `staged-recipes` and it only takes us a little less than ~2min for that setup w/o building, which includes installing all our dev stuff. See this [log]( https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.4367/job/s1kv3mfrbvhl0qfe#L13 ). In any event, I don't think it is that bad at conda-forge. Though we do have access to the highest tier on AppVeyor.

I guess the only question is do we want to port over what we are doing at staged-recipes (pretty easy to do) or do we want to hold out for our own Miniconda? Personally I'd be ok porting this code over for the meantime if we are happy with it. Besides there are some Window issues we have to detangle before we can build `conda` and `conda-env`.

**Comment by jakirkham** [comment]
The code used to do this at `staged-recipes` is in PR ( https://github.com/conda-forge/staged-recipes/pull/982 ).

**Comment by jakirkham** [comment]
Also to reference the installer discussion. Please see issue ( https://github.com/conda-forge/conda-forge.github.io/issues/90 ).
