### ISSUE TITLE
appveyor template does not honor channels->sources

### ISSUE THREAD

**Issue by janschulz** [conda-forge/conda-smithy#178]
It includes `    - cmd: conda config --add channels conda-forge` directly: https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/appveyor.yml.tmpl#L56 Evyery other template iterates over the channels:

https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/travis.yml.tmpl#L48-L50

PR is incoming...

**Comment by pelson** [comment]
Looks like #179 will solve this. There are no objections from me on that PR, so I'll close this one.
