### ISSUE TITLE
badges point to the wrong github user in private feedstocks

### ISSUE THREAD

**Issue by janschulz** [conda-forge/conda-smithy#180]
The readme template has conda-forge hardcoded: https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/README.md.tmpl#L73

I tried to fix that once:
https://github.com/conda-forge/conda-smithy/pull/58/commits/f7fdfb57f02c8f74d54d478bdb042a45c0f3bd69
and then use it in the templates: https://github.com/conda-forge/conda-smithy/pull/58/commits/4f0a833162e78bc4150aaa9e1733ab7a774b056b#diff-761fe9ab7b458354bfa62ed0268e948dR48

Would you accept a PR which would simply set `conda-forge` as the default github user in the [regenerate step](https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/configure_feedstock.py#L306-L312) and, if the user includes it in config, it would be taken from the `conda-forge.yml` file?

**Comment by pelson** [comment]
Certainly would @janschulz! The default needs to be conda-forge, but other than that, makes a lot of sense to me! :+1:
