### ISSUE TITLE
`.gitignore` changes from `3.30.2` break maturin builds on linux

### ISSUE THREAD

**Issue by pavelzw** [conda-forge/conda-smithy#1827]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

See https://github.com/conda-forge/polars-feedstock/issues/205

The changes in `.gitignore` (see https://github.com/conda-forge/polars-feedstock/pull/204/commits/fd6c747f2c11c8b5bbbedd1e75a2aed6bc8ddba7) lead to the maturin builds in polars-feedstock for `build_platform == linux*` being empty.
Only the polars shared object was in the final package. All `.py` files were missing.

Maybe we should revert (parts of) #1413 again?

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by xhochy** [comment]
This should be fixed via https://github.com/conda-forge/conda-smithy/pull/1819

**Comment by pavelzw** [comment]
Thanks!

**Comment by jakirkham** [comment]
Yeah I think we just need a release

**Comment by hmaarrfk** [comment]
I released 3.30.3

**Comment by jleibs** [comment]
Very much appreciate the report and work-around. Was fighting this exact same problem in our latest release.

In my opinion this is technically a maturin bug rather than something logically wrong with the conda-smithy rule. I created a corresponding maturin issue (https://github.com/PyO3/maturin/issues/1911), though we'll definitely need the workaround for the time being.

**Comment by xhochy** [comment]
The workaround is to rerender with the latest conda-smithy.

**Comment by hmaarrfk** [comment]
Unfortunately it isn't that easy, the 3.30.3 version hasn't been released to conda-forge's conda repo so 
https://github.com/conda-forge/conda-smithy-feedstock/pull/274

will have to be pushed through first.

**Comment by pavelzw** [comment]
xref https://github.com/PyO3/maturin/pull/2158
