### ISSUE TITLE
linux-32 builds 

### ISSUE THREAD

**Issue by AbdealiJK** [conda-forge/conda-smithy#183]
It would be nice to have 32bit builds in Linux. Right now, only linux-64 is there https://conda.anaconda.org/conda-forge

This way linux-32 packages would also be created when submitting to conda ?

**Comment by AbdealiJK** [comment]
Apparently travis doesn't support 32bit nor has a plan in the near future to do so - https://github.com/travis-ci/travis-ci/issues/5770
So I guess it can be done by cross compiling (Installing a 32bit conda), or using a 32bit docker image

**Comment by pelson** [comment]
Hi @AbdealiJK. Thanks for submitting this issue. Whilst the changes would involve conda-smithy, we would normally discuss this in the [conda-forge/conda-forge.github.io](https://github.com/conda-forge/conda-forge.github.io/) repo. Interestingly we haven't discussed 32bit linux builds there yet, but it did come up in one of the feedstocks at: https://github.com/conda-forge/eofs-feedstock/issues/1

As I said in that issue, I have been a bit surprised about the lack of demand for linux-32 builds. There are clearly some people who want it, but it isn't clear that the effort needed to implement it outweighs the benefits.

Technically, I'm pretty comfortable that linux-32 builds are completely achievable with CI (circle + docker gives you a lot of power).

Perhaps you can bring this up as an issue on https://github.com/conda-forge/conda-forge.github.io/ and if interested join us for a future conda-forge developer hangout (there is one this Friday, but I'm aware the agenda is already quite full, so maybe the one after).

Cheers,

**Comment by jakirkham** [comment]
I know @rgommers mentioned some interest in this as well at one point.

**Comment by rgommers** [comment]
I did, but there's not a lot of demand so I agree with @pelson that the effort/benefit tradeoff here isn't clear. The main reason I'm using it is to catch issues not found on TravisCI for Numpy and Scipy.

**Comment by AbdealiJK** [comment]
This issue was moved to conda-forge/conda-forge.github.io#163
