### ISSUE TITLE
Lint: ideas from recent submission

### ISSUE THREAD

**Issue by jankatins** [conda-forge/conda-smithy#184]
These probably come from using a  `conda skeleton pypi ...`
- [ ] if the URL contains a long link to the pypi location, ask it to be changed to `https://pypi.io/packages/source/<first letter of package>/<package>/<filename>`
- [ ] If it contains a git link and a tag (instead of a commit ID), tell it to include a real commit id instead of a tag
- [ ] if bld.bat or build.sh is just `python setup.py install` (or the setuptools variant) suggest removing this and adding the line to the meta.yml
- [ ] if recipe contains an install dependency on setuptools, check that the python call uses `--single-version-externally-managed --record=record.txt`
- [ ] check for the version declaration at the top of the file and that it is used in all lines whichuse a version (filename, URL, version)
- check for some licenses: `BSD`/`BSD license` -> `BSD 3-clause` and  `Python` -> `PSF` -- see issue ( https://github.com/conda-forge/conda-smithy/issues/88 )
- [ ] if it contains `# List any patch files here` or `# noarch_python: True` suggest removing these skeleton remnants

**Comment by jakirkham** [comment]
Have changed these to checklist items so it is easier to track progress. Also the license check is already another issue, so noted that next to that line.

**Comment by jakirkham** [comment]
> If it contains a git link and a tag (instead of a commit ID), tell it to include a real commit id instead of a tag

Should add that I'm not sure how I feel about this one.
