### ISSUE TITLE
Release 3.30.5 or 3.31.0?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#1845]
Should we do a new conda-smithy release? Here is [the changelog]( https://github.com/conda-forge/conda-smithy/compare/v3.30.4...main )

Idk if we should do 3.30.5 or 3.31.0. Was thinking the latter with PR ( https://github.com/conda-forge/conda-smithy/pull/1844 ), but open to other thoughts

**Comment by mbargull** [comment]
>  3.30.5 or 3.31.0

The latter.

**Comment by h-vetinari** [comment]
Let's please include #1846

**Comment by jakirkham** [comment]
Done

https://github.com/conda-forge/conda-smithy/releases/tag/v3.31.0
