### ISSUE TITLE
Lint: decrement build number on new upstream version

### ISSUE THREAD

**Issue by janschulz** [conda-forge/conda-smithy#185]
Not sure how easy it is, but it would be nice if the linter would tell you to set the build number back to 0 if you build a new upstream version.

**Comment by pelson** [comment]
I don't think a static linter can ever know this - you need to know something about history to be able to do it (either by looking at the git repo, or by inspecting anaconda.org).

I agree with the desire, but at the moment this is not going to be possible to achieve and will continue to require human reviewing.

I'm going to close this as a wontfix, but if you wanted to prototype such a capability, I'd be more than interested to see how you go about implementing it.

:+1:

**Comment by janschulz** [comment]
> you need to know something about history to be able to do it (either by looking at the git repo, or by inspecting anaconda.org)

Yes, I think so too :-/ My idea was looking at versions on anaconda.org.

The problem here is that the solution is conda-forge specific: it would be either hardcoded to the conda-forge account or would need to open conda-forge.yml to get the destination channel.
