### ISSUE TITLE
Pydantic Schema for conda-forge.yml removed top-level platform keys

### ISSUE THREAD

**Issue by ytausch** [conda-forge/conda-smithy#1863]
### Comment:

#1756 did not include the following top-level keys that were mentioned in the [old docs](https://github.com/conda-forge/conda-forge.github.io/blob/81b3f247a5e08e9a0cd31de84c77e961f0aae2ee/docs/maintainer/conda_forge_yml.md): `linux`, `linux_aarch64`, `linux_ppc64le`, `osx`, `win`.

Is that intended?

**Comment by isuruf** [comment]
>  So the fields should be removed from feedstocks then?

Yes
