### ISSUE TITLE
automatically replace test_on_native_only with test: native_and_emulated

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-smithy#1867]
### Comment:

is there a reason why we aren't making rerendering replace it with the appropriate string?

I might have time to program this into the rerendering process.

These messages are really tiring to act on.
https://github.com/conda-forge/nss-feedstock/pull/79#issuecomment-2000378396

**Comment by hmaarrfk** [comment]
oh it seemes somebody already did this:
https://github.com/conda-forge/nss-feedstock/commit/4473199f5a4246cdc8011e955190c6b66ef433ce

**Comment by jakirkham** [comment]
Please see PR: https://github.com/conda-forge/admin-migrations/pull/97

**Comment by jakirkham** [comment]
Also there is some discussion on improving messaging in issue: https://github.com/conda-forge/conda-smithy/issues/1860

Please feel free to make additional suggestions there
