### ISSUE TITLE
optionally make schema validation errors a warning instead of erroring out during rerenders

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-smithy#1879]
This feature is stopping the bot from making PRs on effected feedstocks. As @isuruf has pointed out, the linter will error on the CI checks anyways, so letting the rerender go through is fine. 

At minimum, we can add an optional override to only warn.

**Comment by jakirkham** [comment]
Yeah warning on re-rendering seems like a better default

Having an option to convert warnings to errors in conda-smithy could be useful, but maybe that is not needed given the linter already errors. If we do add such an option, it would be good to cover on CI (to catch any false positives early)

**Comment by jaimergp** [comment]
Agreed on this strategy.

* `conda-smithy rerender` will warn about validation errors. If they are critical, they'll fail later in the job anyway.
* `conda-smithy recipe-lint` will error out.
