### ISSUE TITLE
ENH: Take into account `stdlib_version` for determining macOS SDK version in `.ci_support/` and cf-ci-setup

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-smithy#1884]
With the introduction of `{{ stdlib("c") }}` and [`macosx_deployment_target`](https://github.com/conda-forge/osx-sysroot-feedstock), we have a new & better way to specify the required macosx deployment target. However, that means if people change to the new way, we need to take that into account when setting up the CI image (i.e. [`download_osx_sdk.sh`](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/main/recipe/download_osx_sdk.sh) in the ci-setup).

Additionally, we should warn about doubly specified deployment targets in cbc.yaml. My suggested proposal is:
* warn in smithy if `MACOSX_DEPLOYMENT_TARGET` is specified in cbc.yaml
* error in smithy if `MACOSX_DEPLOYMENT_TARGET` is in contradiction with a local `c_stdlib_version` on osx (not the one coming from the global pinning)
* keep writing `MACOSX_DEPLOYMENT_TARGET` to the `.ci_support/*.yaml` files, filled by whatever is in `c_stdlib_version` on osx
* that way, we don't need to touch the conda-forge-ci logic, which can keep working as-is for `MACOSX_DEPLOYMENT_TARGET` / `MACOSX_SDK_VERSION`.

Thoughts? @isuruf @mbargull @beckermr

**Comment by beckermr** [comment]
SGTM!

We probably want to have a linting errors for certain things (like the first bullet point) in addition to smithy warnings.

**Comment by isuruf** [comment]
Let's do the warning for a few releases and switch to an error.
