### ISSUE TITLE
Add CONDA_PERL

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#190]
We should add support for `CONDA_PERL`. I think I see vaguely where this would go, but am not clear that it would be treated the same way as other `CONDA_*`.

**Comment by jakirkham** [comment]
cc @msarahan @pelson @ocefpaf

**Comment by pelson** [comment]
Closing, I think this is the same answer as https://github.com/conda-forge/conda-smithy/issues/191#issuecomment-223738023. If this isn't already working, I consider it a bug (and will try to track it down for 1.0).

Thanks @jakirkham

**Comment by jakirkham** [comment]
Should I open a new issue for the bug then?

**Comment by pelson** [comment]
Feel free to reuse this one.

**Comment by jakirkham** [comment]
Basically thinking about the issues we encountered in `autoconf` ( https://github.com/conda-forge/autoconf-feedstock/pull/8 ) and recently in `fftw` ( https://github.com/conda-forge/fftw-feedstock/pull/6 ). Somehow the version isn't being set right or we are missing a step. 😕 Should we be re-rendering maybe? Honestly, I think we can get away with one version of Perl, which would hopefully simplify this then.

**Comment by pelson** [comment]
> Should we be re-rendering maybe?

Yes definitely.

**Comment by jakirkham** [comment]
Indeed you are correct. Works find once the PEBCAK bug is fixed. 😉 ( https://github.com/conda-forge/autoconf-feedstock/pull/9 )
