### ISSUE TITLE
Add CONDA_LUA

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#191]
How do we want to handle these? We should be setting them somehow, but we need to figure out whether they need to be in a matrix or if we just want to support one.

cc @pelson @alexbw @ocefpaf @mingwandroid @msarahan

**Comment by msarahan** [comment]
I have no opinion, and leave it to the domain experts.  I think the only major consideration is the culture of either ecosystem.  Do people migrate to new versions pretty much right away, or straggle, like Python 2?  Also, are there major library/API differences that make earlier versions incompatible (like Python2 vs 3)?

**Comment by alexbw** [comment]
In Lua, people pick LuaJIT 2.0, LuaJIT 2.1, Lua 5.1, Lua 5.2 or Lua 5.3,
and build software around those versions. Migration upwards happens
extremely slowly.

**Comment by janschulz** [comment]
R ist mostly upwards compatible (Apart from an upcoming problem with a compiler change on windows between 3.3 and 3.4) and the ecosystem has some "nagging" features which help users along, at least on minor versions... CRAN supports the last two versions (usually 1yr apart) with packages, so users migrate quite relatively quickly... 

Re nagging: Cran recompiles packages on each minor version and so r itself tells you when a package was compiled/ build a newer version. So probably we would need to recompile on each minor version?

**Comment by jakirkham** [comment]
@alexbw, do you know of other packages on Lua that are NumPy-esque and worth building multiple versions of? Trying to get a scope of the build matrix with Lua.

**Comment by jakirkham** [comment]
Excellent thanks for the insight @janschulz. Didn't realize you knew so much about R. Will be pinging you frequently as questions about R arise. 😄 Do you know when 3.4 is expected? Also, what is the scope of the compiler change there? In any event, supporting two versions of R seems totally reasonable. Are there any other packages with R that we should worry about including in the build matrix as we do with NumPy?

**Comment by alexbw** [comment]
Everybody uses close to head of master of all other libraries.

**Comment by jakirkham** [comment]
Also, I tried to ping people that I knew who had a stake in these. While I am interested in fostering the growth of these other languages here, I'm not well versed in how they are structured. So, if you know others that would care about these constraints and be able to share some other details, please feel free to bring them over here.

**Comment by alexbw** [comment]
People do differentiate between lua and luajit, like CPython and PyPy. Both
are in common use. I think I have added a luajit flag in conda-build to
reflect this.

**Comment by pelson** [comment]
@jakirkham - basically this is already done by conda-smithy (through the [special_case_version_matrix](https://github.com/SciTools/conda-build-all/blob/master/conda_build_all/version_matrix.py#L103) function in conda-build-all).

If you make [perl](https://github.com/SciTools/conda-build-all/blob/master/conda_build_all/version_matrix.py#L217) or [r](https://github.com/SciTools/conda-build-all/blob/master/conda_build_all/version_matrix.py#L227) a dependency, you will automatically get a matrix of the latest 2 major versions of those languages. We should totally add `lua` to that function though.

**Comment by janschulz** [comment]
> Didn't realize you knew so much about R. Will be pinging you frequently as questions about R arise. :smile: > Do you know when 3.4 is expected?

Seems that 3.3 also aready uses the new version and I never noticed because I only had to (re)compile native packages for devel which was already 3.4:
 
https://github.com/rwinlib/r-base#readme
https://cran.r-project.org/bin/windows/Rtools/

I've a local script which basically sets up all the right stuff based on the rtools 3.3 install (which works for 3.1, 3.2 and 3.3+.

If someone wants to salvage that:
```
@echo off
setlocal
setlocal EnableDelayedExpansion

set DEFAULT_PACKAGES=repr,IRKernel,IRDisplay
set DEFAULT_R_VERSION=3.3
set DEFAULT_COMPILE_BOTH=no
set DEFAULT_BUILD_VIGNETTE=no
set DEFAULT_CHECK_PACKAGE=no
set DEFAULT_MOVE_PACKAGE=yes
set DEFAULT_MOVE_PACKAGES_DIR=_build_packages

REM to install:
rem install.packages(c("rzmq","repr","IRkernel","IRdisplay"), repos="file:C:/data/external/R/irkernel.github.io")

set old=%CD%
cd %~dp0

set CHECK=!DEFAULT_CHECK_PACKAGE!
set VIGNETTE=!DEFAULT_BUILD_VIGNETTE!
set MOVE=!DEFAULT_MOVE_PACKAGE!
set BOTH=!DEFAULT_COMPILE_BOTH!
FOR %%A IN (%*) DO (
    set ARGARG=%%A
    set FIRST_THREE=!ARGARG:~0,3!
    set ALL_BUT_FIRST_THREE=!ARGARG:~3!
    if [!ARGARG!] == [--check] (
        set CHECK=yes
    ) else if [!ARGARG!] == [--no-check] (
        set CHECK=no
    ) else if [!ARGARG!] == [--vignette] (
        set VIGNETTE=yes
    ) else if [!ARGARG!] == [--no-vignette] (
        set VIGNETTE=no
    ) else if [!ARGARG!] == [--both] (
        set BOTH=yes
    ) else if [!ARGARG!] == [--no-both] (
        set BOTH=no
    ) else if [!ARGARG!] == [--move] (
        set MOVE=yes
    ) else if [!ARGARG!] == [--no-move] (
        set MOVE=no
    ) else if [!FIRST_THREE!] == [--R] (
        if [!RVER!] == [] (
            set "RVER=!ALL_BUT_FIRST_THREE!
        ) else (
            set "RVER=!rver!,!ALL_BUT_FIRST_THREE!
        )
    ) else (
        if [!PACKAGES!] == [] (
            set PACKAGES=!ARGARG!
        ) else (
            set PACKAGES=!PACKAGES!,!ARGARG!
        )
    )
)
if [!PACKAGES!] == [] set PACKAGES=%DEFAULT_PACKAGES%
if [!RVER!] == [] set RVER=%DEFAULT_R_VERSION%

if [!VIGNETTE!] == [yes] (
   set VIG_BUILD= 
   set VIG_CHECK= 
) else (
  set VIG_BUILD=--no-build-vignettes
  set VIG_CHECK=--no-build-vignettes --no-vignettes
)

if [!BOTH!] == [yes] (
   set COMPILE_BOTH=--compile-both
) else (
   set COMPILE_BOTH= 
)


echo # Building packages: !PACKAGES!
echo # Building both 32bit and 64bit: !BOTH!
echo # Checking: !CHECK!
echo # Moving build packages: !MOVE!

set "OLDPATH=%PATH%"

set old=%CD%
cd %~dp0

for %%V IN (%RVER%) do (
echo # Building for R-%%V

set R_ARCH=x64
set "R_HOME=c:\Program Files\R\R-%%V"
echo !R_HOME!

rem put main programs into path: r, non-compiler stuff
set "PATH=c:\Rtools\bin;!R_HOME!\bin\x64;!OLDPATH!"

rem only for 3.3+, but doesn't hurt on 3.2 - R 3.2 compiler
set "BINPREF=C:/Rtools/mingw_$(WIN)/bin/"

if [%%V] == [3.2] set "PATH=!PATH!;C:\Rtools\gcc-4.6.3\bin"

REM echo !PATH!
REM R -e "R.Version()"
REM pause

rem @echo off
REM setlocal EnableDelayedExpansion


for %%G IN (!PACKAGES!) do (
   echo # Installing dependencies for %%G
   cd %%G
   R -e --slave "devtools::install_deps('.') 
   cd ..
   echo.
   echo # BUILDING package %%G
   R CMD build !VIG_BUILD! %%G
   echo.
   echo # INSTALLing package %%G
   R CMD INSTALL --build !COMPILE_BOTH! %%G
   if [!CHECK!] == [yes] (
        echo.
        echo # CHECKING the package
        R CMD check !VIG_CHECK! --as-cran %%G*.tar.gz
   )
   if [!MOVE!] == [yes] (
        echo # Moving build packages to: .\!DEFAULT_MOVE_PACKAGES_DIR!
        move /Y %%G*.zip .\!DEFAULT_MOVE_PACKAGES_DIR! > NUL
        move /Y %%G*.tar.gz .\!DEFAULT_MOVE_PACKAGES_DIR! > NUL
    )
)
)
endlocal
endlocal

cd %OLD%
```

Put checkouts of package into subdirs and use as `buildpackage --R3.2 --R3.3 --check irkernel` (for the irkernel checkout). 

The main thing apart from setting up PATH is `set "BINPREF=C:/Rtools/mingw_$(WIN)/bin/"` which is needed so that the right compiler is chosen for 32/64 bit binaries (3.2 and below as far as I know uses the same compiler and `-m32` os so).

**Comment by mingwandroid** [comment]
I released R 3.3.0 for Windows a week ago. You can find my recipe here:

https://github.com/conda/conda-recipes/tree/master/r-base

I don't use rtools since that's just based on msys2 anyway, just quite out of date, instead I use msys2 directly.

**Comment by janschulz** [comment]
@mingwandroid Yay, great! Any chance of getting that into conda-forge? 

Re rtools: How do you handle packages? Just uses msys2 and set BINPREF to the same value and let the conda build time dependencies do the magic?

**Comment by jakirkham** [comment]
Closing and punting this upstream ( https://github.com/SciTools/conda-build-all/issues/67 ).
