### ISSUE TITLE
lint on most wheel-based python installs except `noarch: python` and `none-any.whl`

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-smithy#1935]
There are now several feedstocks that use pure python wheels with `noarch: python` recipes. This procedure is in principle safe, but an sdist is preferred. We should lint on any usage of wheels outside this one case. A second PR might also provide a hint that sdists are preferred.

**Comment by beckermr** [comment]
cc @jaimergp

**Comment by hmaarrfk** [comment]
One challenge is that many first time packagers on pypi will only publish wheels and not sdist. 

Should the message be condition on the existing of an sdist for the same version of the package?

**Comment by hmaarrfk** [comment]
Sorry. My comment did understand that you are ok with the wheel + no arch case
