### ISSUE TITLE
How to test updates to `.travis.yml`

### ISSUE THREAD

**Issue by mfansler** [conda-forge/conda-smithy#1940]
### Comment:

I've been in touch with Travis CI Support regarding https://github.com/conda-forge/status/issues/178. In a recent email, they've suggested try changing:

- `language: generic` to `language: shell`
- `matrix.include` to `jobs.include`

to see if that makes any difference. How should I actually test these? I realize this could be a simple PR here, but seems like jumping the gun to update `conda-smithy` itself without evidence that these changes aren't superficial.

Should I test manually overwriting these (i.e., temporarily edit the `.travis.yml` without a rerender) in a draft PR on an affected repository?

**Comment by hoechenberger** [comment]
Hello @mfansler, were you able to make any progress on this? 🙂

**Comment by beckermr** [comment]
Just make an edit by hand in a feedstock and see what happens.
