### ISSUE TITLE
Obvious-CI is pulled from pelson channel in Windows

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/conda-smithy#197]
In the appveyor.yml template the obvious-ci package is [installed from pelson/channel/develoment](https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/appveyor.yml.tmpl#L55) which installs version 0.5.1.  Version 0.6.1 is available from the conda-forge channel which includes a `obvci_appveyor_python_build_env.cmd` script with some important changes.  ~~Specifically, the wrong version of Visual Studio may be used to build Python 3.5 extensions with the older, 0.5.1, script.~~

**Comment by jjhelmus** [comment]
So I checked into this a bit more and the changes in obvious-ci between version 0.5.1 and 0.6.1 are not that significant and Python 3.5 should be fine.  Changing the install locations to the `conda-forge` channel still seems like a good idea.

**Comment by ocefpaf** [comment]
+1 (but I believe @pelson has a long term plan to eliminate obvious-ci
entirely.)
Em 14/06/2016 15:45, "Jonathan J. Helmus" <notifications@github.com>
escreveu:

**Comment by jakirkham** [comment]
Honestly don't know the answer to this question. What is obvious-ci still being used for?

**Comment by pelson** [comment]
> What is obvious-ci still being used for?

https://github.com/conda-forge/toolchain-feedstock/issues/1

**Comment by jakirkham** [comment]
Second question is there any reason not to just install the `conda-forge` one?

**Comment by jakirkham** [comment]
cc @MSeifert04

**Comment by jakirkham** [comment]
We have been using the `conda-forge` copy of `obvious-ci` version `0.6.1` at `staged-recipes` for some time as it gets upgraded through the `conda update` steps. This has worked without issue.

**Comment by jakirkham** [comment]
Changed to the `conda-forge` channel copy in PR ( https://github.com/conda-forge/conda-smithy/pull/370 ). If this does cause problems, please let me know and we can fix it.
