### ISSUE TITLE
ENH: linter should raise error on duplicate keys in `conda-forge.yml`

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-smithy#2004]
Otherwise, this breaks the automerge bot in an unexpected way (invisibly too, unless one goes checking the GHA logs).

Here's are some [example](https://github.com/conda-forge/libcxx-feedstock/actions/runs/10170868302/job/28130805384) logs; the duplication in the `conda-forge.yml` is [real](https://github.com/conda-forge/libcxx-feedstock/blob/68951b4e67b5e362b6c39d6a6009c5770cba87a8/conda-forge.yml#L6-L14) and an issue that'll be fixed, but in any case, this looks like a prime example of what we'd want the linter to check.

**Comment by jakirkham** [comment]
Maybe @ytausch would be interested in this 😉
