### ISSUE TITLE
Get rid of rattler branding

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#2014]
We should get rid of rattler branding here for future conda recipe v2 support in conda-build itself.

For eg: Rename `rattler_linter.py` to `conda_recipe_v2_linter.py` and similar.

cc @nichmor, @wolfv, @beckermr

**Comment by wolfv** [comment]
works for me but I would prefer to do it later :)

**Comment by beckermr** [comment]
I agree 100%.

**Comment by beckermr** [comment]
What do we want to do about API breaks due to this change? 

cc @nichmor

**Comment by nichmor** [comment]
I also plan to rename functions from `lint_rattler_noarch_and_runtime_dependencies` to 
`lint_recipe_v2` ... and keyword arguments `is_rattler_build` to `is_recipe_v2`.


I think if we release these changes as major release, we are ok ?

cc @wolfv @beckermr @isuruf

**Comment by beckermr** [comment]
cc @conda-forge/core for viz on a possible major version bump or a one-time API break or something else...

**Comment by wolfv** [comment]
@beckermr - I feel like no one has used these APIs beyond conda-smithy itself. We could re-export them under the old name and deprecate, but I feel that adds too much hassle for such a new thing.

**Comment by beckermr** [comment]
I agree with this assessment @wolfv. Let's wait for some other comments from core to ensure we have a semblance of consensus.

**Comment by jaimergp** [comment]
Should the API instead support a `recipe_version: int` kwarg that forwards to the appropriate backend? I'm fine with a major bump but if there are other tasks required that involve breakage, we should use that opportunity.

**Comment by isuruf** [comment]
We commented at the same time. https://github.com/conda-forge/conda-smithy/pull/2024/files#r1705766595

**Comment by nichmor** [comment]
I agree about `recipe_version` but going into more implementation specifics - could we use an Enum for this? rather than passing a integer there

**Comment by wolfv** [comment]
I think an enum that maps to an integer would be best.
