### ISSUE TITLE
Rerender broken for clang-compiler-activation-feedstock

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-smithy#2021]
I'm opening this here more for visibility, because AFAICT it's a regression in conda-build: https://github.com/conda/conda-build/issues/5443

However, since I wasn't able to determine the exact conditions that trigger the bug, it might be that other recipes are affected as well, hence this issue.

**Comment by jakirkham** [comment]
As it sounds like upstream this was due to undefined Jinja variables, it sounds like this is the same as issue: https://github.com/conda-forge/conda-smithy/issues/2011

**Comment by jakirkham** [comment]
Am curious if conda-build 24.9.0 fixes the original issue

**Comment by h-vetinari** [comment]
Confirmed to work in https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/141 without the (previously introduced) workaround for this issue.
