### ISSUE TITLE
CircleCI pseudo-matrix via parallelism

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#203]
There are a few feedstocks that get right up to the limit on CircleCI or cross over. While CircleCI does not have a proper notion of matrix builds, it does have a notion of parallelism, which one might be able to extend to act like a matrix build. See this CircleCI [discussion](https://discuss.circleci.com/t/build-matrix/584). Also, see this MIT licensed [code](https://github.com/michaelcontento/circleci-matrix), which can be used in that direction. We should investigate integrating this into `conda-smithy` and possibly [`staged-recipes`](https://github.com/conda-forge/staged-recipes).

cc @Korijn @ivoflipse @ccordoba12 @msarahan @jschueller @grlee77

**Comment by Korijn** [comment]
Sounds like a plan to me. It would be incredibly useful for the VTK package, and many other's, I'm sure. :) I'm not too aware of the inner workings of `conda-smithy` (yet) though, so I'm not sure how much I can contribute.

**Comment by jakirkham** [comment]
Looks like SciPy might be in need of such a solution. See issue ( https://github.com/conda-forge/scipy-feedstock/issues/8 ).

**Comment by jakirkham** [comment]
Trying to package some tools that should be helpful for solving this problem. See PR ( https://github.com/conda-forge/staged-recipes/pull/1151 ).

**Comment by jakirkham** [comment]
So you [asked]( https://github.com/conda-forge/vtk-feedstock/issues/6#issuecomment-250521445 ) for an update @Korijn, here's a brief one.

I took a look at trying to do this with `circleci-helpers`. It's not quite the experience or the effect I want as it will result in much uglier code and possibly make it harder to debug what is going on. It is uglier as we need to setup the matrix outside the docker container and somehow effect the container with this matrix. It would be harder to debug as we may not be able to nicely divide the builds amongst the parallelism provided. So we may have to intermix arbitrary builds in the same parallel job. I'll try to look at it again as I have time, but it will have to wait until after `conda-build` 2 is out and some other internal projects are completed.

**Comment by Korijn** [comment]
Okay, thanks for the update and clarification! I can imagine some of the troubles involved.

**Comment by jakirkham** [comment]
Should add this doesn't need to be a single person effort. So if you have some good ideas you want to play with, feel free to give it a go and I can try to help out.

**Comment by jakirkham** [comment]
So this is really neat idea. Not sure how well it would work in practice, but just noting it here for future reference. One can start [parameterized builds]( https://circleci.com/docs/parameterized-builds/ ). So we could envision a CircleCI build that spawns other CircleCI builds that make up the matrix. If we want to be really efficient, the CircleCI build doing the spawning could be one of the builds itself. Depending on the interface this could be more intuitive than parallelism. Will need to see.

**Comment by jakirkham** [comment]
It looks like we might actually be able to add [real matrix builds]( https://circleci.com/docs/2.0/workflows/ ) on CircleCI. It requires switching to CircleCI 2.0, but that seems reasonable to do (after a cursory look at the changes). So will try to combine these together.

xref: https://github.com/conda-forge/conda-smithy/issues/527

**Comment by jakirkham** [comment]
Have implemented this in PR ( https://github.com/conda-forge/conda-smithy/pull/532 ) for CircleCI 2.0 and tested it on a few feedstocks. Seems to work ok. Though probably could use a review (potentially after the CircleCI 2.0 PR goes in).
