### ISSUE TITLE
rerender with rattler-build removing CODEOWNERS

### ISSUE THREAD

**Issue by xylar** [conda-forge/conda-smithy#2047]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I'm trying out the new recipe option with rattler-build:
https://github.com/conda-forge/pyremap-feedstock/pull/25
After rerendering, the `.github/CODEOWNERS` file has been removed and the readme has been updated to not have any maintainers.  Unless I'm doing something wrong in [my recipe](https://github.com/conda-forge/pyremap-feedstock/pull/25/files#diff-ad6aed43f0cf479348ccccec8e7185c4b70582192329f11908dd22a731771702), I think maybe the maintainers are not getting parsed correctly.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by wolfv** [comment]
Thanks for spotting this @xylar! We'll take a look on Monday at the latest. Please note that uploads aren't yet enabled for `rattler-build` :)

**Comment by xylar** [comment]
Ah, thanks for letting me know @wolfv. So I guess I'm jumping the gun a bit.

**Comment by wolfv** [comment]
This works with the latest versions of everything now! Thanks again @xylar for notifying us :)

**Comment by wolfv** [comment]
proof: https://github.com/conda-forge/pyremap-feedstock/pull/25/files/05efe995a13fa2b53843fb859462fdcc159f8292..41da383b63a4757cfb807e4bec8048a8da64376e
