### ISSUE TITLE
Travis CI skip conditions

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#205]
Recently the Travis CI queue has taken a bit of a beating. This has been caused by large demand. The small number of workers (appears to 164) quickly getting maxed out. Some unfortunate multi-day [infrastructure issues]( https://www.traviscistatus.com/incidents/rqb906yypnk0 ) that left jobs hanging. This has led me to wonder what improvements we can make in this area. The big wins unfortunately will require a significant amount of discussion and work. Though there are still some simple small wins that should improve on the situation.

Awhile back we added PRs ( https://github.com/conda-forge/conda-smithy/pull/87 ) ( https://github.com/conda-forge/conda-smithy/pull/94 ) which eliminated the `appveyor.yaml` file when it wasn't needed. Subsequently @pelson put forward PR ( https://github.com/conda-forge/conda-smithy/pull/95 ), which pushed a button on AppVeyor to disable builds when `appveyor.yaml` wasn't present. This saved a significant number of builds on AppVeyor and made that queue very usable for us.

We can use this same strategy with Travis CI. It also has a toggle switch that can be set via the Travis CI API as stated in the [docs]( https://docs.travis-ci.com/api#settings:-general ). Also, we can use the same logic to rename the `.travis.yml` file. All of this should only be a handful of lines of code. While this isn't a huge win, it is easy to do and does help some.

**Comment by pelson** [comment]
> While this isn't a huge win, it is easy to do and does help some.

Can we measure that? Any idea how many packages are skipped on OSX?

**Comment by jakirkham** [comment]
FWICT it's a handful. Still the bigger steps are likely going to involve things like configuring our own build system or integrating more CIs. See the discussion in this issue beginning with this [comment]( https://github.com/conda-forge/staged-recipes/issues/900#issuecomment-229690523 ).

Beyond the savings one might get, there are also weird bugs that one can run into too. See this issue ( https://github.com/conda-forge/cyavro-feedstock/issues/2 ) for an example.

Nevertheless I felt an obligation to do something about this problem given the issues we have had (even if this isn't a big win). So drew up two PRs to make this happen. Please see PR ( https://github.com/conda-forge/conda-smithy/pull/206 ) and PR ( https://github.com/conda-forge/conda-smithy/pull/207 ) for each part.

**Comment by pelson** [comment]
Thanks for this detail @jakirkham. FWIW, I'm available for a good few hours now to work on these issues. Ping me if you need anything.

**Comment by jakirkham** [comment]
Thanks for your help @pelson.

Now that we have PR ( https://github.com/conda-forge/conda-smithy/pull/207 ) in and PR  ( https://github.com/conda-forge/conda-smithy/pull/206 ) is tested and working. I think we are well on our way to seeing this resolved.

**Comment by jakirkham** [comment]
As sort of a test of all of this functionality (merged and proposed), please see this test PR ( https://github.com/conda-forge/c99-to-c89-feedstock/pull/3 ), which now can skip Travis CI successfully. This also includes a CircleCI skip proposed in PR ( https://github.com/conda-forge/conda-smithy/pull/218 ). Still it is useful to see all of these changes coming together.

**Comment by jakirkham** [comment]
So, I think there are ~25 feedstocks that have benefited from these improvements and skipping CircleCI builds via PR ( https://github.com/conda-forge/conda-smithy/pull/218 ). Again this isn't huge when looking at the nearly 800 feedstocks present. Still it isn't such a small number either. After all with CI usage the question is less about how many feedstocks and more about how many *active* feedstocks. Thus ~25 feedstocks ends up being a more significant number.
