### ISSUE TITLE
rerender with rattler-build removing URLs from README

### ISSUE THREAD

**Issue by xylar** [conda-forge/conda-smithy#2065]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I am testing out rattler-build: https://github.com/conda-forge/pyremap-feedstock/pull/25

It seems that a rerender is leading to the removal of the Home, Doc and Dev URLs:
https://github.com/conda-forge/pyremap-feedstock/pull/25/commits/4c6e00dae69180adde07dbe8d740a875234fcda8#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

(The issue with removing maintainers in the same rerender has already been addressed, see https://github.com/conda-forge/conda-smithy/issues/2047 and https://github.com/prefix-dev/rattler-build-conda-compat/pull/53).

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by wolfv** [comment]
Made a PR here: https://github.com/conda-forge/conda-smithy/pull/2066
