### ISSUE TITLE
false positives in lint parseability; missing link to logs

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-smithy#2158]
There seem to be false positives from the work in #2140 / #2141. For example, https://github.com/conda-forge/arrow-cpp-feedstock/pull/1623 is a PR opened by the bot, yet it says that the bot cannot parse the recipe -- obviously it can, because it opened the PR?

Also echoing a point from #2140 about the logs (which need to be introspectable, otherwise it's very hard to understand what's going wrong.)
> @jakirkham: Also it notes there are logs, but doesn't actually link them. So there is nowhere to look for info

> @beckermr: I can fix the logs. I thought the websevices included a link.

**Comment by beckermr** [comment]
> There seem to be false positives from the work in https://github.com/conda-forge/conda-smithy/issues/2140 / https://github.com/conda-forge/conda-smithy/pull/2141. For example, https://github.com/conda-forge/arrow-cpp-feedstock/pull/1623 is a PR opened by the bot, yet it says that the bot cannot parse the recipe -- obviously it can, because it opened the PR?

The bot only parses for version PRs, not rebuild PRs. So this is not a false positive.

> Also echoing a point from https://github.com/conda-forge/conda-smithy/issues/2140 about the logs (which need to be introspectable, otherwise it's very hard to understand what's going wrong.)

I shipped https://github.com/conda-forge/conda-forge-webservices/pull/781 this morning that should add links to logs to the messages from the linter.

**Comment by beckermr** [comment]
OK check now @h-vetinari and you can find the link to the logs: https://github.com/conda-forge/arrow-cpp-feedstock/pull/1623#issuecomment-2491112726

**Comment by h-vetinari** [comment]
> The bot only parses for version PRs, not rebuild PRs. So this is not a false positive.

Oh, ok. That's not evident from the name `conda-forge-tick (the bot)`...

> I shipped [conda-forge/conda-forge-webservices#781](https://github.com/conda-forge/conda-forge-webservices/pull/781) this morning that should add links to logs to the messages from the linter.

That helped a lot, thanks! It would still be nicer UX to have the error message extracted and put into the comment directly, but we also don't do that for rerender failures, currently...

**Comment by h-vetinari** [comment]
Thanks for adding the logs, let's close this issue. We can discuss extracting the errors and putting them into the bot comment in another issue, if there's demand for it.
