### ISSUE TITLE
`backports.strenum` and Python >=3.11?

### ISSUE THREAD

**Issue by wshanks** [conda-forge/conda-smithy#2198]
### Comment:

Somewhat recently the `backports.strenum` package (which backports Python 3.11's `StrEnum` to earlier versions of Python) added a `<3.11` to its `python_requires` in its 1.3.0 release and the conda-forge package reflects this. With `backports.strenum` and `conda-smithy` both being `noarch` packages, this means that you can either install `conda-smithy` with `python>=3.11 strenum.backports<1.3` or `python<=3.10 strenum.backports>=1.3`. In my experience, a clean install of `conda-smithy` into a new conda environment holds Python back (but maybe it is more common to install conda-smithy in a base environment that already has a newer Python? I didn't test that).

Should anything be done about this here or in the `conda-smithy` feedstock? Options I see:

* Make conda-smithy not `noarch` and make `backports.strenum` only a dependency for Python <=3.10 (probably not preferred)
* Pin `backports.strenum <1.3` in the conda-smithy feedstock so the Python version is not capped by it (giving up whatever bug fixes could come; there is no change log for the package to tell easily what is has been fixed in 1.3;  I see lots of churn around packaging and type annotations in the git log but nothing stands out as a bug fix).
* Vendor in the `StrEnum` class and drop the dependency (again giving up any future bug fixes from upstream)
* Remove the Python upper bound from the `backports.strenum` feedstock. It is harmless to install it with newer Pythons, just unnecessary. I have seen other compromises like this in the conda-forge ecosystem (like including a Windows-only pure-Python dependency unconditionally in a `noarch` package).
* Do nothing until dropping support for Python 3.10 when `backports.strenum` can be dropped as a dependency.

**Comment by hmaarrfk** [comment]
Hmm, i think this https://github.com/conda-forge/backports.strenum-feedstock/pull/4 was supposed to fix things, but it seems the build catastrophically failed.

**Comment by hmaarrfk** [comment]
can you try again in 2 hours or so. the CDNs need to sync. but there should now be a dummy package `backports.strenum` that should get pulled in when you install python 3.12+

**Comment by wshanks** [comment]
Thanks, @hmaarrfk! I see the new packages on anaconda.org, so I will optimistically close this now and check again after they reach the CDN.
