### ISSUE TITLE
what is the workflow for running a feedstock

### ISSUE THREAD

**Issue by janschulz** [conda-forge/conda-smithy#22]
I'm currently trying to understand how to run a "feedstock" for the irkernel packages (three or four repos -> https://github.com/IRkernel/irkernel.github.io/issues/16):

I don't want to lose the ability to run travis tests on github ("travis is green" -> merge the PR), but it seems that integrating the conda-smithy files in the main repos will use travis as a macosx builder and not as a testing mechanism on linux? I also don't want to have a package upload for all commits, only for some tags.

If I use a different repo (`irkernel-smithy` -> much like staged-recipes), but AFAIK every time I push into that repo, a build is attempted for all packages. So my current thinking is adding a small file which only contains the repo which should be built and maybe a tag and let the other configs figure out to use that to only build that one repo and upload to a conda channel ([and to our own r repo](irkernel.github.io)). Every time I want a tag build and pushed to the repos, I would change that file and trigger a build in that `irkernel-smithy` repo.

Is this the right way or do I misunderstand the idea behind conda-smithy?

**Comment by pelson** [comment]
Hi @JanSchulz,

> I don't want to lose the ability to run travis tests on github

Within which repo? The feedstock concept has separated the source repo from the distribution building repo for this reason - we want to make use of the CI tools for building, but we don't want them to be built for *each* PR (that would be continuous development, and whilst is possible with conda-smithy, is certainly not the most common use case).

> it seems that integrating the conda-smithy files in the main repos will use travis as a macosx builder and not as a testing mechanism on linux?

That's right. It is possible to extend the Jinja2 template to do this though, should you wish to.

> I also don't want to have a package upload for all commits, only for some tags.

Agreed.

> If I use a different repo (irkernel-smithy -> much like staged-recipes), but AFAIK every time I push into that repo, a build is attempted for all packages.

Technically this is done using Obvious-CI, and so a build only occurs for distributions which aren't already on your anaconda.org channel.

>  So my current thinking is adding a small file which only contains the repo which should be built and maybe a tag and let the other configs figure out to use that to only build that one repo and upload to a conda channel.

Sounds just like a feedstock, so I think we are on the same wavelength.

> Is this the right way or do I misunderstand the idea behind conda-smithy?

The idea is still fairly loosely formed, but in principle conda-smithy just does boilerplate to set up a repo which can build a single conda-recipe for all OSes (aka a feedstock). Currently I have no intention for conda-smithy to be used for anything other than that purpose - the aim is purely to reduce redundancy (particularly with regards to the CI setup scripts) between feedstocks.

> upload to a conda channel (and to our own r repo)

Sounds awesome. The conda-forge organisation is not Python specific, and the aim is to build a set of community trusted conda distributions. You'd be welcome to manage the R recipes within repos within conda-forge, if you wanted to.

**Comment by JanSchulz** [comment]
Ok, so this is the right layout?

```
source-repo 1-x
* Travis to run the unittests

smithy
* recipes 1-x to install the apps from source-repo 1-x as a conda package
```

So how do I trigger the the build in the smithy? It's done for each push to the repo, but then I would build all packages from all the source-repos, which are probably unnecessary if I only want to have releases build and only the one which I recently tagged in one of the source-repos. 

Is there already a inbuilt way to do that and if not: is there a way you would prefer to do that?

**Comment by pelson** [comment]
I'm not 100% I've understood correctly. The aim of conda-smithy is as a tool to help construct feedstocks. The feedstock concept maps exactly 1 conda recipe to 1 git repository - any changes to a recipe (the feedstock) will result in a CI loop which builds all of the permutations of that recipe that the feedstock defines.

Would you be able to point me at the recipes that you have currently - I think the context would help here.

Thanks!

**Comment by JanSchulz** [comment]
Ok, I want to use it as "on smithy, multiple source repos". I don't want to mirror the whole repo layout for a multi-repo-project. An example would be the rkernel, which currently consists of 3 repos: irkernel, repr and irdisplay. There is also a external dependency rzmq, which requires a c compiler. All three/four projects build one r package each, which I would like to both build as a r package and upload to our github pages (that's not my problem here) and to a conda repo. 

So this is more in line with your https://github.com/conda-forge/staged-recipes repo, which as far as I can tell will build all repos, even if you only want one of the packages built?

**Comment by pelson** [comment]
> which as far as I can tell will build all repos, even if you only want one of the packages built?

Not sure how visible the logs are, but that is not the case. ObviousCI is checking anaconda.org to figure out which distributions already exist. It will then only build those that are missing, and upload those to anaconda.org if an appropriate upload token is provided. The concept of having one repo many recipes is tried and tested in https://github.com/SciTools/conda-recipes-scitools, https://github.com/SciTools/conda-recipes-scitools, https://github.com/pyoceans/conda-recipes-pyoceans and https://github.com/conda-forge/staged-recipes - it works, but I don't believe it to be a great abstraction. It is akin to writing a complex package which has full test coverage, but only running the tests for the things you changed. The concept is certainly not that of a feedstock - the raison d'être of conda-smithy is to reduce the burden of managing N git repos each containing a single recipe.

**Comment by pelson** [comment]
I think we can close this issue.
