### ISSUE TITLE
v1.0 release

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-smithy#222]
A few reminders:

 - [x] update the conda-smithy-feedstock!
 - [x] redeploy conda-forge-maint (so that it has the latest conda-smithy)
 - [x] we can now merge https://github.com/conda-forge/staged-recipes/pull/749 (setuptools)
 - [x] check the TravisCI flag is set for all feedstocks https://github.com/conda-forge/conda-smithy/pull/206#issuecomment-231151430
 - [x] merge https://github.com/conda-forge/staged-recipes/pull/754
 - [x] merge https://github.com/conda-forge/staged-recipes/pull/864
 - [ ] handle https://github.com/conda-forge/conda-smithy/issues/176
 - [x] Merge https://github.com/conda-forge/staged-recipes/pull/656 (conda; ~~conda-env~~ broken out, see below)
 - [x] Merge https://github.com/conda-forge/staged-recipes/pull/1064 (conda-env)

**Comment by pelson** [comment]
Just as a heads up @ocefpaf and @jakirkham - I'm a little nervous of doing this today. I have a presentation to start(!) and am on a long haul flight tomorrow. However, one option is to disable the MNT job which updates the existing feedstocks until I have a good run at the problem (Saturday the 16th, depending on sprint demand).

**Comment by ocefpaf** [comment]
:+1:

**Comment by jakirkham** [comment]
👍 Any thoughts on doing a beta tag and not putting that all the way through? We can build that ourselves and try it a few places to see how it goes.

**Comment by jakirkham** [comment]
I tacked on this issue ( https://github.com/conda-forge/conda-smithy/issues/176 ), which is already on the 1.0 milestone and added the `pip` PR ( https://github.com/conda-forge/staged-recipes/pull/864 ).

**Comment by pelson** [comment]
> Any thoughts on doing a beta tag and not putting that all the way through? We can build that ourselves and try it a few places to see how it goes.

Let's release it but disable the MNT PRs for now. At least then we will get new feedstocks in a form that we can test out the newest release...

**Comment by jakirkham** [comment]
> check the TravisCI flag is set for all feedstocks https://github.com/conda-forge/conda-smithy/pull/206#issuecomment-231151430

I'm checking this one off as I have gone back with `conda-smithy` version `1.0.1` and enabled this flag. See this [comment]( https://github.com/conda-forge/conda-smithy/pull/206#issuecomment-233802194 ) and the following one for more details.

**Comment by jakirkham** [comment]
Also, broke apart the `conda` and `conda-env` items as they were separated into 2 PRs. One is accepted. Have also checked off all other done items.

**Comment by jakirkham** [comment]
Checked off the `conda` PR as that has been merged.

**Comment by pelson** [comment]
I think we are good to close this at this point.
