### ISSUE TITLE
skip on "not win": "no build" icon not shown for OSX and circle.yml not removed

### ISSUE THREAD

**Issue by janschulz** [conda-forge/conda-smithy#226]
The inkscape feedstock skips on `not win`, but only Linux is shown as "no build": https://github.com/conda-forge/inkscape-feedstock

On the other hand, the travis.yml file is gone, but not the circle.yml file.

**Comment by jakirkham** [comment]
So, CircleCI doesn't work the same way that Travis CI does. If you don't include `circle.yml`, then CircleCI assumes how to do a CI build for you. It is trying to be the hands-off CI. So, instead we have to add a [few lines]( https://github.com/conda-forge/inkscape-feedstock/blob/dd0eebc52a8df5e4585e62d59fc4a925a935a9d8/circle.yml#L1-L4 ) to the top that says skip builds on all branches. If you look at the CI, you can see [they]( https://circleci.com/gh/conda-forge/inkscape-feedstock ) were all skipped.

We discussed changing the build logos for Windows some time back in this issue ( https://github.com/conda-forge/conda-smithy/issues/119 ). I think everyone likes the idea. Just we never agreed on what to change it to per se (though that is easy enough to change) and no one got around to doing it. I don't think it will be bad to do. I might take it on in a few days.

**Comment by janschulz** [comment]
Notice in this case the recipe is windows only :-)

**Comment by janschulz** [comment]
Ok, the above explains the existing circle.yml, but not this:

![2016-07-14_201447](https://cloud.githubusercontent.com/assets/890156/16850548/f5ae2d02-49ff-11e6-8bee-e9cd9108d69c.png)

-> OSX should also show "no build"

**Comment by jakirkham** [comment]
Well, that's really up to Travis CI ATM. They chose to use "unknown" for their badge. I suppose an issue can be raised on their [issue tracker]( http://github.com/travis-ci/travis-ci/issues ). If you look at the [queue]( https://travis-ci.org/conda-forge/inkscape-feedstock/builds ), there are no Travis CI builds. The AppVeyor situation is worse as they simply have no badge when skipped. Though these are no longer questions of whether they are skipped correctly and just questions of how we represent that.

Now we can opt to replace these badges during re-rendering by something less confusing, which is the point of issue ( https://github.com/conda-forge/conda-smithy/issues/119 ). Generally I am supportive of this. Though if that is the only point still to discuss I'd like to close this so we can keep that discussion in issue  ( https://github.com/conda-forge/conda-smithy/issues/119 ).

**Comment by janschulz** [comment]
Ah, I thought I saw that this was already fixed and assumed that this was the result :-) So I think #119 is the right thing and nothing needs to be done here.

**Comment by jakirkham** [comment]
Thanks @janschulz. No worries. I got hung up with Travis CI API issues when I was implementing these CI skips. So, I didn't dig into UI issues. Though it seems like a perfectly reasonable thing to do and should not be difficult.
