### ISSUE TITLE
broaden to other package managers?

### ISSUE THREAD

**Issue by janschulz** [conda-forge/conda-smithy#23]
Before I try this: would you be interested to broaden the purpose of conda-smithy to "build-smith" and make it possible to plug in different built scripts for different package managers?

* wheels for PyPI
* R packages uploaded to a github repo? (needs some housekeeping task which builds the index)

**Comment by JanSchulz** [comment]
Ok, for this to make sense, a `conda wheel-build` is needed. Not sure how easy that is to build...

Would need to:

* setup a repo like `conda build` (e.g. parse meta.yml and install the dependencies)
* unpack/prepare a source directory
* call a `wheel_build.sh|wheel_bld.bat` file, which does the real build
* copy the wheel to a common dir...

This way one could use a common `base_bld.bat` file and the conda and wheel builds could call this and then just do a `python setup.py install` vs `... bdist_wheel`.

Uploads could be done via twine (importing something from twine would probably also get around the problem that twine needs a password on the commandline...)

**Comment by JanSchulz** [comment]
Ok, the above is now in https://github.com/JanSchulz/conda-build-wheel

-> For my statsmodels recipe, I can build the wheel by simply pointing it at the current recipe: `conda buildwheel statsmodels`. In this case it works as the bld.bat is a simple `python setup install`, so I just create a bld_wheel.bat which calls `python setup.py bdist_wheel`. For other case you would need to duplicate the preparations...

**Comment by pelson** [comment]
Some really interesting ideas here, but I don't think we should pollute conda-smithy at this stage of its life. Right now, the primary focus is on delivering conda-forge - whilst I'd be super keen to help with other package mangers in the future (possibly, but not necessarily, in conda-smithy), I'm also going to maintain focus on completing conda-forge successfully.
