### ISSUE TITLE
binstar package is deprecated

### ISSUE THREAD

**Issue by janschulz** [conda-forge/conda-smithy#24]
That's at least what it tells me when I install it via conda.

The replacement for the binstar command in the templates seems to be `anaconda auth --create --name WhateverName --scopes "repos conda api"`. Without the `api` bit I couldn't get it to run :-(

**Comment by JanSchulz** [comment]
It seems that it's also better to switch all URLs from binstar.org to anaconda.org (https://twitter.com/quasiben/status/657304020210466816). Currently binstar.org is down but anaconda.org is up (again).

**Comment by ericdill** [comment]
Thanks for pinging me on this @JanSchulz .  I'll use the same scopes since you've already done some testing to figure this out :smile:

**Comment by pelson** [comment]
I seem to remember addressing this issue some time ago. Happy to re-open if I've missed something.

:+1:
