### ISSUE TITLE
Download issue?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#241]
Re-render can fail if we are not able to download from a specified channel for any reason. Ideally we shouldn't care about downloads as we are merely trying to parse the `meta.yaml`. It would be good if we could set some sort of offline mode for `conda-build` when parsing at a bare minimum. Perhaps there are more elegant solutions though.

```
$ conda smithy rerender
No circle token.  Create a token at https://circleci.com/account/api and
put it in ~/.conda-smithy/circle.token
No appveyor token. Create a token at https://ci.appveyor.com/api-token and
Put one in ~/.conda-smithy/appveyor.token
No anaconda token. Create a token via
  anaconda auth --create --name conda-smithy --scopes "repos conda api"
and put it in ~/.conda-smithy/anaconda.token
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ........HTTPError: 500 Server Error: Internal Server Error for url: https://repo.continuum.io/pkgs/free/noarch/repodata.json.bz2: https://repo.continuum.io/pkgs/free/noarch/
```

cc @msarahan

**Comment by jakirkham** [comment]
I could be missing something here like we actually need to queue the channels for some reason. It would be nice to know what that reason is though and see if there might be some kind of workaround.

**Comment by jakirkham** [comment]
Maybe playing with the arguments to [`get_index`]( https://github.com/conda/conda/blob/4.1.9/conda/api.py#L10-L11 ) would workaround this issue? At least, I expect that is where the problem is [arising]( https://github.com/conda-forge/conda-smithy/blob/v1.0.3/conda_smithy/configure_feedstock.py#L308 ).

**Comment by jakirkham** [comment]
Here is an [example]( https://github.com/conda-forge/waf-feedstock/issues/1 ) of a case where this sort of problem may result in issues. Basically incomplete re-rendering resulted in uploads not working as intended. Ideally we should try to avoid needing to request channel info here. In any event, we should have a failing exit status if re-rendering does not complete.

**Comment by jakirkham** [comment]
FWIW it does seem `conda` itself will exit with an error status in this case. Here is an example.

```
$ conda install sqlite
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .......Error: HTTPError: 500 Server Error: Internal Server Error for url: https://repo.continuum.io/pkgs/free/osx-64/repodata.json.bz2: https://repo.continuum.io/pkgs/free/osx-64/

$ echo $?
1

**Comment by jakirkham** [comment]
I'm guessing this boils down to how we handle matrix versions particularly with `perl` and `r`. Wonder if we could/should look ahead and see if those cases are worth solving. Another thought would be to cache the index so that we don't need to make as many checks against.

**Comment by pelson** [comment]
I'm not sure there is anything we can do here. We need the index in order to be able to figure out what the build matrix should be. I would **love** somebody to sort out the caching of the index in conda though - it is bizarre that 2 calls to conda results in 2 index fetches, even though there appears to be a "cache" concept...

**Comment by jakirkham** [comment]
Yeah, I agree.

Though we should need no more than 3 calls. I believe we are making 5 calls ATM. This is mostly on me at this point as I did add a few more calls by handling different Linux files. Perhaps we can determine how we would like to accomplish this refactor.

**Comment by pelson** [comment]
OK, I'm going to go ahead and close then. Happy to see 5 calls -> 4 (linux, osx, and win 32 + 64).

**Comment by jakirkham** [comment]
Ugh forgot about win32.

**Comment by jakirkham** [comment]
> Happy to see 5 calls -> 4 (linux, osx, and win 32 + 64).

Doing this in PR ( https://github.com/conda-forge/conda-smithy/pull/457 ).

**Comment by jakirkham** [comment]
Closing as PR ( https://github.com/conda-forge/conda-smithy/pull/457 ) went in and actually we now use `conda-build` to render recipes. So this would be something to address in `conda` or `conda-build`.
