### ISSUE TITLE
Error out on missing `example` recipe

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#258]
Not sure how we feel about this, but it is a common problem. Often people move the `example` recipe when creating their own, it would be nice if the linter reminded them to put the `example` back.

There are some other causes for the `example` recipe to be removed, but I think we have mitigated those cases with PR ( https://github.com/conda-forge/staged-recipes/pull/1206 ).

**Comment by pelson** [comment]
This definitely doesn't belong in the linter, but I can see a strong case for having a conda-forge "checklist". The kinds of things would include "example recipe hasn't been moved", "dependencies have been pinned correctly" etc. It could definitely be part of the conda-forge-webservices hook we have for linting.

**Comment by jakirkham** [comment]
Yeah, I agree. This really isn't linter specific. Going to move it to the webservices repo.

**Comment by jakirkham** [comment]
Issue moved to [conda-forge/conda-forge-webservices #41](https://github.com/conda-forge/conda-forge-webservices/issues/41) via [**ZenHub**](https://www.zenhub.com/)
