### ISSUE TITLE
Release for v1.0.4?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#265]
We have added quite a few nice features. A short list is below. Also it has been a month since our last release. It seems like it is time for a new release. Thoughts?

* Fixes for newer `conda-build` releases
* Linter improvements
* The long awaited disabled CI badges
* Removal of the `disabled_appveyor.yml` files
* A workaround ignored CircleCI skips
* Improved instructions for working on feedstocks

**Comment by jakirkham** [comment]
One minor note, it would be nice if we could get PR ( https://github.com/conda-forge/conda-smithy/pull/266 ) into this release too.

**Comment by jakirkham** [comment]
There is a v1.1.0 release out. So closing. Thanks @pelson. 👍

**Comment by pelson** [comment]
No probs. Thanks for the nudge.
