### ISSUE TITLE
Is upload_or_check_non_existence.py needed?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#268]
I'm trying to understand the purpose of [`upload_or_check_non_existence.py`]( https://github.com/conda-forge/conda-smithy/blob/3f49bcea082d55b638f36bef2435b30ff6259c67/conda_smithy/feedstock_content/ci_support/upload_or_check_non_existence.py ). FWICT we may just be better served by setting `anaconda_upload` to `true` in `.condarc`. This will ensure that packages get uploaded. We can configure the token to use when we build. There may be some kinks to work out, but I'd rather spend time doing that than maintaining a nearly identical copy of this functionality in every feedstock.

cc @msarahan @pelson

**Comment by jakirkham** [comment]
One kink that I know of is `conda-build` asks one to login if they don't have a token and have set `anaconda_upload` to `true`. It might be better if this provided a warning that an upload was not possible. Any non-zero exit code would cause erroneous failures in PR builds.

**Comment by jakirkham** [comment]
Should note that it doesn't overwrite a package if it is already uploaded and it doesn't have an exit code in that case either.

**Comment by msarahan** [comment]
I don't fully understand what you're asking here, but if you pass a token with --token to conda build, it's implicitly enabling anaconda_upload.  Maybe this is simpler than you're thinking?

**Comment by jakirkham** [comment]
Indeed that does work. It also properly handles an empty string token by doing nothing.

**Comment by jakirkham** [comment]
However, it doesn't seem to handle multiple channels/users well. Also it doesn't seem to support labels or perhaps I don't know the right syntax.

**Comment by jakirkham** [comment]
Should add it looks like what we are doing in this file is causing us upload problems. See [comment]( https://github.com/Anaconda-Platform/support/issues/60#issuecomment-241792373 ).

**Comment by jakirkham** [comment]
We might need to do something smaller with this script for a bugfix release soon-ish.

**Comment by pelson** [comment]
> I'd rather spend time doing that than maintaining a nearly identical copy of this functionality in every feedstock

FWIW, I'm keen to move this out of each feedstock too - there is an issue somewhere for it, but I can't find it right now. The quickest intermediate step is to put the same script (with modifications) into a common repo (`conda-forge-build-setup`?) from which we can get this functionality. Longer-term I'm definitely interested in whether we can achieve the same functionality with conda-build's upload (when I wrote this, we couldn't) though.

**Comment by jakirkham** [comment]
Yep, moving it out of here as a first step is totally reasonable. I think we should start on that ASAP as we are going to need to start changing that script to resolve issue ( https://github.com/Anaconda-Platform/support/issues/60 ). It seems one of our API calls is making things really slow.

**Comment by jakirkham** [comment]
See issue ( https://github.com/conda-forge/conda-smithy/issues/270 ) on rough description of what resolving these upload issues will entail.

**Comment by jakirkham** [comment]
Can `conda-build` sign the package too? This is functionality we would want if we switch to something like that.

**Comment by pelson** [comment]
We have moved the upload script to the conda-forge-build-setup.
