### ISSUE TITLE
Test failure fudging subdir in `master`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#276]
Appears we are running into a test failure in `master` as evidenced by [build]( https://travis-ci.org/conda-forge/conda-smithy/builds/155249280 ). Would be great if we could sort it out.

```
======================================================================
ERROR: test_metadata_reading (conda_smithy.tests.test_configure_feedstock.Test_fudge_subdir)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/conda-forge/conda-smithy/conda_smithy/tests/test_configure_feedstock.py", line 31, in test_metadata_reading
    meta.parse_again()
  File "/home/travis/conda/lib/python2.7/site-packages/conda_build/metadata.py", line 387, in parse_again
    self.meta = parse(self._get_contents(permit_undefined_jinja), path=self.meta_path)
  File "/home/travis/conda/lib/python2.7/site-packages/conda_build/metadata.py", line 689, in _get_contents
    env.globals.update(context_processor(self, path))
  File "/home/travis/conda/lib/python2.7/site-packages/conda_build/jinja_context.py", line 157, in context_processor
    ctx = get_environ(m=initial_metadata)
  File "/home/travis/conda/lib/python2.7/site-packages/conda_build/environ.py", line 174, in get_dict
    d.update(meta_vars(m))
  File "/home/travis/conda/lib/python2.7/site-packages/conda_build/environ.py", line 274, in meta_vars
    d['PKG_NAME'] = meta.name()
  File "/home/travis/conda/lib/python2.7/site-packages/conda_build/metadata.py", line 453, in name
    sys.exit('Error: package/name missing in: %r' % self.meta_path)
SystemExit: Error: package/name missing in: '/tmp/tmpp_ZDSdrecipe_/meta.yaml'
----------------------------------------------------------------------
Ran 19 tests in 2.768s
FAILED (errors=1)
```

cc @pelson @msarahan

**Comment by pelson** [comment]
Unable to produce locally. Hmmm.

**Comment by pelson** [comment]
Woops. That was an easy one 😄  - it is just because the name isn't defined on a Linux system...

**Comment by jakirkham** [comment]
> ...it is just because the name isn't defined on a Linux system...

Was thinking about that too. Just was confused why that should matter as it seems the test uses [Windows]( https://github.com/conda-forge/conda-smithy/blob/fe01e7e98807b92cb1ae3a93083d077ee68c37c0/conda_smithy/tests/test_configure_feedstock.py#L30 ) or [OS X]( https://github.com/conda-forge/conda-smithy/blob/fe01e7e98807b92cb1ae3a93083d077ee68c37c0/conda_smithy/tests/test_configure_feedstock.py#L34 ), but not Linux. Especially as the error was coming from this [line]( https://github.com/conda-forge/conda-smithy/blob/fe01e7e98807b92cb1ae3a93083d077ee68c37c0/conda_smithy/tests/test_configure_feedstock.py#L31 ) during the Windows test. Is there something I'm missing about how we fudge the OS or how `conda-build` responds to it?

**Comment by pelson** [comment]
But the initial load of the recipe happens on the native system - https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/tests/test_configure_feedstock.py#L30

On my machine (OSX) works, on Travis (Linux) fails. 😉

**Comment by jakirkham** [comment]
All I'm saying is I'd be comfortable with that explanation if it actually failed on that line. The fact that it fails 2 lines later when it should be fudging the OS is a little unnerving to me. Anyways it's not a big deal. The test does seem to work, which does suggest it is fudging the OS correctly eventually.

**Comment by pelson** [comment]
> All I'm saying is I'd be comfortable with that explanation if it actually failed on that line

Ah, I see. Yes, that is unusual. I don't have a good mental model for why that would be the case... presumably the multi-parse pass needs the name to be defined from the get-go. :confused:
