### ISSUE TITLE
Automatically set BINSTAR_TOKEN for new feedstocks?

### ISSUE THREAD

**Issue by scopatz** [conda-forge/conda-smithy#28]
Is there any way to automatically set the `BINSTAR_TOKEN` environment variable on the various CI services, if we have it locally? This could be a pain to manage by hand...

**Comment by pelson** [comment]
:+1:

**Comment by pelson** [comment]
This is done in https://github.com/conda-forge/conda-smithy/pull/33 (specifically https://github.com/conda-forge/conda-smithy/pull/33/files#diff-8666415dcccfaf789819c990341084c8R124 and https://github.com/conda-forge/conda-smithy/pull/33/files#diff-8666415dcccfaf789819c990341084c8R27). A similar activity can be added for AppVeyor (see also http://help.appveyor.com/discussions/questions/1892-encryption-through-api).

**Comment by pelson** [comment]
Finished off in https://github.com/conda-forge/conda-smithy/pull/35.
