### ISSUE TITLE
Upload script fails with conda_build >= 2.0.0

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/conda-smithy#282]
conda build version 2.0.0 changed the call signature of the [`bldpkg_path()` function](https://github.com/conda/conda-build/commit/cd2f45ccc4e984dd1b9ec05b71c4ee3317ff4d23) so that it now takes a second `config` argument.  This breaks the `upload_or_check_non_existence.py` script in conda-smithy, see conda-forge/doctr-feedstock#5.

**Comment by jakirkham** [comment]
Could we do a PR to http://github.com/conda-forge/conda-forge-build-setup-feedstock please? Please ping me to. Will merge ASAP. Happy enough to keep that pinned for the near term until we get this and other issues sorted.

**Comment by jjhelmus** [comment]
This was fixed by #300 and can be closed as far as I am concerned.  Moving to using the `upload_or_check_non_existence.py` script from the **conda-forge-build_setup** package should be tracked in another issue.
