### ISSUE TITLE
1.3.0 release

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/conda-smithy#305]
Now that conda-smithy supports conda-build 2.x can we tag a `v1.3.0` release and get a conda package started building?

* [x] https://github.com/conda-forge/conda-smithy/pull/293
* [x] https://github.com/conda-forge/conda-smithy/pull/301
* [x] https://github.com/conda-forge/conda-smithy/pull/309
* [x] https://github.com/conda-forge/conda-smithy/pull/310
* [x] https://github.com/conda-forge/conda-smithy/pull/311

**Comment by jakirkham** [comment]
Would like to merge PR ( https://github.com/conda-forge/conda-smithy/pull/301 ) first. Though it looks like we may be down to a click of a button on that one.

Would be nice to get PR ( https://github.com/conda-forge/conda-smithy/pull/293 ) in too. Though that one is less urgent.

**Comment by jakirkham** [comment]
Should add there is still a bit of an issue using the included upload script. Please see the closed PR ( https://github.com/conda-forge/conda-smithy/pull/273 ). That got included in `conda-forge-build-setup`, but not here. We would need it included here if we really want to keep using the included script. So either that PR needs to be reopened and merged or PR ( https://github.com/conda-forge/conda-smithy/pull/301 ) needs to be merged.

**Comment by jakirkham** [comment]
The above comment has been resolved as PR ( https://github.com/conda-forge/conda-smithy/pull/301 ) has been merged.

As we still need to handle file cleanup, have put together PR ( https://github.com/conda-forge/conda-smithy/pull/311 ) that borrows heavily from commit ( https://github.com/conda-forge/conda-smithy/pull/193/commits/3e46d10c195cc127b0698a2e8090cefacb2f37ac ), which should go in to this release.

Also as we did include PR ( https://github.com/conda-forge/conda-smithy/pull/293 ), we should include PR ( https://github.com/conda-forge/conda-smithy/pull/309 ), which includes some improvements.

**Comment by jakirkham** [comment]
Edited the OP to have a list of outstanding/resolved issues/PRs. Hope that is ok, @jjhelmus.

**Comment by jakirkham** [comment]
Thoughts on this @pelson? This is a `conda-build` version `2` blocker. If you are too busy, can I merge the remaining PRs and do a release?

**Comment by pelson** [comment]
I'm going to cut a v1.3 this afternoon. It won't have all of the issues / PRs resolved, but it will unlock a few things. I'm happy to create releases for conda-smithy often (and for others to do so as well).

**Comment by jakirkham** [comment]
Thanks @pelson. 😄

**Comment by pelson** [comment]
I was hoping to get to the bottom of the rerendering oddness (https://github.com/conda-forge/conda-smithy/issues/223), but I don't want to let that hold up the release so I will cut it now.

**Comment by jakirkham** [comment]
Me too, but we have had a hard time getting a line on it.

Maybe we can add some code to the re-rendering script to try to catch and raise on generation of PRs that are odd. This would not only help us stop generating bad PRs, but maybe would add some useful info to the log.

**Comment by jakirkham** [comment]
Done. Thanks @pelson. 😄
