### ISSUE TITLE
Get the correct repo name when rerendering from the feedstocks repo

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-smithy#319]
As per https://github.com/conda-forge/python-decorator-feedstock/pull/3 we should not be guessing the repo name (https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/configure_feedstock.py#L422) and should instead be getting this from some other source.

**Comment by jakirkham** [comment]
Maybe add it to `conda-forge.yml` and guess otherwise? Should still work in the base case. Also would provide a setting that we could leverage when handling renaming ( https://github.com/conda-forge/conda-forge.github.io/issues/179 ).

**Comment by jakirkham** [comment]
So I think there is some attempt at a fix in `1.3.1`, but it's not working right.

xref: https://github.com/conda-forge/numpy-feedstock/pull/29#discussion-diff-81435719L73

**Comment by pelson** [comment]
> Does this affect staged-recipes at all?

I don't believe so. The feedstock directory for a staged-recipe comes from https://github.com/conda-forge/staged-recipes/blob/master/.CI/create_feedstocks.py#L148

```
feedstock_dir = os.path.join(feedstocks_dir, name + '-feedstock')
```

> That was a re-rendering from the feedstocks repo. So this is a bad change for my workflow. Could we discuss a better change?

Yes, I'd welcome a better change. We maintain the name of the upstream repo in the feedstocks repo, right? If so, we can use gitpython to inspect that name.

**Comment by jakirkham** [comment]
That seems like a good idea. So check for `conda-forge` in the URL and go from there?

**Comment by jakirkham** [comment]
Should add there are a few other [spots]( https://github.com/conda-forge/conda-smithy/blob/9a254c278479fab17ce0c73fb17630f8e854227f/conda_smithy/cli.py#L154 ) that we could/should do smarter things. Currently this results in [failures]( https://travis-ci.org/conda-forge/staged-recipes/builds/164905851#L288 ) in conversion that are well documented in issue ( https://github.com/conda-forge/staged-recipes/issues/1073 ).

**Comment by jakirkham** [comment]
> Yes, I'd welcome a better change. We maintain the name of the upstream repo in the feedstocks repo, right? If so, we can use gitpython to inspect that name.

So this isn't quite that nice, but PR ( https://github.com/conda-forge/conda-smithy/pull/323 ) does seem to fix the problem for me while still keeping the behavior intended by PR ( https://github.com/conda-forge/conda-smithy/pull/320 ). Given I just need `conda-smithy` to work right now, this is good enough. Please take a look.

**Comment by jakirkham** [comment]
So we have a fix that works with re-rendering and locally, but it is a bit kludgy. Will keep open for a better GitPython-style fix.

**Comment by pelson** [comment]
Let's open something when it is needed. No need to keep noise in the issue tracker - makes it hard to see the 🌳  from the 🌳🌲🌳🌲🌳🌲🌳🌲. 😄
