### ISSUE TITLE
Don't store `BINSTAR_TOKEN` in `conda-forge.yml` to prevent accidental overwrites

### ISSUE THREAD

**Issue by shadowwalkersb** [conda-forge/conda-smithy#328]
Currently, `BINSTAR_TOKEN` is used for authentication(?) in uploads to `conda-forge`. It is stored in `conda-forge.yml` of every feedstock making it part of a recipe. However, the token is not recipe specific and is actually used by the uploading account only. Being part of the feedstock makes it vulnerable to edits, see issue ( https://github.com/conda-forge/freeglut-feedstock/issues/10 ). Per the conversation in the mentioned PR, [here](https://github.com/conda-forge/freeglut-feedstock/issues/10#issuecomment-253410844), [here](https://github.com/conda-forge/freeglut-feedstock/issues/10#issuecomment-253411284) and [here](https://github.com/conda-forge/freeglut-feedstock/issues/10#issuecomment-253412058), proposing to remove `BINSTAR_TOKEN` from `conda-forge.yml`.

It can be stored in a file just like the token files `conda-smithy` reads from locally. It is used only during the upload process. Not familiar with the details of the process, but the file can be stored in the account that uploads.

**Comment by jakirkham** [comment]
So I guess the question is where does it get stored instead? The CIs need to have access to it in order to do the upload. Related how do we update it if it changes? Right now we can edit a file. However, it gets hidden away somewhere, we need to reconsider how to edit it.
