### ISSUE TITLE
No git repo option

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#333]
So `conda-smithy init` provides a `--no-git-repo` option. I'm trying to understand if this option has some actual value for real use cases. If not, I'm wondering if we can simply eliminate it. There's a lot of nifty things we can do if we can guarantee feedstocks are always git repos. However, those nifty things pick up a lot more tedious maintenance if we can't make that guarantee.

**Comment by jakirkham** [comment]
I think we should drop this option with `conda-smithy` 3. Have not heard anyone chime in to say it is used and keeping a superfluous option around doesn't seem like a good idea. Thoughts from others?

**Comment by isuruf** [comment]
+1

**Comment by jakirkham** [comment]
Thanks @isuruf. Went ahead and threw together PR ( https://github.com/conda-forge/conda-smithy/pull/659 ) to get this started. Would appreciate feedback on that PR if you have time.
