### ISSUE TITLE
License for non-conda-forge feedstocks generated with conda-smithy

### ISSUE THREAD

**Issue by shadowwalkersb** [conda-forge/conda-smithy#344]
Currently, the feedstock licenses are copyrighted to [conda-forge](https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/feedstock_content/LICENSE#L1-L3).

`Copyright (c) conda-forge`

Is it appropriate for a feedstock generated for an organization/user other than conda-forge and which is hosted on their own channel? Or, should it be customized?

**Comment by jakirkham** [comment]
Seems reasonable enough to me. Will be a little bit of work to get the jinja right, but if you want to do it, I'd say go for it. Would you like to submit a PR?

**Comment by shadowwalkersb** [comment]
Can't promise anything ATM. But, just wanted to make sure that it is OK to customize.

**Comment by jakirkham** [comment]
I can't speak for others, but for me personally this seems ok.

**Comment by shadowwalkersb** [comment]
When copyrighted to conda-forge, are there any limitations or things to be aware of when using and hosting conda-smithy generated feedstocks somewhere other than conda-forge repos and channels? If no problems, I guess, there is no need to change the current license.

**Comment by jakirkham** [comment]
AFAIK it is just the BSD 3-Clause license.

Going to close this out, but please let us know if this change is still needed and we can reopen.
