### ISSUE TITLE
UnicodeEncodeError during rerender if meta.yaml contains unicode chars [Python2]

### ISSUE THREAD

**Issue by marscher** [conda-forge/conda-smithy#364]
when calling rerender in a feedstock, I get the following error, when my root env is running Python 2.7. Note that I do not have created CI tokens yet, but since the re-render step should not rely on the tokens and is already writing/updating the readme, I'd guess it is a bug.
```
marscher@jigsaw:~/sources/conda-forge/pyemma-feedstock$ conda smithy rerender
No circle token.  Create a token at https://circleci.com/account/api and
put it in ~/.conda-smithy/circle.token
No appveyor token. Create a token at https://ci.appveyor.com/api-token and
Put one in ~/.conda-smithy/appveyor.token
No anaconda token. Create a token via
  anaconda auth --create --name conda-smithy --scopes "repos conda api"
and put it in ~/.conda-smithy/anaconda.token
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...........
Fetching package metadata ...........
Fetching package metadata ...........
Fetching package metadata ...........
Fetching package metadata ...........
Traceback (most recent call last):
  File "/home/marscher/anaconda/bin/conda-smithy", line 6, in <module>
    sys.exit(conda_smithy.cli.main())
  File "/home/marscher/anaconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 289, in main
    args.subcommand_func(args)
  File "/home/marscher/anaconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 200, in __call__
    configure_feedstock.main(args.feedstock_directory)
  File "/home/marscher/anaconda/lib/python2.7/site-packages/conda_smithy/configure_feedstock.py", line 461, in main
    render_README(env, config, forge_dir)
  File "/home/marscher/anaconda/lib/python2.7/site-packages/conda_smithy/configure_feedstock.py", line 204, in render_README
    fh.write(template.render(**forge_config))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 158: ordinal not in range(128)
marscher@jigsaw:~/sources/conda-forge/pyemma-feedstock$ python --version
Python 2.7.12 :: Continuum Analytics, Inc.
```

**Comment by marscher** [comment]
conda-smithy version 1.4.6

**Comment by jakirkham** [comment]
Is this with other feedstocks or just `pyemma`?

**Comment by jakirkham** [comment]
Also does this happen when `root` is Python 3.5 as well? Or is this restricted to Python 2.7?

**Comment by marscher** [comment]
Since conda-smithy can only be installed within the root env, it is restricted to Python-2.7. It seems that it only failed with pyemma-feedstock.

**Comment by marscher** [comment]
Eg. with msmtools-feedstock it works as expected (with py-27)

**Comment by jakirkham** [comment]
> Since conda-smithy can only be installed within the root env, it is restricted to Python-2.7.

Why? One can install Python 3.5 in the `root` environment. Alternatively one can download Miniconda with Python 3.5 in the `root` environment to start with.

**Comment by jakirkham** [comment]
> with msmtools-feedstock it works as expected (with py-27)

Ok, so I guess there is some Unicode character in `pyemma`'s feedstock `meta.yaml` that is causing issues. Admittedly we should still be better at handling it.

**Comment by marscher** [comment]
This is what the error message say, right. I'd guess that writing the file in binary mode should be sufficient to fix this kind of issue

**Comment by marscher** [comment]
I can confirm that this is only happening with Python2, no error on Python3.

**Comment by jakirkham** [comment]
Should be fixed by PR ( https://github.com/conda-forge/conda-smithy/pull/366 ).

**Comment by jakirkham** [comment]
Further improvements for unicode support in the linter provided by PR ( https://github.com/conda-forge/conda-smithy/pull/372 ).
