### ISSUE TITLE
rerender potentially changes file permissions

### ISSUE THREAD

**Issue by grlee77** [conda-forge/conda-smithy#365]
running `conda smithy rerender --commit` on the following feedstock resulted in a number of files becoming executable, that were not previously executable.  The files that underwent the undesired change in permission were: `.gitignore`, `.travis.yaml`, `LICENSE`, `README.md`, `appveyor.yml`, `circle.yml`.

The rerendering was performed from within a folder on an NTFS drive mounted after boot time in linux.  The folder where the drive is mounted is showing the following permissions `drwxr-xr-x` which is what the files seem to have inherited after the rerender.

**Comment by jakirkham** [comment]
The simple fix for this is we explicitly set permissions on all files we create not just those that we wish to change the permissions on. Should be simple enough to do.

**Comment by jakirkham** [comment]
I noticed in PR ( https://github.com/conda-forge/scikit-sparse-feedstock/pull/3 ) that `conda-forge.yml` got execute permissions, but is untouched by re-rendering. Is there something else going on maybe with the filesystem?

**Comment by jakirkham** [comment]
> The folder where the drive is mounted is showing the following permissions `drwxr-xr-x` which is what the files seem to have inherited after the rerender.

Should add this is the normal permission setting for a directory. Execute permissions in particular are required to run `ls` and the like.

**Comment by grlee77** [comment]
For the `scikit-sparse` case I did the rerendering on a different system (macbook with OS X Mavericks), not the one where I had the problem previously. 

I just tried it locally on traitsui-feedstock, though, and could not reproduce the problem.  no file permissions were changed

**Comment by jakirkham** [comment]
So I've tried to address this in PR ( https://github.com/conda-forge/conda-smithy/pull/379 ). However, I must say that I have had a lot of trouble getting the permissions set properly in all cases. TBH I really don't want to go through with it at this point given the issues I have experienced.

Could you please double check that your system was actually reproducibly causing this problem? If not, I'm inclined to note this as a strange case and leave everything alone lest we somehow make this worse for others.

**Comment by grlee77** [comment]
I cannot reproduce on either machine at the moment when I try with some other feedstocks.  I will go ahead and just remember to keep an eye out for it on my end in the future.

**Comment by jakirkham** [comment]
Thanks for rechecking.

**Comment by jakirkham** [comment]
I recently encountered a similar problem and think it has to do with some code we added to change permissions in `git` using blobs. Unfortunately, it appears it can have some unexpected side affects like setting permissions on other files. Fortunately I think I have a fix that at least solved the issue I was encountering locally and hopefully this one.

**Comment by jakirkham** [comment]
So deployed the fix in `1.5.3`. If that still gives you issues, please let me know.
