### ISSUE TITLE
Add a switch to build a multiple recipe forge

### ISSUE THREAD

**Issue by janschulz** [conda-forge/conda-smithy#37]
For one project, having an (or a few) additional repo(s) for the conda builds is fine. But for things like https://twitter.com/wesmckinn/status/685537127199723523 (+answers...) I think having this layout will lead to hundreds of repos and I think that this a bad idea: you lose overview, it's a lot of work to update passwords or the smithy code itself. And getting bugs assigned to the right repo is a pain (the current ipython problem after the big split). 

I would like to propose that conda-smithy gets a switch to build such a multiple recipe forge. I could do the work on this (IMO it's "just" some conditionals in the templates + small code changes in the generation to trigger these conditionals).

Would you take such a PR?

**Comment by pelson** [comment]
I have been considering this too. I confess, I'm still not sure that it is a good model to use, but I can certainly see the pragmatic reasons for what you say. My approach so far has been - "push as far as I can, and then concede pragmatically when pinch points reveal themselves". With that in mind - I wouldn't *yet* merge such a PR, but I may very well do in a few months time. My energy at the moment though will be focussing on smoothing of the process to try to avoid the multiple recipes in a repo concept.

At the very worst, we will always have the option of using staged-recipes for the very small packages...

**Comment by JanSchulz** [comment]
Reading [this](https://github.com/conda-forge/conda-smithy/pull/41#issuecomment-170525210) I wonder if it wouldn't be easier to switch the whole thing over to multiple recipe per feedstock on default:

You can still work with one recipe per feedstock, the only "bad" thing would be that you have to look in `recipe/whatever` instead `recipe` for the conda recipe.

**Comment by jjhelmus** [comment]
I'm been thinking about this same idea on and off for a while but did not know the best place to discuss this, why not here!  Originally I though the one repository per recipe ideas was a good model, but then I realized how difficult it would be to manage 100's of recipes in this manner.  I've had two ideas that might be worth considering that I would love to hear your opinions of.

**A single repository with one branch per recipe.**  

This makes maintenance easier as you only need to monitor a single repository for contributions, bugs, updates to tokens, etc. New recipes would be a branch from master which is then merged into the non-master branch (does GitHub allow this).  The one downside is that it is a bit difficult to see what recipes are already available as these are branches and not a folder list.  I tried this out idea a bit in [jjhelmus/hearth](https://github.com/jjhelmus/hearth).


**A single repository and branch with declarative builds.**

The idea here would be to have a single repository which holds recipes which may or may not be built and use a .yml or other file to declare to the CI scripts which recipe or recipes should be built for a given pull request.  All builds would need to update  this .yml files (or remove it when nothing is to be built) which may results in merge conflicts that would require re-basing.  In general I think PRs in this method would be a bit more involved.  Building against new versions of Python, NumPy or new platforms would be easier as these could be specified in the .yml file.  The other benefit, I see of this setup is that the recipes can be de-coupled from the build repository, in fact the recipes folder could be a git submodule (conda/conda-recipes?) with updates building a recipe or two at a time.  I'm hoping to try this out with some packages I need to build personally.

**Comment by JanSchulz** [comment]
@jjhelmus Here is a bit more discussion about this issue: https://github.com/conda-forge/conda-smithy/pull/51#issuecomment-181910644

**Comment by pelson** [comment]
> A single repository with one branch per recipe.

Technically, there is nothing stopping one doing this already with a conda-forge feedstock. This will be a real option when it comes to meta-packages I think, but hopefully it is clear that at the moment, it would be frowned upon to produce packages with different names from a single feedstock. I have discussed this option before with @ericdill as a way of managing multiple versions of the same package in a single feedstock, and in principle I'm :+1: on it.

> A single repository and branch with declarative builds.

conda-build-all can just inspect a channel to figure out what needs building - no need for the declaration. The submodules option would work for repositories such as IOOS and does give you separation of concerns at the cost of having to update 2 repositories (that's submodules for you).

> I'm hoping to try this out with some packages I need to build personally.

You're welcome to submit to conda-forge/staged-recipes and become a maintainer of the recipes you propose... :wink:

**Comment by pelson** [comment]
For now, I'm going to close this issue. We all know the details of multiple-recipes in a single repo, and for now, I'm comfortable with the 1-package 1-repo model (issues such as submitting PRs to every single feedstock have been addressed through automation).

Again, there may be pragmatic reasons we need to do this in the future, but for the time being, the decentralised maintenance model is bearing fruit.

Thanks!
