### ISSUE TITLE
Python 3.5 packages contain extra .pyc files

### ISSUE THREAD

**Issue by aburgm** [conda-forge/conda-smithy#373]
Several python 3.5 conda packages such as pandas and pytz contain unrelated .pyc files in `__pycache__` directories, e.g. for pkg_resourecs, setuptools or Cython. See for example:

https://anaconda.org/conda-forge/pandas/0.19.1/download/win-64/pandas-0.19.1-np111py35_0.tar.bz2
https://anaconda.org/conda-forge/pytz/2016.7/download/win-64/pytz-2016.7-py35_0.tar.bz2

The python 3.4 versions don't contain these extra files:

https://anaconda.org/conda-forge/pandas/0.19.1/download/win-64/pandas-0.19.1-np111py34_0.tar.bz2
https://anaconda.org/conda-forge/pytz/2016.7/download/win-64/pytz-2016.7-py34_0.tar.bz2

This issue is not specific to Windows, it also happens on Linux and Mac OS X.

**Comment by aburgm** [comment]
This seems related: https://github.com/conda/conda-build/issues/718

**Comment by jakirkham** [comment]
I completely agree that this is an issue (and a quite annoying one). Have run into a few times myself.

However, as you have pointed out this is an upstream issue. As this is not related to `conda-smithy`, I'm going to close this out.

**Comment by aburgm** [comment]
@jakirkham Did you read [ilanschnell's comment](https://github.com/conda/conda-build/issues/718#issuecomment-226167430) on that upstream bug report? It seems unclear that it is actually an upstream issue and might instead be an issue in the recipe or the recipe of dependencies.

An issue that I think is related is that in the py3.4 version of the above mentioned packages, the .pyc files are stored inside a `__pycache__` directory, which is correct. In the py3.5 version, however, the .pyc files are stored right next to the .py files, which is not where python expects them.

**Comment by aburgm** [comment]
With which conda-build version have these packages been built? That second issue seems to have been fixed somewhere between conda-build 2.0.0 and 2.0.8.

Could it be that those packages and maybe some of their dependencies just have to be rebuilt with more recent conda-build versions?

**Comment by jakirkham** [comment]
I think you are referring to PR ( https://github.com/conda/conda-build/pull/1304 ). Yes, that fixed part of the problem.

**Comment by jakirkham** [comment]
We are currently stuck on `conda-build` 1. So everything is built with that at present.

**Comment by aburgm** [comment]
Oh, I guess that explains it. Thanks. Looking forward to conda-build 2 builds then...

**Comment by jakirkham** [comment]
So that only helps part of it. I did try building with both locally and still found it compiling pieces of dependencies. In particular, I tried with `pytz`.

The best thing I can find is @marscher 's suggestion, which basically amounts doing `python -B setup.py install  --single-version-externally-managed --record=record.txt`. This seems to keep the other dependencies out.

In any event, this is the sort of issue that is best raised on the [webpage repo]( https://github.com/conda-forge/conda-forge.github.io/ ) as it is a org wide issue. `conda-smithy` is more for issues with how the CIs on the feedstocks work and the like. Would you like to do that?

**Comment by aburgm** [comment]
pytz however has dependencies on setuptools, and if that package is missing `__pycache__` directories, then they will end up in the pytz build as they get created during execution of setup.py. I would expect that if you start building things with conda-build 2 from the very bottom of the stack, the issue should disappear.

Sure, I'll open an issue on the webpage repo.

**Comment by jakirkham** [comment]
FWICT with the [`-B`]( https://docs.python.org/3/using/cmdline.html#cmdoption-B ) experiment. That does not seem to be the case. This may in fact be a sufficient solution to the problem. It just will take a bit of work to roll out.

**Comment by aburgm** [comment]
The -B only solves the symptom, though, not the root of the problem? For instance, if you build a package this way with conda-build 1, it does not have the superfluous `__pycache__` directories anymore, but it still generates `.pyc` files in the wrong place for the actual package that is supposed to be packaged.

**Comment by marscher** [comment]
If you do not want to upgrade to conda-build 2.x yet, the workaround of calling python with -B option is valuable. But all the feedstocks would have to be
re-rendered right?
