### ISSUE TITLE
Conda smithy package should update conda-build-all

### ISSUE THREAD

**Issue by rolando** [conda-forge/conda-smithy#375]
I've got this error when trying to run `conda smithy regenerate`:

```
/Users/rolando/miniconda3/lib/python3.5/site-packages/conda_build_all/resolved_distribution.py in setup_vn_mtx_case(case)
     20 def setup_vn_mtx_case(case):
---> 21     orig_npy = conda_build.config.config.CONDA_NPY
     22     orig_py = conda_build.config.config.CONDA_PY
     23     orig_r = conda_build.config.config.CONDA_R

AttributeError: module 'conda_build.config' has no attribute 'config'
```

I've updated `conda`, `conda-build`, `conda-smithy` and the issue was gone after updating `conda-build-all`.

I had an old conda-build-all package:

```
The following packages will be UPDATED:

     conda-build-all: 0.13.1-py35_0 conda-forge --> 1.0.0-py35_0 conda-forge
```

**Comment by jakirkham** [comment]
cc @jakevdp

**Comment by jakirkham** [comment]
Yeah, this is an issue with `conda-build` version `2.0.x` compatibility. While it is not strictly a requirement to have `conda-build-all` version `1.0.0` with newer `conda-smithy`'s, it may be time to just pin `conda-build-all` in the recipe to `1.0.0` to avoid confusion. This is not the first time this has come up.

**Comment by whart222** [comment]
FWIW, I also just ran into this issue.

**Comment by rolando** [comment]
It's a bummer that `conda-build-all` (of any conda command for that matter) has to be installed in the `root` environment.

If you happen to use `conda-build-all` `2.x` for your own recipes then you will have to downgrade in order to run `conda smithy regenerate`. Granted that this affects only to feedstock maintainers.

**Comment by jakirkham** [comment]
One doesn't need to downgrade `conda-build`. Just upgrade `conda-build-all` and things should work fine.

**Comment by rolando** [comment]
@jakirkham oh, I mixed things up between `conda-build` and `conda-build-all` versions. Thank you for the clarification.
