### ISSUE TITLE
Conda smithy requires v4.2+

### ISSUE THREAD

**Issue by scopatz** [conda-forge/conda-smithy#381]
Currently, if you try to run conda-smithy with <= v4.1.12, you'll see the following error.

```console
scopatz@artemis ~/re2-feedstock fixes $ conda smithy rerender
Traceback (most recent call last):
  File "/home/scopatz/miniconda3/bin/conda-smithy", line 4, in <module>
    import conda_smithy.cli
  File "/home/scopatz/miniconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 10, in <module>
    from conda_build.metadata import MetaData
  File "/home/scopatz/miniconda3/lib/python3.5/site-packages/conda_build/metadata.py", line 9, in <module>
    from .conda_interface import iteritems, PY3, text_type
  File "/home/scopatz/miniconda3/lib/python3.5/site-packages/conda_build/conda_interface.py", line 27, in <module>
    from conda.base.constants import SEARCH_PATH
ImportError: No module named 'conda.base'
```

This is because the base subpackage is new in v4.2

**Comment by jakirkham** [comment]
Could you please include the results of `conda info`?

**Comment by jakirkham** [comment]
I suspect this is some incompatibility between `conda` version `4.1.12` and `conda-build` version `2.0.9` as it did not exists with `conda-build` version `2.0.8`. However, would need that info to confirm that is what happened in this case. Thoughts on this @msarahan ?

**Comment by jakirkham** [comment]
In particular, this [line]( https://github.com/conda/conda-build/compare/2.0.8...2.0.9#diff-ba343c116f2df712f571a28c16577543R19 ) seems to cause the problem.

**Comment by jakirkham** [comment]
In particular, this [line]( https://github.com/conda/conda-build/compare/2.0.8...2.0.9#diff-6d8cb4644da89eaf24a8c9617a738d55R27 ) causes the problem.

**Comment by jakirkham** [comment]
Have opened this issue ( https://github.com/conda/conda-build/issues/1527 ) upstream. At present, one must use `conda-build` version `2.0.8` or lower with `conda` version `4.1.x`. Alternatively, one must use `conda` version `4.2.x`. Will try at least to get `conda-build` pulled or hot-fixed if possible.

**Comment by jakirkham** [comment]
So I can try to fix the `conda-smithy` package in a build number bump to avoid `conda-build` version `2.0.9`. However, `conda` may simply wriggle free from this version constraint by picking a lower version of `conda-smithy` that allows for a newer version of `conda-build`. Maybe making a new release of `conda-smithy` would not result in the same issue. Not sure.

**Comment by jakirkham** [comment]
Have resolved this by making a `conda-smithy` version `1.5.2` release which excludes `conda-build` version `2.0.9`. That appears to correctly downgrade `conda-build` when installed. Though there may be cases where this breaks like `conda update --all`. In any event, that is all we can do to address this at present. So am considering this resolved and am closing it.
