### ISSUE TITLE
conda smithy 1.6.1 rerender does not notice numpy 

### ISSUE THREAD

**Issue by tacaswell** [conda-forge/conda-smithy#397]
See https://github.com/conda-forge/matplotlib-feedstock/pull/81 and my attempts to get this working. 

A previous version of conda-smithy did bad things to the mpl feedstock, is there something wrong with the recipe metadata?

**Comment by jakirkham** [comment]
Expect this is likely a product of using the user's `.condarc` instead of overriding it with `conda-smithy`. As such, am consolidating this into issue ( https://github.com/conda-forge/conda-smithy/issues/387 ). If after solving that issue this persists, we can revisit.

**Comment by tacaswell** [comment]
Indeed:

```
envs_dirs:
  - /home/tcaswell/.virtualenvs/

channels:
#  - tacaswell
  # - danielballan
  # - asmeurer
 # - pkgw
  - defaults
show_channel_urls: True
binstar_upload: yes

```

is the contents of my `.condarc`

**Comment by jakirkham** [comment]
Thanks for the info. Was helpful for testing things out.

Just put together PR ( https://github.com/conda-forge/conda-smithy/pull/401 ), which seems like it should fix the issue. Would be curious to hear how it plays out for you.
