### ISSUE TITLE
Revisiting Perl

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#415]
We recently added a new version Perl. As I recently experienced while doing some testing, this going to start resulting in matrices of Perl. Am opening this issue to discuss how we want to deal with this. Do we wish to constrain the Perl versions used at `conda-forge`? Should we start pinning the version? Do we just wish to tweak `conda-smithy`'s lower bound on Perl?

**Comment by jakirkham** [comment]
@msarahan, do you have any ideas on this?

**Comment by ericdill** [comment]
tl;dr from the dev meeting: Fixing this is going to require tweaking the conda-smithy matrix generation. Since conda-build 3 is going to change behavior, the matrix generation code is going to require a rewrite. The suggestion from the dev meeting is to wait until conda-build 3 lands so that we don't have to rewrite the matrix generation code twice

**Comment by mingwandroid** [comment]
I've updated Perl to 5.26.0 in a fork of the conda-forge recipe. Sure there are knock-ons around @INC changes (nothing some simple patching doesn't fix though).

Can you show me what fails? I don't understand the need to pin Perl so exactly, esp. when it's just indeed as a build dependency to run some script or other (eg openssl's Configure).

**Comment by isuruf** [comment]
@mingwandroid, `conda-build-all` will create a matrix of builds for each perl version just like it does for each python version. But when perl is needed only as a build dependency, there is no use for this matrix of perl versions.

**Comment by jakirkham** [comment]
Though the only reason `conda-build-all` does that at all is `conda-build` had hardcoded some old version of `perl`, which never existed in `conda-forge`. We had discussed fixing `conda-build` some time ago, but we only had one `perl` version for a long time. So `conda-build-all` just treated `perl` like other matrix determining dependencies instead, which may be ok for `perl` packages. It didn't matter until we got multiple `perl` versions. As @isuruf already noted, this results in needless matrices when `perl` is only a build dependency. Though the same thing happens when `python` is only a build dependency. Hence recipes like `openblas` and `openssl` need to pin `perl` to not create needless builds. What pinning is used in these cases is utterly irrelevant.

**Comment by mingwandroid** [comment]
This means if I update perl to a new version I need to update every recipe that pins perl to the old version.

Can `conda-build-all` not be fixed to not create build matrices based on build requirements? That seems like the correct fix here?

**Comment by isuruf** [comment]
> This means if I update perl to a new version I need to update every recipe that pins perl to the old version.

No. Since the old version is enough for building that recipe (Assuming perl is only a build dependency), there's no need to update that recipe.

**Comment by jakirkham** [comment]
Though I suppose there are questions of how big a range is needed, how tight the pinnings should be, and how many versions do we want to support? Perhaps some `perl` packages can be treated as effectively `noarch` packages and don't need any pinning. As it has been a long time since I have used `perl`, I'm not sure of the answers to these. Hence why this issue exists. 😉 So definitely would like to hear some well-reasoned answers to these that can guide our tooling forward.

**Comment by mingwandroid** [comment]
@isuruf, this contradicts what's being done though, see for example: https://github.com/conda-forge/openssl-feedstock/blame/master/recipe/meta.yaml#L37

Is there any reason for this pinning? Can we make it a policy to not pin perl build requirements when any perl version released so far is equally capable of being used?

**Comment by mingwandroid** [comment]
cc'ing @pmlandwehr.

**Comment by mingwandroid** [comment]
@jakirkham, I don't know enough about perl or perl packages to comment, but specifically I want to discuss only `requirements/build` perl pinning here.

**Comment by isuruf** [comment]
@mingwandroid, I don't see any contradictions there. If `perl=5.20.3.1` is enough for building `openssl`, there's no need to update it to a newer version of perl. Pinning exactly is needed to stop `conda-build-all` from generating a matrix there.

**Comment by mingwandroid** [comment]
No, the result of this pinning is that when you want to update Perl, instead of editing N recipes (where N is the number that pin Perl as a `requirement/run`) you have to edit N+M recipes (where M is the number that (needlessly) pin Perl as a `requirement/build`).

> Pinning exactly is needed to stop conda-build-all from generating a matrix there

This sounds like a bug in `conda-build-all` does it not?

**Comment by isuruf** [comment]
> edit N+M recipes (where M is the number that (needlessly) pin Perl as a requirement/build

Why do these M recipes need to be updated?

> This sounds like a bug in `conda-build-all` does it not?

Yes.

> Can conda-build-all not be fixed to not create build matrices based on build requirements? That seems like the correct fix here?

I agree with this. We also have to consider that `conda-forge` is relying on `python` as a build requirement for different msvc compilers for C/C++ libraries.

**Comment by jakirkham** [comment]
> This sounds like a bug in `conda-build-all` does it not?

I think I missed saying this or it was simply unclear. Sorry for that @mingwandroid. The problem begins with `conda-build`. For a long time it did something really odd like try and install `perl` 5.18.2 (not entirely sure what version) if the version was not specified. So the change added to `conda-build-all` was to combat this behavior in `conda-build`. I'm not sure that we can fix `conda-build-all` unless `conda-build` has rid itself of this bad behavior.

**Comment by jakirkham** [comment]
In any event, I'm really cautious about doing anything with the `perl` situation since none of us really uses it that much. I'd really like us to draw on knowledge from those that already use `perl` with `conda` extensively . Would be good if some bioconda people could advise us on what would be the right thing to do with `perl` would be. We can then discuss special cases like `perl` as a `build`-only dependency. Though as @isuruf notes this situation is similar to `python` as a `build`-only dependency, which also is quite strange and requires different hacks.

cc @johanneskoester @bgruening

**Comment by mingwandroid** [comment]
conda-build's perl version preference can be overridden by setting the `CONDA_PERL` env var (though we're moving away from those altogether in conda-build 3).

**Comment by jakirkham** [comment]
Right, which is what `conda-build-all`/`conda-smithy` started doing to workaround this issue. This was a non-issue while we had only one `perl` version. Once we needed to add multiple `perl` versions to help out bioconda, we started getting matrices of `perl` versions where we did not need them. Hence we find ourselves with this weird pinning situation with `perl`. FWIW I don't like it either am just unclear on how we can fix it without a change in `conda-build` that yields smarter behavior (i.e. not fixing the `perl` version at all). Is this possible in `conda-build` 3?

**Comment by mingwandroid** [comment]
Yeah, conda-build 3 has comprehensive build matrix and pinning specification capabilities. It's on defaults now. Pinging @msarahan.

**Comment by jakirkham** [comment]
Cool. So I guess instead of trying to fix `conda-build-all`, which we would like to phase out and replace with `conda-build` 3, maybe it is better for us to work out what `perl` should look like in a new version of `conda-smithy` and `staged-recipes` that use `conda-build` 3.

**Comment by bgruening** [comment]
I agree completely with your last comment @jakirkham. Let's wait for conda-build 3 and pick useful version(s) for perl. Bioconda will then follow and try to use the exact same pinning schema.

**Comment by pmlandwehr** [comment]
Appreciate the cc into this thread, but I'm not sure I have much to add here - my only concern for the recipe is that there's a version of `perl` available to match the pin required at the build. As long as `conda-build` lets me pin a particular version of perl in the recipe's build environment, I think I'm happy enough. The number of build matrices this entails is something I've been able to leave upstream for y'all, and that still seems like the right move.

**Comment by scopatz** [comment]
It would be nice to document this somewhere.

**Comment by jakirkham** [comment]
I guess the problem is we really don't know what to say about this issue other than it is one and there is a workaround. Is that the advice that you would like to see in the docs or did you have something else in mind? Happy to be advised on this issue given I'm not an avid Perl user. :)

**Comment by minrk** [comment]
We just ran into an unwanted perl matrix in https://github.com/conda-forge/openmpi-feedstock/pull/18. Since perl is only a build dependency, it shouldn't produce a matrix, should it? Only if it's *both* a build and runtime dependency? I'm guessing it's not worth fixing now, as this will all change with conda-build 3.

**Comment by jakirkham** [comment]
Yeah, unfortunately. The current recommendation is to pin `perl` to an exact version.

**Comment by jakirkham** [comment]
It appears this issue does not persist in `conda-smithy` 3 RC. ( https://github.com/conda-forge/openmpi-feedstock/pull/19 ) We provide [some guidance on constraining `perl`]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/2999590b6fbdd908dac5a6f85f79b25c43b33bf4/recipe/conda_build_config.yaml#L173-L174 ). However changing to an older version for `perl` has the same outcome. IOW this issue appears to be solved in the development version of `conda-smithy`.
