### ISSUE TITLE
All Python versions removed after re-rendering

### ISSUE THREAD

**Issue by johannesring** [conda-forge/conda-smithy#429]
As reported in pull request [#3](https://github.com/conda-forge/libadjoint-feedstock/pull/3) for the `libadjoint-feedstock` repo, all Python versions are removed in `.travis.yml` and `ci_support/run_docker_build.sh` after re-rendering with `conda-smithy`.

After looking closer at this, it seems to be connected with these build requirements for `libadjoint`:
``` yaml
- toolchain
- mpich
- petsc
- slepc
```
The re-rendering works fine if all of them are removed, but adding back any of them results in the problem as described.

**Comment by jakirkham** [comment]
Does this still happen with `conda-smithy` 2.0.0?

**Comment by johannesring** [comment]
No, it works fine with `conda-smithy` 2.0.0. Thanks!
