### ISSUE TITLE
CONDA_NPY not set in appveyor.yml

### ISSUE THREAD

**Issue by guyer** [conda-forge/conda-smithy#430]
A recipe with that requires `numpy x.x` does not get `CONDA_NPY` set in appveyor.yml, but it is set in circle.yml.

conda-smithy 2.0.0

**Comment by jakirkham** [comment]
Do you have an example?

**Comment by jakirkham** [comment]
Just re-rendered the matplotlib-feedstock with `2.0.0` and I'm not seeing this behavior. Do you have some kind of reproducer that you can share as I'm unable to reproduce this ATM?

xref: https://github.com/conda-forge/matplotlib-feedstock/pull/100

**Comment by guyer** [comment]
Here's the feedstock I'm trying to get working: https://github.com/guyer/pysparse-feedstock

**Comment by jakirkham** [comment]
...but it does have `CONDA_NPY` set. 😕See this [line]( https://github.com/guyer/pysparse-feedstock/blob/master/appveyor.yml#L18 ) for instance. Am I missing something?

**Comment by guyer** [comment]
I added `CONDA_NPY` manually. [This](https://github.com/guyer/pysparse-feedstock/blob/120e830300d22e956109f806be32f7dba322dc6d/appveyor.yml) is what was generated originally.

**Comment by jakirkham** [comment]
The `conda-forge.yml` doesn't appear to be formatted correctly. The `channels` section needs to be properly indented.

ref: https://github.com/guyer/pysparse-feedstock/blob/master/conda-forge.yml#L2

**Comment by guyer** [comment]
Thank you
