### ISSUE TITLE
`--user github_user_name` not passed to ci_support/run_docker_build.sh 

### ISSUE THREAD

**Issue by guyer** [conda-forge/conda-smithy#431]
Despite conda-forge.yml having
```
channels:
targets:
- [github_user_name, main]
```
ci_support/run_docker_build.sh still says
```
upload_or_check_non_existence /recipe_root conda-forge --channel=main || exit 1
```

**Comment by jakirkham** [comment]
Did you [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock )? Just tested this myself and am not seeing this behavior.

**Comment by guyer** [comment]
Yes, I rerendered. Nothing changed.

**Comment by jakirkham** [comment]
Assuming this is the same feedstock as the other issue, this is also behaving correctly. Please see this [line]( https://github.com/guyer/pysparse-feedstock/blob/master/ci_support/run_docker_build.sh#L50 ) for an example. Am I missing something else? 😕

**Comment by guyer** [comment]
Like the other, I [added that manually](https://github.com/guyer/pysparse-feedstock/commit/a25c5e52dc491bfe6db107bd6d511bbcd8e034fb#diff-072cea419befcfca383c45968d4c00b5) so that I could actually get things working.

**Comment by jakirkham** [comment]
The `conda-forge.yml` doesn't appear to be formatted correctly. The `channels` section needs to be properly indented.

ref: https://github.com/guyer/pysparse-feedstock/blob/master/conda-forge.yml#L2

**Comment by guyer** [comment]
Ah, thanks. I copied from https://github.com/conda-forge/conda-smithy/blob/master/README.md, but it's not indented by github markdown.

**Comment by jakirkham** [comment]
Good point. Feel free to submit a PR to fix that.

In light of the indentation fix, do these problems go away or are there other issues?

**Comment by guyer** [comment]
Indentation fixed both issues, thanks. 

I can't tell why README.md doesn't indent properly. The raw text looks fine.

**Comment by jakirkham** [comment]
Looks like they were indented using one space instead of two. Using two spaces seems to fix it. Thanks for point that out. Fixing in PR ( https://github.com/conda-forge/conda-smithy/pull/432 ).

**Comment by jakirkham** [comment]
Have corrected the README. Thanks again for catching that.
