### ISSUE TITLE
No such file /feedstock_root/build_artefacts/recipe_root ...

### ISSUE THREAD

**Issue by jgoppert** [conda-forge/conda-smithy#434]
I'm running into this error after re-rendering with conda smithy 2.0.0:

https://circleci.com/gh/conda-forge/px4tools-feedstock/21?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

PR is here: https://github.com/conda-forge/px4tools-feedstock/pull/11

It is up-to-date:

```bash
jgoppert@jmg-bnb1:~/git/px4tools-feedstock$ conda smithy rerender
Fetching package metadata .........
Fetching package metadata .........
Fetching package metadata .........
Fetching package metadata ...........
Fetching package metadata ...........

Re-rendered with conda-smithy 2.0.0.

No changes made. This feedstock is up-to-date.
```

**Comment by jakirkham** [comment]
This is not a `conda-smithy` issue, but a change in `conda-build` behavior. Please see this [comment]( https://github.com/conda-forge/px4tools-feedstock/pull/11#issuecomment-272726212 ) for details and possible fixes.
