### ISSUE TITLE
run_docker_build SSL verification.

### ISSUE THREAD

**Issue by dnadeau4** [conda-forge/conda-smithy#448]
Would it be possible to add `ssl_verify: false` to the config section of run_docker_build.sh so that `conda` does not verify the SSL certificate.   When using a `local` certificate, this is the only way to get through the firewall using `conda`.  

Or just add the following information to the documentation, that would also be very useful. 

* `Add a local certificate on Ubuntu for docker to load the docker image using https://`

```
1.  Copy CA cert to /usr/local/share/ca-certificates.
2.  sudo update-ca-certificates
3.  sudo service docker restart
```

```bash
config=$(cat <<CONDARC 

channels: 
 - conda-forge  
 - defaults

conda-build: 
 root-dir: /staged-recipes/build_artefacts  

always_yes: true 
show_channel_urls: true 
ssl_verify: false

CONDARC                                                                                                                                                                        
)  ```

**Comment by jakirkham** [comment]
Not sure I like the suggestion of not using SSL always. Could you explain a little more why you think this is necessary?

**Comment by dnadeau4** [comment]
It would be nice to inform the user in your documentation on a way to bypass/set the certificate when they are behind a firewall (only if needed).   My work place have their own certificate and does allow `direct` SSL connection.   

Many people working with their own certificate have this problem.
* https://github.com/conda/conda/issues/1166

You can also set your own certificate with conda directly.  
* conda config --set ssl_verify `pathToYourFile.crt`

Docker has this problem too.  Each program using `curl` will needs to be set somehow.  


Example:
```
$> conda install gfortran 
Fetching package metadata ...

CondaHTTPError: HTTP None None for url <None>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)
```

**Comment by jakirkham** [comment]
Setting your own certificate file sounds like a much better option than disabling SSL verification entirely. Does this work for your use case?

**Comment by dnadeau4** [comment]
I tried it and it works very well.



Lawrence Livermore National Laboratory
Atmospheric, Earth and Energy Division
925-423-3123

________________________________

**Comment by dnadeau4** [comment]
I understand that SSL provides privacy and data integrity, but when we are testing development using `docker` on a local machine and `conda-forge` channel, it is not critical to set SSL, although it would be better. 

 I usually have to `export GIT_SSL_NO_VERIFY=true` for `git commands` to work.  I have not found another way using SSL with  `git`

BTW `anaconda` uses `binstar` and it is possible to set SSL verification as well when you upload to your channel with this command.
`binstar config --set verify_ssl [true|false|/path/to/root/CA]`

Note:
* `conda` uses `ssl_verify` 
* `binstar` uses `verify_ssl` :smiley:

**Comment by jakirkham** [comment]
TBH all you would need to do is make your own package for `ca-certificates` and put it in a channel that has higher priority than conda-forge. This would then allow you to use certificates that meet your work's requirements.

**Comment by jakirkham** [comment]
Going to go ahead and close this out as it seems the solution is outside of the scope of conda-forge. Though recommendations have been made that should help.
