### ISSUE TITLE
Appveyor x64 py27 builds failing

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/conda-smithy#462]
I've submitted a number of revisions and refactors that are dying because the `x64`, `py27` build on Appveyor is failing to start `conda`. Example:
```bash
call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
failed to create process.
failed to create process.
failed to create process.
'"C:\Miniconda-x64\Scripts\\..\python"' is not recognized as an internal or external command,
operable program or batch file.
conda update --yes --quiet conda
'conda' is not recognized as an internal or external command,
operable program or batch file.
```
Some example pulls are: [`python-engineio`](https://github.com/conda-forge/python-engineio-feedstock/pull/2), [`setuptools-git`](https://github.com/conda-forge/setuptools-git-feedstock/pull/2), [`pytimeparse`](https://github.com/conda-forge/pytimeparse-feedstock/pull/1), and [`pysocks`](https://github.com/conda-forge/pytimeparse-feedstock/pull/1)

**Comment by jakirkham** [comment]
Thanks @pmlandwehr. Indeed this does appear to have shown up on a variety of other feedstocks as well in the past few hours. Probably a bad update in an AppVeyor image. Will ask about it.

**Comment by jakirkham** [comment]
Seems like this [build]( https://ci.appveyor.com/project/conda-forge/cloud-sptheme-feedstock/build/1.0.6 ) is the first one. The [one]( https://ci.appveyor.com/project/conda-forge/blinker-feedstock/build/1.0.5 ) before that is fine. So it looks like this started ~10hrs ago.

**Comment by jakirkham** [comment]
Opened an issue with AppVeyor. Let's see what they say.

xref: https://github.com/appveyor/ci/issues/1339

**Comment by jakirkham** [comment]
Upstream has rolled the image back for now. FWICT this is working correctly on running builds. They will push a new fixed image tomorrow evening. More details on the upstream ticket.

For now, would recommend restarting any failing builds to get them back in the queue. They should behave normally once started.

Thanks for raising to our attention, @pmlandwehr.

**Comment by jakirkham** [comment]
Also have restarted any builds that appeared to be affected by this issue.
