### ISSUE TITLE
rerender not adding travis.yaml to libcf

### ISSUE THREAD

**Issue by dnadeau4** [conda-forge/conda-smithy#465]
https://github.com/conda-forge/libcf-feedstock/pull/1

Not sure what is going, I created a new pull request to libcf, but `osx` is not being process since travisl.yaml is missing.

**Comment by jakirkham** [comment]
Have you tried [re-rendering]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock )?

**Comment by dnadeau4** [comment]
@jakirkham I just tried re-rendering, but only circle CI was ran.  I tried to re-run the the staged-recipe by clicking `restart` but it does not see to work https://travis-ci.org/conda-forge/staged-recipes/builds/202997493  What else should I try?

**Comment by dnadeau4** [comment]
@jakirkham I loooked at the end of the log and Travis did not build the file for some reasons, it came back green.

**Comment by jakirkham** [comment]
Strange. I'll take a look later, but can't look right now. Thanks for raising this.

**Comment by dnadeau4** [comment]
I could create a new staged-recipe and we can delete the old one if this helps.

**Comment by jakirkham** [comment]
Looks like this was just a [typo]( https://github.com/conda-forge/libcf-feedstock/pull/1/commits/9829aa54657e6f316b7530d6265073c2b72ee9b4#diff-e178b687b10a71a3348107ae3154e44cR19 ) that need to be fixed.
