### ISSUE TITLE
"vc14 [win and (py35 or py36)]" or "vc14 [win and py35]"

### ISSUE THREAD

**Issue by MSeifert04** [conda-forge/conda-smithy#467]
The anaconda recipes (`feature`-section) were changed with the 3.6 release, for example [`boost/meta.yaml`](https://github.com/ContinuumIO/anaconda-recipes/blob/08f84e7eb91ce1fbe4637a39b39d0a9a9b96f3fa/boost/meta.yaml#L14) to include `py36` for `vc14`.

Is such a change necessary for the conda-forge recipes as well? The latest rerender PR didn't change these so I was unsure if that was an oversight or on purpose.

**Comment by ocefpaf** [comment]
Necessary? No. Nice to have for the sake of being explicit? Yes!

**Comment by MSeifert04** [comment]
@ocefpaf In that case I'm closing this again. Thanks for the fast reply 👍
