### ISSUE TITLE
BUG: placeholder limit issues

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-smithy#468]
It seems that there is an issue with the placeholder length.
from [circle ci](https://circleci.com/gh/CJ-Wright/staged-recipes/22?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):
```python
OSError: Failed to copy /staged-recipes/build_artefacts/attrs_1488327519754/work/attrs-16.3.0/LICENSE.txt to /staged-recipes/build_artefacts/attrs_1488327519754/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/info/LICENSE.txt.  Error was: Command 'cp -a /staged-recipes/build_artefacts/attrs_1488327519754/work/attrs-16.3.0/LICENSE.txt /staged-recipes/build_artefacts/attrs_1488327519754/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/info/LICENSE.txt' returned non-zero exit status 1
```
This may have things to do with the many issues on the conda side:
https://github.com/conda/conda-build/pull/877
https://github.com/conda/conda/issues/1087#issuecomment-207559278
https://github.com/conda/conda-build/issues/982
https://github.com/conda/conda-build/issues/1502
Some of these mention encryption, but something tells me that nothing on the conda-forge side has changed with respect to that and this is more an error with conda-build.

**Comment by jakirkham** [comment]
`conda-smithy` plays no role in the build process at `staged-recipes`.

**Comment by CJ-Wright** [comment]
Sorry for the misplacement. I thought that this was rather curious (I have the same problem on my local machine but thought this was a particularly good example since it is running on the definition of a clean machine)

**Comment by jakirkham** [comment]
No worries. Thanks for raising it. Just trying to make sure it gets redirected somewhere where it will be more likely to be solved. Do you have a link for the `conda-build` issue?

> I have the same problem on my local machine but thought this was a particularly good example since it is running on the definition of a clean machine

Absolutely! This remains one of my favorite features of conda-forge. Definitely has helped up and the conda team iron out bugs on either end before. This merely continues that great trend.

**Comment by CJ-Wright** [comment]
I found out the issue was a FileNotFound problem, however python27 doesn't have those *sigh*
