### ISSUE TITLE
Lint the recipe

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-smithy#47]
Now that we have a linter, one of the CI services should be used to lint the recipes as they are proposed to the feedstock.

**Comment by ocefpaf** [comment]
I guess we should set this CI for https://github.com/conda-forge/feedstocks, right?  I can take a look into next week.

**Comment by pelson** [comment]
> I guess we should set this CI for https://github.com/conda-forge/feedstocks, right?

Nope. That would be too late. It would have to live in each of the feedstocks at PR time.
To do that, we add capability to the feedstock creation library (aka conda-smithy). I'd probably do this at https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/travis.yml.tmpl.

**Comment by ocefpaf** [comment]
> Nope. That would be too late.

OK.  Now I get what you are doing that.

> To do that, we add capability to the feedstock creation library (aka conda-smithy).

Got it.

**Comment by jakirkham** [comment]
So, this is resolved by the linter bot, right? The only thing it could really use a field in the commit/PR status, which would be offered by this PR ( https://github.com/conda-forge/conda-forge-webservices/pull/11 ). Though that PR may need a practice run to see if it is actually doing the right thing.

**Comment by pelson** [comment]
Yep. I think we can close this issue. Plenty of refinement available in conda-forge/conda-forge-webservices
