### ISSUE TITLE
Fix skip handling

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#488]
It appears that commit ( https://github.com/conda-forge/conda-smithy/commit/75dc6bf6fab963d88e079fc6dd2c2c326cf813fd ) from PR ( https://github.com/conda-forge/conda-smithy/pull/479 ) results in some unintended skips as demonstrated by PR ( https://github.com/conda-forge/viridis-feedstock/pull/4 ). Will need to investigate a fix that still has the intended behavior.

Edit: Another example is PR ( https://github.com/conda-forge/qcodes-feedstock/pull/1 ).

**Comment by jakirkham** [comment]
cc @johanneskoester @jni

**Comment by jakirkham** [comment]
When inspecting the `meta`, we find that all cases result in `skip` being `True`. We are going to need look for some more specific information if about the `skip` conditions, but will need to figure out where.

**Comment by johanneskoester** [comment]
Alternatively, one could still try to find the conda/conda-build combination where the computation works without a problem. This should be doable by using my test case, deactivating the skipping, and checking where it crashes.

**Comment by jakirkham** [comment]
Thanks for the suggestion, @johanneskoester. I'll keep it in mind when I have time to do more debugging.

**Comment by jakirkham** [comment]
Fixed by PR ( https://github.com/conda-forge/conda-smithy/pull/493 ).

**Comment by jakirkham** [comment]
The fix is being released in `conda-smithy` 2.2.2.

xref: https://github.com/conda-forge/conda-smithy-feedstock/pull/73
