### ISSUE TITLE
Re-rendering remove Python 3.4 from builds

### ISSUE THREAD

**Issue by megies** [conda-forge/conda-smithy#496]
I re-rendered our feedstock at [conda-forge/obspy-feedstock](https://github.com/conda-forge/obspy-feedstock) with conda-forge/obspy-feedstock#13 and found that conda smithy has removed Python 3.4 from the builds matrix.. on the other hand, the [current example recipe at staged-recipes](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml) states that ['`By default, the package will be built for Python 2.7, 3.4, and above, for all major OSs.`'](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L24).

So either..
 - the comment in the recipe example is wrong or
 - conda smithy is wrong by excluding Python 3.4 from the build matrix or
 - `conda smithy rerender` in my case should not have removed Python 3.4 from the build matrix as it did, see [command stdout](https://github.com/conda-forge/obspy-feedstock/pull/13#issuecomment-289414094)

**Comment by ocefpaf** [comment]
The comment is outdated. `conda-forge` cannot build Python 3,4 due to the strain on the CIs and we decided to support only Python 3.5 and 3.6.

There is not much we can do as we are CI limited here. Sorry.

**Comment by megies** [comment]
OK, thanks for clarification @ocefpaf.
