### ISSUE TITLE
gitdb requirement missing?

### ISSUE THREAD

**Issue by MSeifert04** [conda-forge/conda-smithy#497]
I tried to rerender and the first test failed because of a missing `gitdb` dependency. Could it be included?

Tested: smithy 2.2.2, Windows 10, python 3.5

**Comment by scw** [comment]
It correctly was pulled in on my end, the requirements for [gitpython](https://github.com/conda-forge/gitpython-feedstock/blob/master/recipe/meta.yaml) should pull it in. Did gitpython end up in your environment?

**Comment by MSeifert04** [comment]
ah, I just retried it and it worked. Sorry

Thanks for the comment @scw !

**Comment by scw** [comment]
Cool! Happy to help.
