### ISSUE TITLE
Why is BINSTAR_TOKEN handled differently than all other token?

### ISSUE THREAD

**Issue by janschulz** [conda-forge/conda-smithy#50]
I'm currently trying to build a multiple recipe version of conda-smithy and found that all access token go into a subdir of `~`, but only the `BINSTAR_TOKEN` is requested to be in `os.environ`. Is it ok, to change that to also use a file based access token ( `~\.conda-smithy\anaconda.token`)?

**Comment by pelson** [comment]
> Is it ok, to change that to also use a file based access token ( ~\.conda-smithy\anaconda.token)?

Sure. Makes sense to me :+1:

**Comment by pelson** [comment]
This was done. Thanks @janschulz

**Comment by janschulz** [comment]
Seems this commit was not applied: the binstar token is still gotten from the environment and not from `anaconda.token` https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/ci_register.py#L36

Commit is here: https://github.com/conda-forge/conda-smithy/pull/51/commits/3e868c03de23afdb71d16c54df71ae2a34fac736#diff-8666415dcccfaf789819c990341084c8R29

Should I port that commit to the current codebase?
