### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc4 in position 5: invalid continuation byte

### ISSUE THREAD

**Issue by ericdill** [conda-forge/conda-smithy#500]
Looks like one of the recipes in staged-recipes [yaafe](https://github.com/conda-forge/staged-recipes/pull/2709/files) was bundling a binary .wav file with it for testing purposes and I didn't catch that during the review. Honestly, I didnt even think to check for it :disappointed: .  In any event, it did surface an interesting "bug?" in the file [copy function](https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/feedstock_io.py#L77) in conda-smithy/feedstock_io.py.

Full stack trace:
```
Repository registered at github, now call 'conda smithy register-ci'
Making feedstock for yaafe
Initialized empty Git repository in /private/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/tmpyp_2IE__feedstocks/yaafe-feedstock/.git/
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 6, in <module>
    sys.exit(conda_smithy.cli.main())
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 275, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 98, in __call__
    generate_feedstock_content(feedstock_directory, args.recipe_directory, meta)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 29, in generate_feedstock_content
    configure_feedstock.copytree(source_recipe_dir, target_recipe_dir)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda_smithy/configure_feedstock.py", line 582, in copytree
    copy_file(s, d)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda_smithy/feedstock_io.py", line 80, in copy_file
    for line in fh_src:
  File "/Users/travis/miniconda/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc4 in position 5: invalid continuation byte
```

For now, I think the right move is to remove the offending file from staged-recipes to keep the flow of new recipes -> feedstocks open and that .wav file can be re-added in the feedstock. (https://github.com/conda-forge/staged-recipes/pull/2743)

Long term, what's the right approach here? The first two things that come to mind are:

1. Don't merge recipes that contain non-text files and ask that those be added in the feedstock
2. Detect if a file is a binary file in the copy_file function in feedstock_io.py and invoke one of the built in copy commands.

Thoughts @conda-forge/conda-smithy ?

A brief search of the issue tracker in this repo did not surface a similar issue.

**Comment by jakirkham** [comment]
Just some history to keep in mind. Some time ago, I raised a question about whether we allow binary files in feedstocks. ( https://github.com/conda-forge/conda-forge.github.io/issues/128 ) Generally we noted there are licensing and security concerns. Though we didn't come down against it. Fixing this implies we generally think it is ok to include binary files in feedstocks. In some ways, the answer is already yes as people have included icons in the past.

More recently we had issues with different line endings for re-renderings on Unix vs. Windows. The fix was this line-by-line copying. ( https://github.com/conda-forge/conda-smithy/pull/407 ) While I agree this is not great for binary files, we still need it for text files. I guess a fix would be to either somehow detect the file is binary and not use the line-by-line copying or catch `UnicodeDecodeError` then simply copy the file over (as binary files shouldn't need line endings fixes).

**Comment by ericdill** [comment]
Thanks for surfacing that issue number here. I see that I even participated in that discussion. I'm a little embarrassed I didn't remember that 🤦‍♂️.  

> Fixing this implies we generally think it is ok to include binary files in feedstocks

That's a very good point that I hadn't considered. I am inclined to come down on the 👎 side of anything that increased licensing and security concerns. 

> I guess a fix would be to either somehow detect the file is binary and not use the line-by-line copying or catch UnicodeDecodeError then simply copy the file over (as binary files shouldn't need line endings fixes).

Ok, that's a pretty straightforward fix. I'll take care of fixing that, but I think it's a good idea to have some sort of CF policy before submitting that fix. 

---

I don't feel particularly motivated to propose a general policy for binary files, nor am in any way pressuring you to come up with such a policy. Until there's a motivating factor for CF to create such a policy, I'm content to let this issue sit idle. Does that seem reasonable?

**Comment by jakirkham** [comment]
Believe this was fixed by issue ( https://github.com/conda-forge/conda-smithy/pull/535 ). So going to go ahead and close. Feel free to reopen if that is not the case.
