### ISSUE TITLE
No BINSTAR_TOKEN present, so no upload is taking place

### ISSUE THREAD

**Issue by Horta** [conda-forge/conda-smithy#504]
I'm getting

> No BINSTAR_TOKEN present, so no upload is taking place. The distribution just built is not already available on conda-forge's main channel.

for OSX builds of https://travis-ci.org/conda-forge/limix-inference-feedstock

Example, last build: https://travis-ci.org/conda-forge/limix-inference-feedstock/jobs/221278857

I've compared this log with working builds and the difference is that it does not do

`export BINSTAR_TOKEN=[secure]`

As a results, I get now new OSX release for my package...

**Comment by isuruf** [comment]
See https://github.com/conda-forge/limix-inference-feedstock/pull/2/files#r111680690

**Comment by mjscosta** [comment]
@isuruf having the same issue with https://github.com/eyeware/lcov-feedstock/blob/master/.travis.yml, I don't really understand how you fixed it. Can you provide additional details.

I'm staging this recipe, at the moment I really want to have this package available, later when I've got it working, I'll send it to conda-forge staging recipes, but for now I just need to figure out how to fix this.

**Comment by horta** [comment]
@mjscosta I don't remember but have you tried rerendering it? `conda smithy rerender --commit auto` with the latest conda-smith package.

**Comment by mjscosta** [comment]
Hi @horta , I think I did as it was a recipe build from scratch. I can retry that, but I fear this issue might come into play (https://github.com/conda-forge/conda-smithy/issues/935) as I'm not using conda-forge github and channels to compile and upload.

**Comment by carlodri** [comment]
just stumbled into this here: https://travis-ci.org/conda-forge/databases-feedstock
