### ISSUE TITLE
Travis trouble syncing repos

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#506]
Appears that sometimes we have trouble syncing repos on Travis CI as shown in the traceback below. Maybe we need to retry in a short period of time or something.

```
CI Summary for conda-forge/marray-feedstock (can take ~30s):
 * Registered on travis-ci
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 6, in <module>
    sys.exit(conda_smithy.cli.main())
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 283, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 159, in __call__
    ci_register.add_project_to_travis(owner, repo)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda_smithy/ci_register.py", line 225, in add_project_to_travis
    response.raise_for_status()
  File "/Users/travis/miniconda/lib/python2.7/site-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.travis-ci.org/users/sync
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 195, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', u'/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/tmpj7z8yr__feedstocks/marray-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

ref: https://travis-ci.org/conda-forge/staged-recipes/builds/222777217#L1605-L1624

**Comment by jakirkham** [comment]
This is one of the issues that I also saw while testing PR ( https://github.com/conda-forge/conda-smithy/pull/505 ) locally.

cc @isuruf

**Comment by isuruf** [comment]
Why do we need to sync after activating the repo?

**Comment by isuruf** [comment]
@pelson, any reason why we are trying a sync after activating the repo [here](https://github.com/conda-forge/conda-smithy/blob/7bd1ef276b6690ed9cba423336903f58351d7ae9/conda_smithy/ci_register.py#L223-L224)

**Comment by jakirkham** [comment]
Hmm...why are we still using `/hooks` [here]( https://github.com/conda-forge/conda-smithy/blob/7bd1ef276b6690ed9cba423336903f58351d7ae9/conda_smithy/ci_register.py#L216 )?

**Comment by isuruf** [comment]
@jakirkham, that's a put request not a get and therefore returns the info of only the changed hooks. `/repos` is only for checking info and `/hooks` is the only way to change from inactive to active.

**Comment by jakirkham** [comment]
Would have figured we could do that through `/repos`, but yeah I'm not seeing a POST or PATCH call listed as supported.

**Comment by isuruf** [comment]
From travis-ci docs, `Might return status 409 if the user is currently syncing.`
