### ISSUE TITLE
GitHub issue/PR templates

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#509]
It seems like there are a bunch of trivial things that come up on each issue every time. Am thinking it is probably a good idea to include GitHub issue and PR templates to have users address these. Hoping this would streamline things for bug reporters and maintainers.

A common example of one of these questions is getting reporters to include an environment listing with package bug reports. Another example is reminding users to reset the build number in version bump PRs.

**Comment by epruesse** [comment]
Checking for a correct build number could be done by `recipe-lint` (it should be zero if there is no package in conda-forge with that name and version, or n+1 if the pair does exist).

Perhaps there could also be a link to a checklist for contributors/reviewers? Here are some items that I was asked to fix:

 - build number (yep, frequent)
 - don't overwrite LDFLAGS & friends (append instead)
 - pin packages according to [pin_the_slow_way.py](https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/pin_the_slow_way.py])
 - name of recipe folder should be name of package
 - delete docs

**Comment by jakirkham** [comment]
Thanks for the suggestions @epruesse.

Have put together some templates and general guidance documents for feedstocks in PR ( https://github.com/conda-forge/conda-smithy/pull/598 ). Think that covers most of the things you raised except for environment variables, which we can discuss. Would be great if you could take a look and provide some feedback. :)

As for "delete docs" (guessing comments in the `example` at `staged-recipes`?) and recipe directory name, they only really make sense at `staged-recipes`. So did not include them in the feedstocks template. Though agree that it would be good to have contribution templates and guidance at `staged-recipes` too, which may borrow somewhat from the feedstock templates. Would encourage you to raise an issue or submit a PR for these changes over at `staged-recipes`.

**Comment by epruesse** [comment]
> As for "delete docs" (guessing comments in the example at staged-recipes?) 

I was referring to `rm -rf $PREFIX/share/doc` type cleanup, intended to minimize package size (although I personally believe that the docs should be preserved in a -doc package just in case).

**Comment by jakirkham** [comment]
Gotcha. Still feels like a `staged-recipes` recommendation as opposed to a feedstock recommendation. Presumably some decision was already made about what to keep before the feedstock was created.

As far as docs, we usually keep `man` pages, but drop anything more advanced. In some cases we lack the tools to build the docs of some packages. If there is more demand for inclusion of more bulky docs, we might want to explore split packages to appease both people wanting a light weight stack and people wanting the docs in their environment.

**Comment by epruesse** [comment]
> to appease both people wanting a light weight stack and people wanting the docs in their environment.

I'd say I belong to both groups, but I have to admit that `conda install <somepackage>-docs` would be much less useful than `apt install <somepackage>-docs` simply because in the minutes it needs to come up with an installation plan I'll have found the information elsewhere.

**Comment by jakirkham** [comment]
> ...I have to admit that `conda install <somepackage>-docs` would be much less useful than `apt install <somepackage>-docs` simply because in the minutes it needs to come up with an installation plan I'll have found the information elsewhere. 

Not necessarily. The docs really don't need to have any run dependencies. So there shouldn't really be anything to resolve dependency-wise.
