### ISSUE TITLE
lint the final package

### ISSUE THREAD

**Issue by janschulz** [conda-forge/conda-smithy#52]
More linter ideas for after the package is build:

* [ ] Check that all dependencies are declared/satisfied (install package, check all imports are importable, see https://github.com/bndr/pipreqs)
* [ ] Check that all native code has it's dependencies satisfied (for all so/dll/lib -> check that the required symbols are in the installed packages)
* [ ] check that there are no wrongly compile python files in it (e.g. some recipes explicitly delete directories from other packages). E.g if the package is named `whatever`, no other dir in `<root>Lib\site-packages\*` should exist. Maybe others?

**Comment by pelson** [comment]
Ah, are you talking about a conda distribution (i.e. ```.tar.bz2``` archives) linter? That is an interesting concept too! :+1:

**Comment by JanSchulz** [comment]
There are probably also a few good ideas in http://jwilk.net/software/lintian4python -> https://bitbucket.org/jwilk/lintian4python/src

**Comment by JanSchulz** [comment]
`conda inspect` also seems to something in that direction. Haven't investigated further than printing the help as that indicates that it doesn't work under windows :-(

**Comment by pelson** [comment]
Yes - I haven't tried it, but it sounds fairly useful on OSX & Linux.

**Comment by jakirkham** [comment]
I know @stuarteberg was interested in seeing something like this in `conda`. Sort of like a package sanitizer. Basically try to verify that we are linking to right things and that the versions are all good. This would definitely be a good last step to have before uploading a package.

**Comment by jakirkham** [comment]
This sounds more like [`anaconda-verify`]( https://github.com/ContinuumIO/anaconda-verify ) at this point. Probably worth raising each of these issues there. I think we would be better off to throw our weight behind that tool.

Though we could add a step at the end of each build to run the package through `anaconda-verify`. That way if it fails we don't accidentally upload something that is broken to start with. Have raised such an issue ( https://github.com/conda-forge/conda-smithy/issues/264 ) to discuss and keep track of this idea.

Going to close this out for now. If this plan sounds problematic, please feel free to explain this and we can reassess our approach.
