### ISSUE TITLE
copy_file chokes when copying binary data

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/conda-smithy#534]
Some packages many need binary data for testing and it should not be hard to make [`copy_file`](https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/feedstock_io.py#L77) more general.

**Comment by jakirkham** [comment]
Indeed. Saw the issues you raised and was just thinking about this. I think one solution would be to check the file type by using something like `mimetypes.guess_type` (from stdlib) or `magic.from_file` (from `python-magic`) and only fix line endings if the file comes back as `text`.

**Comment by jakirkham** [comment]
Looks like this got fixed with PR ( https://github.com/conda-forge/conda-smithy/pull/535 ). Going to go ahead and close this out. Please reopen if that is not the case.
