### ISSUE TITLE
AppVeyor error 500 when trying to register

### ISSUE THREAD

**Issue by jgomezdans** [conda-forge/conda-smithy#548]
I'm following the README instructions to get a feedstock for a package I wrote. Everything works up registering the feedstock with the CI providers (step 3 in Section "Making a new feedstock"). I get the following error 

```
$ conda smithy register-ci --user jgomezdans --feedstock_directory ./prosail-feedstock/
CI Summary for jgomezdans/prosail-feedstock (can take ~30s):
 * jgomezdans/prosail-feedstock already enabled on travis-ci
 * jgomezdans/prosail-feedstock enabled on CircleCI
Traceback (most recent call last):
  File "/opt/anaconda/bin/conda-smithy", line 6, in <module>
    sys.exit(conda_smithy.cli.main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 283, in main
    args.subcommand_func(args)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 165, in __call__
    ci_register.add_project_to_appveyor(owner, repo)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_smithy/ci_register.py", line 128, in add_project_to_appveyor
    response.raise_for_status()
  File "/opt/anaconda/lib/python2.7/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://ci.appveyor.com/api/projects`
```

I think the error is maybe related to appveyor/ci#1045 and the recommendation from a few month's back seems to be to "wait for an hour and retry", which isn't working here.

**Comment by melund** [comment]
@jgomezdans It also happened to me just now, but I think it caused by something different. Seems the Anaconda token was accidentally exposed and thus expired. Short term workaround is to re-add the recipe to https://github.com/conda-forge/staged-recipes  

See the guide here: https://github.com/conda-forge/conda-forge.github.io/issues/426#issuecomment-321897876

**Comment by jakirkham** [comment]
Going to close as that issue was resolved a while back. Please let us know if new issues should arise.
