### ISSUE TITLE
Mark patch files as binary in .gitattributes

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#549]
This is so that git doesn't mess with the patches. Like below,
```diff
diff --git a/.gitattributes b/.gitattributes
index 288029d..d567ec6 100644
--- a/.gitattributes
+++ b/.gitattributes
@@ -1,5 +1,6 @@
 * text=auto
 
+*.patch binary
 meta.yaml text eol=lf
 build.sh text eol=lf
 bld.bat text eol=crlf
```

I'd send a PR for this, but where that should be done isn't obvious to me.

cc @synapticarbors

**Comment by jakirkham** [comment]
Sure. It would go here.

ref: https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/feedstock_content/.gitattributes

**Comment by jakirkham** [comment]
Solved in PR ( https://github.com/conda-forge/conda-smithy/pull/550 ).
