### ISSUE TITLE
Add a CHANGELOG

### ISSUE THREAD

**Issue by nicoddemus** [conda-forge/conda-smithy#558]
Hi,

I couldn't find a CHANGELOG for `conda-smithy` while trying to see if the `noarch` feature has bee released yet (conda-forge/conda-smithy#531). 

Or perhaps is there a changelog somewhere and I didn't find it?

**Comment by ocefpaf** [comment]
We never did a changelog (nor proper docs). All we got is the release notes: https://github.com/conda-forge/conda-smithy/releases/tag/v2.4.0

Regarding the `norach` stuff I am writing docs about it. So far we only have a few message exchanged on gitter. (Sorry :flushed: ) See https://gitter.im/conda-forge/conda-forge.github.io?at=59ae8a64614889d475c1a008

**Comment by nicoddemus** [comment]
> We never did a changelog (nor proper docs). All we got is the release notes: https://github.com/conda-forge/conda-smithy/releases/tag/v2.4.0

Oh that's great, didn't occur to me to check there, my bad. Opened 
conda-forge/conda-smithy#559 to add a file to point to the releases page to help users find it.

> Regarding the noarch stuff I am writing docs about it. So far we only have a few message exchanged on gitter. (Sorry 😳 )

Not at all, great. I understand this is quite new, I wouldn't expect to see docs about it so soon anywa. 😁 

Thanks!
