### ISSUE TITLE
Update conda in README.md

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#562]
Now that we are using noarch packages, it'll be good to instruct the users to update conda itself before installing the conda-forge packages.

**Comment by jakirkham** [comment]
Should this actually go in the webpage docs?

**Comment by isuruf** [comment]
Yes, that too

**Comment by jakirkham** [comment]
Maybe we can actually just require a newer `conda` (given issues with 4.2) or is that too much?

**Comment by isuruf** [comment]
How do we require a newer Conda for a Conda package? I'm not talking about conda-smithy

**Comment by jakirkham** [comment]
Sorry was mixing things. So `conda` [also instructs]( https://github.com/conda-forge/conda-smithy/pull/531#issuecomment-327019171 ) that as well.

**Comment by isuruf** [comment]
Problem is that if `conda` is updated at the same time you try to install a `noarch` package, then we'll get issues.

**Comment by jakirkham** [comment]
Yeah that sounds unpleasant. In any event, am more than happy to see a note in the README.

At some point we might want to consider reusing our README here in the docs instead of copying pieces between them.
