### ISSUE TITLE
noarch: python path lengths appear to cause breaks on CircleCI.

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/conda-smithy#570]
I've been rebuilding some recipes using the new `noarch: python` flag and have been seeing some build breaks due to path lengths getting too long. e.g. for[`tqdm`](https://github.com/conda-forge/tqdm-feedstock/pull/15) I get:
`FileNotFoundError: [Errno 2] No such file or directory: '/feedstock_root/build_artefacts/tqdm_1505374729453/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/tqdm=tqdm._main:mai'

I've seen the same error when rebuilding [`faker`](https://github.com/conda-forge/faker-feedstock/pull/8), [`pyjwt`](https://github.com/conda-forge/pyjwt-feedstock/pull/6), and [`datadotworld-py`](https://github.com/conda-forge/datadotworld-py-feedstock/pull/1). Has anyone else noticed an uptick in these path issues?

**Comment by jakirkham** [comment]
Please raise this with `conda-build`.

**Comment by pmlandwehr** [comment]
Submitted [here](https://github.com/conda/conda-build/issues/2378), now closing this.

**Comment by isuruf** [comment]
See my comment here, https://github.com/conda-forge/staged-recipes/pull/3880#discussion_r137982022
