### ISSUE TITLE
Release 2.4.1

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#574]
@jakirkham, is there any other PRs we can incorporate to the next release?

**Comment by isuruf** [comment]
I guess we can fix https://github.com/conda-forge/conda-smithy/issues/562 before the next release

**Comment by jakirkham** [comment]
I think that is good enough for a patch release. We can always do another release. There are some other interesting PRs, but might need some more time to look at them properly. Was there anything else you were thinking would be good?

**Comment by jakirkham** [comment]
So I guess we are good for the release, right?

**Comment by isuruf** [comment]
Yes

**Comment by jakirkham** [comment]
Done. Thanks @isuruf for getting this out the door.
