### ISSUE TITLE
Travis CI's API failing to access hooks

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#584]
Seems that we are having a lot of trouble accessing `https://api.travis-ci.org/hooks` as we keep getting `500 Server Error: Internal Server Error`. Maybe this is getting poorly behaved now that we have so many repos here. Might be worth looking to see if there is an alternative API that we can be using. If there isn't one, maybe it is time to ask Travis CI for one.

ref: https://travis-ci.org/conda-forge/staged-recipes/builds/278739287#L322

**Comment by jakirkham** [comment]
Here's a more recent [log]( https://travis-ci.org/conda-forge/staged-recipes/builds/278926100 ), which has the same issue with every repo it tried to create until it hangs at the end and had to be manually terminated.

**Comment by isuruf** [comment]
There is one in travis' v3 API, https://developer.travis-ci.org/resource/repository#activate

**Comment by jakirkham** [comment]
Are there any caveats to using v3?

**Comment by isuruf** [comment]
We'll have to look at all the API calls we are using and check what the relevant ones are now. Some API calls like `/hooks` is not there.

**Comment by jakirkham** [comment]
So do we have to rewrite everything if we want to use the v3 API or can we just use this one piece from it?

**Comment by isuruf** [comment]
I think we can use v3 API for just this one.

**Comment by jakirkham** [comment]
We since use v3 for everything except authentication. ( https://github.com/conda-forge/conda-smithy/pull/771 ) Closing this as resolved.
