### ISSUE TITLE
linter hint missing license_file

### ISSUE THREAD

**Issue by ReimarBauer** [conda-forge/conda-smithy#591]
As we don't have a license_file in pypi resources we should fail early by the linter if a license_file parameter is used and not that name present at the correct position.

**Comment by jakirkham** [comment]
This is already effectively caught in the build, right? Should add this raises a question as to whether the linter should download the source. TBH I'm not sure that it should (at least not by default).

**Comment by beckermr** [comment]
This one is done too I think!

**Comment by ocefpaf** [comment]
Yep. We are currently discussing making it an error instead of a hint. See https://github.com/conda-forge/conda-smithy/pull/1102
