### ISSUE TITLE
should linter suggest pinning?

### ISSUE THREAD

**Issue by notestaff** [conda-forge/conda-smithy#597]
Since the required pins are listed at https://github.com/conda-forge/conda-forge.github.io/blob/e1061028272cdd3ef6c5787250b317208b2d920b/scripts/pin_the_slow_way.py#L40-L92 , maybe the linter could check  that if packages from the list are listed as dependencies, they're pinned correctly.

**Comment by jakirkham** [comment]
That's the idea. @croth1 did some work on this problem previously in PR ( https://github.com/conda-forge/conda-smithy/pull/482 ). However in light of `conda-build` 3 we are not sure what the right way is going to be to tackle this problem.

**Comment by jakirkham** [comment]
Also dup of issue ( https://github.com/conda-forge/conda-smithy/issues/139 ). So closing.
