### ISSUE TITLE
Convert scripts to entry points in setup.py

### ISSUE THREAD

**Issue by mwcraig** [conda-forge/conda-smithy#6]

**Comment by ocefpaf** [comment]
If no one is doing this I can tackle it.  I always wanted to learn how to use `entry_points` ;-)

**Comment by mwcraig** [comment]
All yours, @ocefpaf!  I think you'll need to add the .py extension back on the script and update the list of files in setup.py in addition to sing the entry point.

**Comment by ocefpaf** [comment]
Done in #8.  Note that the script file was renamed to `conda_smithy.py`, but the entry point call is still `conda-smithy`.
