### ISSUE TITLE
travis.yml and appveyor.yml does not exist initially

### ISSUE THREAD

**Issue by dorukozturk** [conda-forge/conda-smithy#611]
Our package ([pynwb](https://github.com/NeurodataWithoutBorders/pynwb)) is just published on conda-forge and we do not have a "skip" section in our recipe but travis and appveyor files are missing. 

Is there something that I am missing? When I try to rerender I see 
```
No changes made. This feedstock is up-to-date.
```

[meta.yml](https://github.com/NeurodataWithoutBorders/staged-recipes/blob/master/recipes/pynwb/meta.yaml)
[pynwb-feedstock](https://github.com/conda-forge/pynwb-feedstock)

**Comment by jakirkham** [comment]
This is because it is a `noarch: python` package. It only builds on CircleCI, but the binaries can be installed on any platform or Python version.

**Comment by dorukozturk** [comment]
@jakirkham Thank you very much. That solved my problem.

**Comment by jakirkham** [comment]
np. Glad to help. Also thanks for adding `pynwb` to conda-forge. :)
