### ISSUE TITLE
Linter should catch missing space in version spec

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#633]
If a user writes something like `dnspython>=1.8.0,<2.0.0`, the linter should complain that a space is needed before the version constraint. Meaning it should be `dnspython >=1.8.0,<2.0.0`.

**Comment by beckermr** [comment]
This one is done as well!

**Comment by jakirkham** [comment]
Do you have a PR or something where this was solved?

**Comment by beckermr** [comment]
Just grep the code base.

**Comment by jakirkham** [comment]
Looks like PR ( https://github.com/conda-forge/conda-smithy/pull/1133 ).
