### ISSUE TITLE
Enable caching of PR builds on AppVeyor

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#642]
Would be great to have `conda-smithy` enable PR build caching on AppVeyor for new repos. Here's a [rough implementation in PowerShell]( https://github.com/appveyor/ci/issues/1553#issuecomment-356489167 ) that could be coerced into Python with Requests.

**Comment by xoviat** [comment]
This is not possible because appveyor totals the cache size across the entire organization.

**Comment by jakirkham** [comment]
No longer relevant as AppVeyor is not used
