### ISSUE TITLE
import conda.config raises ImportError with conda 4.4.8

### ISSUE THREAD

**Issue by guyer** [conda-forge/conda-smithy#646]
https://github.com/conda-forge/conda-smithy/blob/34a651d4a6399d02af99ee3148eb89f11afce958/conda_smithy/configure_feedstock.py#L13

raises `ImportError: No module named config` because
`conda/config.py` was removed in conda/conda@bf4b3c5b1f63e3a7a0924bbfb2e9c51e146d1ace

**Comment by jakirkham** [comment]
Thanks for the report. `conda-smithy` doesn’t yet support `conda` 4.4. So will need to use 4.3 for the time being instead.

Also this is a dup of issue ( https://github.com/conda-forge/conda-smithy/issues/630 ). So closing this out. Feel free to add additional details to the other issue if needed.
