### ISSUE TITLE
Fix test_regenerate

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#651]
This recipe has git reset --hard at the end. Will be a nasty surprise if somebody ran the tests without commiting their changes

**Comment by jakirkham** [comment]
Guessing this refers to [this line]( https://github.com/conda-forge/conda-smithy/blob/ac5114ca6fce044d8e6fa56d5f2a1b725eed0882/tests/test_cli.py#L104 )? We could create a temporary directory to run this test in instead of running it in `conda-smithy`.
