### ISSUE TITLE
Python skipping doesn't work. 

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#658]
See https://github.com/conda-forge/zlib-feedstock/pull/16
Even though py36 is skipped, there is a matrix entry for it.

cc @msarahan

**Comment by isuruf** [comment]
Adding an additional `{{ compiler('c') }}` adds more matrix entries

**Comment by msarahan** [comment]
This is a bug, but the zlib recipe is also written poorly.  Historically, python was used as the means of imposing a given VS requirement on windows.  That was kludgy and indirect.  CB3 allows this to be much more directly specified - generally with just ``{{ compiler('c') }}``.

For example, see Anaconda's altered zlib recipe: https://github.com/AnacondaRecipes/zlib-feedstock/blob/master/recipe/meta.yaml#L23

I'll fix the bug in the interest of handling legacy recipes correctly, but we really should aim to remove all of these misuses of python.
