### ISSUE TITLE
Linter shouldn't fail for new cb3 features

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#662]
Things like `host`, `compiler`, `pin_subpackage`, etc.

cc @msarahan

**Comment by msarahan** [comment]
I thought I had fixed all that?

https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/lint_recipe.py#L29
https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/lint_recipe.py#L308-L315

**Comment by msarahan** [comment]
There's even a test:

https://github.com/conda-forge/conda-smithy/blob/master/tests/test_lint_recipe.py#L372-L374
https://github.com/conda-forge/conda-smithy/blob/master/tests/recipes/cb3_jinja2_functions/recipe/meta.yaml

**Comment by isuruf** [comment]
Sorry, I must have been using an older version
