### ISSUE TITLE
Overriding exclusive_config_file

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#674]
Raising this to discuss which option we prefer in terms of setting `exclusive_config_file`. Should it be a `conda-smithy` CLI option or should it live in `conda-forge.yml`?

**Comment by jakirkham** [comment]
cc @msarahan @isuruf

**Comment by msarahan** [comment]
You can't set it in conda_build_config.yaml.  Do you mean conda-forge.yml?

**Comment by msarahan** [comment]
I think it depends on how much you can get away with relative paths.  If you point at a file within the feedstock folder, it can live in conda-forge.yml.  If you point outside of the feedstock folder, it needs to be a CLI option.

**Comment by isuruf** [comment]
> If you point outside of the feedstock folder, it needs to be a CLI option.

In #652, if you give the absolute path or a relative path with respect to the feedstock folder it works.

I prefer the `conda-forge.yml`, because if somebody changes `conda-forge.yml` we can see the change. If they don't commit, we won't, but it's better than CLI

**Comment by jakirkham** [comment]
I think I did a bad job of motivating this discussion. Perhaps we should give some thought to when this feature will be used and then the right option will be clear to us.

The main use cases I can think of are testing/development, maybe to workaround bad behavior in `conda-smithy` or the pinning file, etc. Any others?

**Comment by isuruf** [comment]
> The main use cases I can think of are testing/development, maybe to workaround bad behavior in conda-smithy or the pinning file, etc. Any others?

I'm not sure I understand the use case, but I guess we can remove this from 3.0.0 milestone right?

**Comment by jakirkham** [comment]
My point is I'm not sure what use case we have to override the pinning file currently. I've speculated on a few. However if there is no such use case for changing the pinning file used, we shouldn't provide an option. Otherwise we are just adding maintenance effort for no purpose, right? Plus we will be limiting our ability to make a more informed choice down the road when use cases actually crop up.

Regardless this is still part of the 3.0.0 milestone as we are on the hook for any option we provide here. So we should make a decision about what if any option is appropriate. Based on your recent comment, I'm leaning towards not allow the pinning file to be configurable. That way we can give more thought to how it can be configured later.

**Comment by isuruf** [comment]
I forgot the use case of conda-smithy itself in the tests. I think making the tests independent of `conda-forge-pinning` is nice, so that we don't have to update tests when `conda-forge-pinning` changes.

That's the only use case I can think of. In all other use-cases people can override `conda-forge-pinning` instead of replacing it.

**Comment by jakirkham** [comment]
Right, it seems to me that it would be a little less awkward to handle with a CLI option than editing `conda-forge.yaml`. Namely we can easily try multiple different configs with the same recipe using a CLI option in the tests, but would need to edit or keep multiple copies of the recipe if using `conda-forge.yml`.

That said, I don't have strong feelings on this. So if you feel strongly about keeping this setting in `conda-forge.yml`, maybe we should just leave it as is.

**Comment by isuruf** [comment]
> Right, it seems to me that it would be a little less awkward to handle with a CLI option than editing `conda-forge.yaml`

Sure. CLI option is okay as well.
