### ISSUE TITLE
Adding conda-forge badges to README for multiple outputs

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#675]
When producing multiple output conda pckages, we currently still show only one badge in the README, which corresponds to the recipe's package name. However we should actually show a badge for each output conda package that matches the name of that package.

**Comment by jakirkham** [comment]
Any ideas as to how to get at this information in `conda-build`, @msarahan? Do we need to handle cases differently depending on whether the recipe is a canonical recipe vs. one that produces multiple outputs?

**Comment by msarahan** [comment]
conda-build's api.render will return a MetaData object for each output.  Iterate over them, and store their .name() and .version()

**Comment by jakirkham** [comment]
Ah ok. Sounds like this should be pretty straightforward to fix. Thanks for the info, Mike. :)

**Comment by jakirkham** [comment]
cc @isuruf

**Comment by isuruf** [comment]
1. 
![image](https://user-images.githubusercontent.com/5234427/38911873-c28d7f1c-4297-11e8-8466-e46c99bf2358.png)
2.
![image](https://user-images.githubusercontent.com/5234427/38912012-9d20b5d6-4298-11e8-91fc-4e6cd25ec5a2.png)

**Comment by jakirkham** [comment]
Thanks @isuruf.

Fixed by PR ( https://github.com/conda-forge/conda-smithy/pull/744 ).
