### ISSUE TITLE
Decide on location of CONDA_BUILD_SYSROOT

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#678]
Before releasing conda-smithy=3.0.0, we need to decide it as it's going to be written in the feedstock matrix yaml files.

`CONDA_BUILD_SYSROOT` is the path to the MacOS SDK needed by the new Anaconda compilers. This is set in `conda-forge-pinning` as ` /opt/MacOSX10.9.sdk` now. Either we can point this to where Travis-CI installs it (can it change in the future?) or we can install the sdk in `/opt/MacOSX10.9.sdk`.

cc @conda-forge/core

**Comment by jakirkham** [comment]
In general, one can find XCode SDKs by running  `"$(xcode-select --print-path)/Prms/MacOSX.platform/Developer/SDKs"`. To get the 10.9 SDK, one would run this `"$(xcode-select --print-path)/Prms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk"`. I suspect we can soft code this into `conda-smithy` by picking up the version (to be explicit `10.9`) from `conda-forge-pinning` and fill that into an environment variable. Then we get something like `"$(xcode-select --print-path)/Prms/MacOSX.platform/Developer/SDKs/MacOSX${MAC_SDK}sdk"` this in the `.travis.yml`. Not sure what else we need to do to forward that on to `conda-build`.

**Comment by msarahan** [comment]
The SDKs we've been using are so old that they're not typically available.  You must either get them from Apple somehow, which I hear is possible from their developer site, or download them from other locations.

**Comment by jakirkham** [comment]
The 10.9 SDK is included in the Travis CI `xcode6.4` image.

**Comment by jakirkham** [comment]
Did a little test in PR ( https://github.com/conda-forge/staged-recipes/pull/5245 ). Turns out I was a little off on the location, but [found the SDKs]( https://travis-ci.org/conda-forge/staged-recipes/builds/344652560#L55-L57 ). The path is `"$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs"`.

**Comment by isuruf** [comment]
Okay. So do we want `CONDA_BUILD_SYSROOT` set in the config file or as an env variable in `conda-forge-ci-setup`?

**Comment by jakirkham** [comment]
IMHO it would make more sense in `conda-forge-ci-setup`.

**Comment by jakirkham** [comment]
Added PR ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/3 ) to set the environment variable in `conda-forge-ci-setup`.

**Comment by jakirkham** [comment]
Reopening for PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/12 ).
