### ISSUE TITLE
Mark VERBOSE_AT as always used.

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#699]

**Comment by jakirkham** [comment]
Probably should add `VERBOSE_CM` to that list.

**Comment by jakirkham** [comment]
Though we should be a bit careful about adding a lot of verbosity to the logs as the CIs do have log length limits that we occasionally run afoul of causing CIs to fail.

**Comment by isuruf** [comment]
This is done by conda-build
