### ISSUE TITLE
conda-forge.yml matrix ignored on rerender?

### ISSUE THREAD

**Issue by minrk** [conda-forge/conda-smithy#700]
I'm trying to test rerendering with conda-smithy master and it's failing in a few cases. The first example I tried was https://github.com/conda-forge/mpi-feedstock which is an empty metapackage with two MPI_VARIANT matrix entries in conda-forge.yml. When I rerendered, I got only a single `config_.yml` without the MPI_VARIANTs.

Is this a bug in rerender or is there an extra step I'm missing to migrate conda-forge.yml matrix entries to conda_build_config.yml?

**Comment by isuruf** [comment]
Add a `recipe/conda_build_config.yaml` file with 
```
mpi_impl:
  - mpich
  - openmpi
```

and you can use `mpi_impl` as a jinja variable in the meta.yaml.

conda-forge.yml's matrix is removed now. (We should warn that it is removed though)

**Comment by jakirkham** [comment]
Did this go in the wiki too?

**Comment by isuruf** [comment]
Yes, see https://github.com/conda-forge/conda-smithy/wiki/Release-Notes-3.0.0.rc1

**Comment by jakirkham** [comment]
Great, thanks.

**Comment by minrk** [comment]
Perfect, thanks. Manual step is AOK; a message about what I needed to do on rerender would be great (just a link to that wiki page would have been enough for me).

**Comment by jakirkham** [comment]
Thanks @minrk. Appreciate your help testing.

Think we will move the wiki content to the docs once we get closer.

We can certainly add a warning (maybe even error?) when the old cba matrix feature appears.

**Comment by minrk** [comment]
An error like "Can't rerender until you migrate conda-forge.yml matrix to conda_build_config.yml" sounds like a good idea to me, since the rerender result will always be wrong and need to be redone anyway.

**Comment by isuruf** [comment]
Can you send a PR? You can check for `matrix` in https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/configure_feedstock.py#L588

**Comment by minrk** [comment]
Sure, I'll give it a go.

**Comment by minrk** [comment]
#702
