### ISSUE TITLE
Instructions in PULL_REQUEST_TEMPLATE should be commented

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#704]
cc @jakirkham

**Comment by jakirkham** [comment]
Sorry not following. Could you please explain a bit more what you are looking for?

**Comment by isuruf** [comment]
See https://raw.githubusercontent.com/conda/conda/master/.github/ISSUE_TEMPLATE.md
Their comments are hidden.

**Comment by jakirkham** [comment]
Thanks for clarifying.

Initially was trying to [mimic bioconda]( https://raw.githubusercontent.com/bioconda/bioconda-recipes/master/.github/PULL_REQUEST_TEMPLATE.md ) actually and so kept it pretty lean. Thought it was pretty self-explanatory, but I'm obviously a poor judge having written it. Am open to adding stuff if you think it would be useful. What would you like to add?

**Comment by isuruf** [comment]
I don't want to add stuff. Maybe change it to something like.
```
<!--
Thank you for the pull request.
Below are a few things we ask you kindly to self-check before getting a review.
-->

* [ ] Used a fork of the feedstock to propose changes
* [ ] Bump the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-render]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensure the license file is being packaged.

<!--
Please note any issues this fixes using [closing keywords]( https://help.github.com/articles/closing-issues-using-keywords/ ) after the arrow
-->

<!--
Please add any other relevant info below:
-->
```

**Comment by jakirkham** [comment]
Would still like to keep some sort of subsection titles that are not commented to keep things easy to read. Though they don't have to be the instructions spelled out. Some examples might be "Checklist:", "Related Issues:", "Other Info:". Though if you have other ideas, would be interested to hear.
