### ISSUE TITLE
linter: license unknown

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/conda-smithy#71]
Conda skeleton adds a *license unknown* when the license metadata is missing.

I am not sure if the linter catches that, but we should raise an error and look for a license the proper license in the repo/docs.

**Comment by pelson** [comment]
:+1: https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/lint_recipe.py#L25

**Comment by pelson** [comment]
Relates to #88

**Comment by ocefpaf** [comment]
Let's close this one and add this goal to #88.
