### ISSUE TITLE
Windows 32-bit using 64-bit install

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#711]
It appears the 64-bit Miniconda install is being used for 32-bit builds. For example, please see [this log]( https://ci.appveyor.com/project/conda-forge/python-snappy-feedstock/build/job/ccgk75m1kwcflu1j ). This is causing the build to fail.

**Comment by jakirkham** [comment]
cc @msarahan

**Comment by msarahan** [comment]
If you are talking about this: https://ci.appveyor.com/project/conda-forge/python-snappy-feedstock/build/1.0.21/job/ccgk75m1kwcflu1j#L72

That's expected.  The outer root environment (the one running conda-build) is expected to be win-64.  The build env is also expected to be win-64.  The host env is what may vary depending on target_platform.  I don't really think any sort of cross-compiling (which is technically what you're doing here) is going to work without using the new compiler syntax, and without splitting build and host prefixes.

**Comment by jakirkham** [comment]
Good to know.

Yeah would expect we need to update [these lines in the template]( https://github.com/conda-forge/conda-smithy/blob/v3.0.0.rc2/conda_smithy/templates/appveyor.yml.tmpl#L31-L34 ) and [these lines in the code]( https://github.com/conda-forge/conda-smithy/blob/v3.0.0.rc2/conda_smithy/configure_feedstock.py#L522 ) to select between either 32-bit or 64-bit.

We use to have some code like this, but I think it got swept away with the move to `conda-build` 3 in `conda-smithy`. This is completely fine as this code would need to be retooled for `conda-build` 3 anyways.

Is there a good way for us to check whether a build will target 32-bit or 64-bit? It's set in `conda-forge-pinning` AFAICT. Just not sure how we can get at this info in `conda-smithy`.

**Comment by jakirkham** [comment]
So I tried to use the compiler packages, but it appears to be picking up VS 2015 in a Python 2.7 build as seen in [this log]( https://ci.appveyor.com/project/conda-forge/numcodecs-feedstock/build/1.0.41/job/pah0n36j6if7n6bl ). Guessing I'm doing something wrong, but not really sure what.

**Comment by msarahan** [comment]
You appear to be missing any form of zip_keys, which is what keeps the python-VS version association.  Are you using conda-forge-pinning?  If not, I wouldn't really expect things to work.

**Comment by jakirkham** [comment]
Yes. Though guess another re-rendering is needed after the compiler packages are added, which I wasn't aware of.

That said, it appears to have added combinations of Python and VS that aren't suppose to combined (e.g. Python 3.5 and VS 2008 or Python 2.7 and VS 2015). Are we missing something from the pinning file or are my recipes missing something?

**Comment by jakirkham** [comment]
Did you see [this comment]( https://github.com/conda-forge/python-snappy-feedstock/pull/12#issuecomment-372146224 ), @msarahan? Something funny is happening with the 32-bit builds. Tried adding the compiler as a build requirement for the wheel, but it doesn't seem to help.

More generally confused about why `zip_keys` isn't effectively avoiding problematic combinations of python-VS despite using the latest version of the pinning file.

**Comment by jakirkham** [comment]
No worries. Just wanted to make sure it wasn't lost in the noise since it seems to indicate a more general problem than building wheels.

Hope you get better. This can certainly wait. :)

> ...suspect that the key trimming in conda-smithy is being overzealous.

We may want to take a look at this ourselves. (cc @isuruf)

**Comment by msarahan** [comment]
Fix proposed in #712
