### ISSUE TITLE
AppVeyor template in dev fails with Miniconda 4.4.10

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#713]
Appears that AppVeyor upgraded to Miniconda 4.4.10, which breaks builds on AppVeyor when using the dev copy of conda-smithy. Fortunately this does not affect the stable conda-smithy (2.4.5). We will need to investigate what sort of hack is required to get things operational again.

ref: https://ci.appveyor.com/project/conda-forge/python-snappy-feedstock/build/1.0.27/job/x05cxqvxlym6c5lt

**Comment by jakirkham** [comment]
Should add this blocks using the newer `anaconda-client` API needed in `conda-forge-ci-setup`. ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/8 )

**Comment by jakirkham** [comment]
Have been trying to play with this in PR ( https://github.com/conda-forge/nsis-feedstock/pull/10 ), but it is a bit painful. If someone has a Windows machine, testing/suggestions would be very helpful here.

cc @conda-forge/core

**Comment by jakirkham** [comment]
So `conda-smithy` 3 works fine with the new `conda` (4.5.0). So maybe we should solve this by just upgrading `conda` ( https://github.com/conda-forge/conda-feedstock/pull/41 ) instead of trying to hack away at this. Thoughts?

**Comment by jakirkham** [comment]
Pushing ahead with `conda` 4.5.0 in PR ( https://github.com/conda-forge/conda-feedstock/pull/44 ).

**Comment by msarahan** [comment]
conda 4.5.0 is now available thanks to https://github.com/conda-forge/conda-feedstock/pull/44 - closing this issue.

**Comment by jakirkham** [comment]
Solved thanks to various changes throughout c-f. Closing this out.
