### ISSUE TITLE
CircleCi: fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by stuertz** [conda-forge/conda-smithy#714]
from https://github.com/conda-forge/python-constraint-feedstock/pull/4

```
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Exited with code 128
```

What is going wrong here? 
Sorry if this is not an issue with smithy, but currently I don't know whom else to ask - didn't find any helpful links on the net but others having the same issue, e.g.: https://github.com/conda-forge/cfchecker-feedstock/issues/7

**Comment by jakirkham** [comment]
Please use [this command]( https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-update-circle ) in a new or existing issue to refresh the SSH key used by CircleCI. Also please add a new PR re-rendering with the latest `conda-smithy`.

Have fixed the aforementioned feedstocks already. Though the latter of the two may need a re-rendering still.
