### ISSUE TITLE
Ensure we are using latest conda and conda-build

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/conda-smithy#72]
See https://github.com/conda-forge/hdfeos2-feedstock/pull/1#issuecomment-197417297

**Comment by pelson** [comment]
Actually, maybe we should just update the image.

**Comment by ocefpaf** [comment]
> Actually, maybe we should just update the image.

You mean the docker image?

How abou AppVeyor and Travis-CI?

**Comment by pelson** [comment]
> How abou AppVeyor and Travis-CI?

They are pulling from anaconda.org anyway, right? I support TravisCI may have been setup to cache that though...

**Comment by ocefpaf** [comment]
> They are pulling from anaconda.org anyway, right? I support TravisCI may have been setup to cache that though...

The Travis-CI template is the only one that has the line `conda update --yes conda`. I am suggesting we add that to all the templates.

**Comment by ocefpaf** [comment]
BTW the update is done before conda-build is installed. I also suggest we do it after. See https://github.com/conda-forge/conda-smithy/blob/0b131fc406e341ea5db8acb30d636068677af687/conda_smithy/templates/travis.yml.tmpl#L38

If you are OK with these changes I can put a PR together later today.

**Comment by pelson** [comment]
> The Travis-CI template is the only one that has the line conda update --yes conda. I am suggesting we add that to all the templates.

But that is because Travis has caching which needs updating. AppVeyor gets the latest file each time. CircleCI doesn't, as that is part of the image definition. If we want to update conda there, I think we are just as well updating the image (as in, clicking the "rebuild" button on dockerhub).

**Comment by ocefpaf** [comment]
OK. Got it. (The cache was throwing me out there.)

> I think we are just as well updating the image (as in, clicking the "rebuild" button on dockerhub).

OK. I still think it should be in the CI though. So we always have the latest conda-build get ready to fix things as soon as they break.

**Comment by pelson** [comment]
> OK. I still think it should be in the CI though. So we always have the latest conda-build get ready to fix things as soon as they break.

Ok. That sounds reasonable. Hopefully, most of the time, that would be a no-op anyway (assuming we keep our docker image up to date).
