### ISSUE TITLE
ISC license

### ISSUE THREAD

**Issue by looooo** [conda-forge/conda-smithy#720]
the linter currently doesn't allow to use
```license_family: ISC```

would it be possible to allow this? or is it ok to use BSD as the "license-family", as it seems like ISC is a less restricted BSD: https://en.wikipedia.org/wiki/ISC_license

came up here: https://github.com/conda-forge/staged-recipes/pull/5308/commits/a7ed149464104a5ce03d05e968c96e25a921caf9

**Comment by jakirkham** [comment]
Could you please raise this at `conda-build`? We just lint using their `license_family` list. Should note that they may have fixed this in `conda-build` 3. So would check that first before raising. Thanks.

**Comment by CJ-Wright** [comment]
Oops, sorry @looooo (I forgot that I made that linkage to build) :sheep:
