### ISSUE TITLE
linter valid version numbers

### ISSUE THREAD

**Issue by dougalsutherland** [conda-forge/conda-smithy#722]
The linter should complain about bad version numbers, e.g. `v3_0_1`.

The conda docs seem to [only say](https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#package-version) to use [PEP 386](https://www.python.org/dev/peps/pep-0386/), though we should probably encourage [PEP 440](https://www.python.org/dev/peps/pep-0440/). Possibly as a warning rather than a failure (#628 / #317).

Not sure if `conda-verify` already has a test for this or anything.

**Comment by isuruf** [comment]
Fixed in https://github.com/conda-forge/conda-smithy/pull/673

**Comment by dougalsutherland** [comment]
Aha! Well then. :)
