### ISSUE TITLE
lint for `host` in the recipe

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-smithy#725]
Having `host` in the recipe seems to make the linter very unhappy. eg https://github.com/conda-forge/staged-recipes/pull/5562#pullrequestreview-110297398

**Comment by jakirkham** [comment]
So this is a `conda-smithy` 2.x problem and is not present with `conda-smithy` 3.x. Also tested with this recipe to verify. Though there is a different issue ( https://github.com/conda-forge/conda-smithy/issues/727 ), which we should think about.

**Comment by dougalsutherland** [comment]
Specifically, this was fixed by https://github.com/conda-forge/conda-smithy/pull/554.

Think this is covered by that + #727, so closing here. Feel free to reopen if you think I'm wrong though.

**Comment by jakirkham** [comment]
It’s also fixed by using cb3. So allowing this key. Both are good fixes.
