### ISSUE TITLE
Do not publish builds unless on master branch

### ISSUE THREAD

**Issue by peterjc** [conda-forge/conda-smithy#726]
Quoting https://conda-forge.org/docs/conda-forge_gotchas.html#using-a-fork-vs-a-branch-when-updating-a-recipe

> For updates, using a branch in the main repo is discouraged because,
>
> ...
>
> Branches are automatically published.
>
> This means if you push a version update to a branch and then create a PR, conda packages will be published to anaconda.org before the PR is merged.

There may be good reason for this, but why not restrict publishing conda packages to the master branch only to prevent this kind of accident?

cf https://github.com/conda-forge/ocaml-feedstock/pull/2#issuecomment-379621280

**Comment by CJ-Wright** [comment]
There are legitimate uses for building from other branches, eg for rc branches or updates for long term service packages.

**Comment by peterjc** [comment]
Are these legitimate uses common, perhaps more common than new contributors messing up?

i.e. Builds could abort if branch != master (novice user problem) and some flag is not set (whitelisting for legitimate branches)?

**Comment by CJ-Wright** [comment]
There is a whitelist issue https://github.com/conda-forge/conda-forge.github.io/issues/87

**Comment by peterjc** [comment]
OK, that seems to cover my ideas. Closing this issue as its is basically a duplicate, thanks!

**Comment by jakirkham** [comment]
If you want to contribute to that issue, please feel free @peterjc. I think this is one of those issues that there is a fair bit of interest in improving it. Special release branches are not uncommon, but they tend to be a "power user" feature more than an "average user" feature. Turning it off by default seems reasonable. There are some ideas at the end about his this might done if you are interested in contributing a patch.
