### ISSUE TITLE
Change from Miniconda3-x64 to Miniconda36-x64.

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#731]
See https://github.com/conda/conda/issues/7144

**Comment by msarahan** [comment]
I approve this change.  I can't merge here, but I very much recommend merging and rushing out a new release ASAP.  Conda may need to be reverted in the meantime.

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/conda-smithy/pull/733 ). Feel free to reopen if I'm mistaken.
