### ISSUE TITLE
Windows 32-bit issue

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#734]
See https://ci.appveyor.com/project/isuruf/boost-cpp-feedstock/build/1.0.24

The recipe doesn't use `compiler` jinja functions and therefore has no `c_compiler` nor `zip_keys` entries.

**Comment by msarahan** [comment]
yes, no cross-compilation is possible without using the compiler jinja2.  The target_platform key is what we depend on, but that's not used with the legacy compiler setup.

TBH, this is not something we should fix.  This is a great reason to switch to the new recipe style.  Also, didn't we vote to drop win-32 anyway?

**Comment by isuruf** [comment]
Looks like it's not a win-32 issue anyway.

> This is a great reason to switch to the new recipe style.

You mean switch to the new recipe style only for windows?

**Comment by isuruf** [comment]
https://ci.appveyor.com/project/isuruf/boost-cpp-feedstock/build/1.0.25

**Comment by ocefpaf** [comment]
>  Also, didn't we vote to drop win-32 anyway?

My bad. Dropped the ball on the announcement. Just triggered that on our main channels:

https://github.com/conda-forge/staged-recipes/issues/5640

**Comment by msarahan** [comment]
yeah, that boost issue is pretty squirrelly.  Things are getting very confused on which compiler is active, fwict:

```
(base) C:\Miniconda36-x64\conda-bld\boost-cpp_1523463342065\work>call "C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools\..\..\VC\vcvarsall.bat" amd64 
The specified configuration type is missing.  The tools for the
configuration might not be installed.
(base) C:\Miniconda36-x64\conda-bld\boost-cpp_1523463342065\work>set "INCLUDE=C:\Miniconda36-x64\conda-bld\boost-cpp_1523463342065\_h_env\Library\include;" 
(base) C:\Miniconda36-x64\conda-bld\boost-cpp_1523463342065\work>set "LIB=C:\Miniconda36-x64\conda-bld\boost-cpp_1523463342065\_h_env\Library\lib;" 
(base) C:\Miniconda36-x64\conda-bld\boost-cpp_1523463342065\work>call "C:\Miniconda36-x64\Scripts\activate.bat" "C:\Miniconda36-x64\conda-bld\boost-cpp_1523463342065\_h_env" 
(C:\Miniconda36-x64\conda-bld\boost-cpp_1523463342065\_h_env) C:\Miniconda36-x64\conda-bld\boost-cpp_1523463342065\work>REM ===== end generated header ===== 
(C:\Miniconda36-x64\conda-bld\boost-cpp_1523463342065\_h_env) C:\Miniconda36-x64\conda-bld\boost-cpp_1523463342065\work>call bootstrap.bat 
Building Boost.Build engine
Bootstrapping is done. To build, run:
    .\b2
    
To adjust configuration, edit 'project-config.jam'.
Further information:
    - Command line help:
    .\b2 --help
     
    - Getting started guide: 
    http://boost.org/more/getting_started/windows.html
     
    - Boost.Build documentation:
    http://www.boost.org/build/doc/html/index.html
...found 1 target...
...updating 1 target...
msvc.write-setup-script C:\Users\appveyor\AppData\Local\Temp\1\b2_msvc_14.0_vcvarsall_x86.cmd
...updated 1 target...
...found 1 target...
...updating 1 target...
msvc.write-setup-script C:\Users\appveyor\AppData\Local\Temp\1\b2_msvc_14.0_vcvarsall_amd64.cmd
...updated 1 target...
...found 1 target...
...updating 1 target...
msvc.write-setup-script C:\Users\appveyor\AppData\Local\Temp\1\b2_msvc_14.0_vcvarsall_x86_arm.cmd
...updated 1 target...
...found 1 target...
...updating 1 target...
msvc.write-setup-script C:\Users\appveyor\AppData\Local\Temp\1\b2_msvc_9.0_vcvarsall_x86.cmd
...updated 1 target...
Performing configuration checks
    - 32-bit                   : yes
    - arm                      : no
    - mips1                    : no
    - power                    : no
    - sparc                    : no
    - x86                      : yes
    - symlinks supported       : yes
    - C++11 mutex              : no
    - Boost.Config Feature Check: cxx11_auto_declarations : no
    - Boost.Config Feature Check: cxx11_constexpr : no
    - Boost.Config Feature Check: cxx11_defaulted_functions : no
    - Boost.Config Feature Check: cxx11_final : no
    - Boost.Config Feature Check: cxx11_hdr_mutex : no
    - Boost.Config Feature Check: cxx11_hdr_regex : no
    - Boost.Config Feature Check: cxx11_hdr_tuple : no
    - Boost.Config Feature Check: cxx11_lambdas : no
    - Boost.Config Feature Check: cxx11_noexcept : no
    - Boost.Config Feature Check: cxx11_nullptr : no
    - Boost.Config Feature Check: cxx11_rvalue_references : no
    - Boost.Config Feature Check: cxx11_template_aliases : no
    - Boost.Config Feature Check: cxx11_thread_local : no
    - Boost.Config Feature Check: cxx11_variadic_templates : no
    - has_icu builds           : no
warning: Graph library does not contain MPI-based parallel components.
```

I'm concerned about the msvc_14 stuff in there, and also about the cxx11 stuff - seems like if it is really vs2015, those should all be yes, not no.  This is probably going to require some local debugging.

**Comment by jakirkham** [comment]
Yeah can reproduce this on 64-bit Windows with `boost-cpp` using the new compiler stuff (assuming I didn't mess it up).

ref: https://ci.appveyor.com/project/conda-forge/boost-cpp-feedstock/build/1.0.71/job/5o3gt8mjqf88900v?fullLog=true#L479

**Comment by jakirkham** [comment]
So I think that line from Boost is misleading. It may mean something totally different. The 64-bit builds are [generating 64-bit binaries]( https://ci.appveyor.com/project/conda-forge/boost-cpp-feedstock/build/1.0.73/job/qi0nak5ww5skjput#L42602 ). Also the `conda-smithy` 2/`conda-build` 2 based builds [said the same thing for 64-bit jobs]( https://ci.appveyor.com/project/conda-forge/boost-cpp-feedstock/build/1.0.69/job/g94acxv4cycqjwlx?fullLog=true#L5617 ), which AFAIK did not generate binaries for the incorrect architecture. FWIW the same is true of the 32-bit builds. TL;DR adding the compiler seems to be enough for creating acceptable binaries with `conda-smithy` 3/`conda-build` 3 for the correct architecture.

**Comment by msarahan** [comment]
yeah, adding the compiler stuff should definitely work, but IMHO it should not be a hard requirement.  It may be one we impose by policy, but should not be a technical requirement.  I will work on fixing the issue so that recipes without the new compiler information still work.
