### ISSUE TITLE
unknown key conda-build

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#748]
Saw this in a recent build log. Not sure exactly where it is coming from or how much we should worry about it. Just noting it here before I forget.

ref: https://circleci.com/gh/conda-forge/conda-smithy-feedstock/220

**Comment by isuruf** [comment]
This is a harmless warning by conda. See https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/run_docker_build.tmpl#L20

Can you open an issue in conda?

**Comment by jakirkham** [comment]
Right, that's what I was guessing. Just wasn't sure when `conda` runs into it and complains.

@msarahan, where should we migrate this issue?

**Comment by msarahan** [comment]
As @isuruf asked, conda.

**Comment by jakirkham** [comment]
Thanks guys. Moved to issue ( https://github.com/conda/conda/issues/7192 ).

**Comment by jakirkham** [comment]
Addressing with PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/98 ) and PR ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/11 ).
