### ISSUE TITLE
Should we add the lint to the template?

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/conda-smithy#75]
If I understood the system correctly the recipes are linted only at `staged-recipes` but not as feedstocks. Does it make sense to keep running the linter in the feedstocks?  (Maybe to ensure that new lint rules will be applied and that the recipe won't be changed to offend the rules?)

**Comment by janschulz** [comment]
IMO the linter should file bugs, not fail recipes... An example for bad thing: a failing recipe for an emergency release due to a new linter release which got stricter about something.

**Comment by ocefpaf** [comment]
> a failing recipe for an emergency release due to a new linter release which got stricter about something.

You got me there.  However, it would ensure good practices. (And we could merge such failing recipe anyways!)

**Comment by pelson** [comment]
> IMO the linter should file bugs, not fail recipes...

I've been thinking the same thing for the last few days (well, since I automated the PR changes). It would be trivial to do, and is a really nice approach. Now I think about it, it would be awesome to have this for PEP8 for normal python packages too (:memo: into my list of useful ideas :wink:).

**Comment by pelson** [comment]
This is a dupe of #47. I'll try to get on and solve this so that I can close them both :wink:

**Comment by ocefpaf** [comment]
> This is a dupe of #47. I'll try to get on and solve this so that I can close them both :wink:

Let's close this one and reduce the amount of open issues then.
