### ISSUE TITLE
Linter incorrectly diagnoses source/folder

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#756]
In `conda-build` 3, the `folder` key was added to `source` to specify where the source should be placed in the working directory (as noted in the doc reference). However `conda-smithy`'s linter does not recognize this key. So it marks this as an error even though that is not the case.

ref: https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#destination-path
ref: https://github.com/conda-forge/staged-recipes/pull/5719#issuecomment-384135350

**Comment by isuruf** [comment]
Please open this issue in conda-build. https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L458 should have `folder` in it.

**Comment by jakirkham** [comment]
Good point. Not sure if that was an oversight or intentional. We'll soon find out. 

xref: https://github.com/conda/conda-build/pull/2837

**Comment by msarahan** [comment]
oversight.  Thanks for the PR!

**Comment by isuruf** [comment]
@msarahan, what about `outputs`? It isn't in `FIELDS` either.
