### ISSUE TITLE
OSX-specific  circleci configuration entries under linux builds for some feedstocks

### ISSUE THREAD

**Issue by roryk** [conda-forge/conda-smithy#764]
Hey ya'll,

I think some mangled configurations are getting generated for circleci, where OSX-specific commands are underneath Linux build headings. See https://github.com/conda-forge/r-rdrop2-feedstock/blob/master/.circleci/config.yml as an example and compare to what looks to me like a properly generated configuration: https://github.com/conda-forge/r-oceanview-feedstock/blob/master/.circleci/config.yml

https://github.com/conda-forge/r-r-drop2-feedstock/blob/master/.circleci/config.yml 
https://github.com/conda-forge/r-sessioninfo-feedstock/blob/master/.circleci/config.yml
https://github.com/conda-forge/r-clisymbols-feedstock/blob/master/.circleci/config.yml

all look affected. Searching github, it looks like those are probably the only ones: https://github.com/search?q=.%2F.circleci%2Frun_osx_build.sh&type=Code

Should I just swap it over to what it should be?

**Comment by isuruf** [comment]
Fix is to change lines like https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/circle.yml.tmpl#L20 to `platform.startswith('linux')`

**Comment by ocefpaf** [comment]
@roryk do you fancy sending a PR? If not I can get to it now, I'm working on a new release and it would be nice to get this fixed too.

**Comment by roryk** [comment]
Yeah working on a PR now, is there some way I can test locally?

**Comment by ocefpaf** [comment]
I would try to re-render a feedstock with the changes in your PR.
I usually do a `~/miniconda3/bin/pip install -e .` to use the development version to re-render.

**Comment by roryk** [comment]
Thanks will do and update the p/r if it seems kosher.

**Comment by roryk** [comment]
Thanks so much for walking me through everything!
