### ISSUE TITLE
Linter: discourage use of toolchain, gcc directly.

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#767]

**Comment by jakirkham** [comment]
Generally agree. Would also add use of `vc` in `features` or as a dependency.

Would suggest linking to the docs for details as well.

As to `gcc`, this could be valid on macOS ATM. The reasons are Fortran (though I guess your PR handle this) and OpenMP. As Fortran is handled, we might think about how we want to handle OpenMP on macOS (it's already handled through adding `libgcc` on macOS).

**Comment by CJ-Wright** [comment]
Also can we lint that the compilers are in the build section and that a host section exists?

**Comment by scopatz** [comment]
I tend to disagree.  I know that I have recipes that require gcc (on mac, because of fortran). It would be pretty frustrating if the linter said that these perfectly valid recipes were bad just because this is not what most packages need.

**Comment by isuruf** [comment]
@scopatz, `{{ compiler('fortran') }}` on osx will add `gcc` to build requirements and `libgfortran` to run requirements.

**Comment by isuruf** [comment]
I've got a script here that automates stuff https://gist.github.com/isuruf/a4c4c0a0c49114bc02cd8554b5d3b1f7. I'll polish it up and maybe incorporate it into conda-smithy when I have time.

**Comment by ocefpaf** [comment]
> I've got a script here that automates stuff gist.github.com/isuruf/a4c4c0a0c49114bc02cd8554b5d3b1f7. I'll polish it up and maybe incorporate it into conda-smithy when I have time.

This is great! Thanks!!

**Comment by jakirkham** [comment]
What do we do/recommend if a recipe need OpenMP these days?

**Comment by isuruf** [comment]
openmp on Linux works right? I don't know how openmp on mac works.

**Comment by dougalsutherland** [comment]
Yeah, openmp on Linux doesn't need anything special. There are a few feedstocks out there using `clangdev` to get it work on Mac, but it's a hassle; hopefully the Anaconda compilers just have it automatically?

**Comment by jakirkham** [comment]
Not currently. ( https://github.com/AnacondaRecipes/aggregate/issues/71 )

**Comment by jakirkham** [comment]
Resolved with PR ( https://github.com/conda-forge/conda-smithy/pull/913 ).
