### ISSUE TITLE
yum requirements are missing after rerendering (conda smithy 3.1.4)

### ISSUE THREAD

**Issue by looooo** [conda-forge/conda-smithy#775]
yum requirements are missing after re-rendering a feedstock. Also results of conda-smithy are different if rerendering is applied multiple times.

**Comment by looooo** [comment]
ok I think I found the problem. I used a temporary branch, to get the package ready for osx. So I didn't specify any sha256sum... I guess this made conda-smithy fail.

**Comment by jakirkham** [comment]
Do you have an example PR?

**Comment by jakirkham** [comment]
Yeah, there was some shifting around in 3.1.3 due to some issues with the way we ran tests on Linux previously. The gist is we now use an interactive TTY instead of redirecting stdin/stdout/stderr. Should fix some problems caused by the redirection. Plus it is a bit nicer (e.g. term colors render on CI, users can Ctrl+C out of local builds, etc.).

xref: https://github.com/conda-forge/conda-smithy/pull/701

**Comment by jakirkham** [comment]
More generally if there are things we could be documenting/explaining better, please let us know.

**Comment by looooo** [comment]
conda-smithy drives me crazy...
I think the yum requirements are not working:
see her:
https://circleci.com/gh/conda-forge/occt-feedstock/58?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -lXmu
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -lXi
```

after rerendering the build_steps.sh file doesn't contain the section to install these libraries. Maybe it is correlated to building osx on circle ci...

**Comment by isuruf** [comment]
[This line](https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/configure_feedstock.py#L474) needs to be removed

**Comment by jakirkham** [comment]
Do we want to get rid of that line or the line above it?

**Comment by isuruf** [comment]
`build_steps.sh.tmpl` should be added conditionally as in https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/configure_feedstock.py#L479-L480
