### ISSUE TITLE
Lint `{`/`}` and space between included text 

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#782]
Would be nice if the linter promoted adding spaces between `{`/`}` and text. For example, instead of `{{version}}` one should use `{{ version }}`.

**Comment by isaac-philip** [comment]
Is this still open ? Which linter is used ? flake8 ?

**Comment by isuruf** [comment]
This is for linting the recipe file meta.yaml, which is a YAML file with jinja2 syntax in it.

**Comment by beckermr** [comment]
I went to address this issue and found that it is already in done. Let's close it!
