### ISSUE TITLE
Setting CircleCI's `no_output_timeout` parameter

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#784]
Setting CircleCI's [`no_output_timeout` parameter]( https://circleci.com/docs/2.0/configuration-reference/#run ) generally to avoid timeouts w.r.t. long quiet builds. We could just generally set this or make it an opt-in parameter in `conda-forge.yml`. Thoughts?

**Comment by dougalsutherland** [comment]
I guess the question is how often people's builds mistakenly deadlock, versus how often they need the longer timeout. My guess is that both are relatively rare.

**Comment by jakirkham** [comment]
Timeouts are fairly common in long running/complex builds. A fair bit of time is spent tinkering with this sort of thing by maintainers.

Certainly users can set this themselves if they know to (good argument for documenting at least). The main issues are re-renderings removing this setting and users not being aware this is an allowed option.

Admittedly this would be more valuable if we could set this more uniformly across CIs.

**Comment by jakirkham** [comment]
Opened issue ( https://github.com/travis-ci/travis-ci/issues/9666 ) with Travis CI about getting a similar option. On AppVeyor's issue tracker, issue ( https://github.com/appveyor/ci/issues/517 ), which is similar, has already been raised.

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/conda-smithy/pull/973 ).
