### ISSUE TITLE
Add information about supported platforms to feedstock Readmes

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#79]
It could also be nice to capture info about the currently supported platforms (as Windows is sometimes not supported and some things are Linux only). Though this may require some discussion with Continuum to get the API right. Added this issue ( https://github.com/Anaconda-Server/support/issues/27 ) to start discussion on this point.

**Comment by pelson** [comment]
Hmmm. That would be very neat to have. :+1:

**Comment by jakirkham** [comment]
I think this has been effectively solved by skipping any unused CIs and the no build badge. Going to close this out.
