### ISSUE TITLE
Don't sort variant values alphabetically

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#790]
Variant values should be sorted in the original order that they were given. If there were 2 variant types joined by zip_keys, sorting alphabetically screws up the relation.

For example
```
key1:
   - 1
   - 2
key2:
   - 2
   - 1
zip_keys:
- - key1
  - key2
```

**Comment by isuruf** [comment]
@msarahan, do you know how to get the original order of a key? ([2, 1] for key2 in this case)

**Comment by msarahan** [comment]
I would just avoid sorting anything associated with a zip_key entry at all.  Failing that, keep a copy of the original variants set and use that?  It's pretty hard to keep track once things get split up.  I found it best to not rely on order, but grouping instead, and as long as the grouping was kept correct, the order didn't matter.  Of course, you'll still want to do it to reduce cruft in the diff.  Pick one key from zip_keys to sort, and compute the positions of the sorted list relative to the original list.  Use that to reorder the other lists.
