### ISSUE TITLE
Lint requirement version format

### ISSUE THREAD

**Issue by vidartf** [conda-forge/conda-smithy#794]
I just had an issue with a PR (https://github.com/conda-forge/staged-recipes/pull/6025) where I used an invalid requirement string `traittypes >= 0.2`. Here, the last space (between `>=` and `0.2`) should be removed. Ideally, this should be picked up by the linter.

**Comment by scopatz** [comment]
Thanks for pointing this out @vidartf! PRs welcome!

**Comment by jakirkham** [comment]
Did you also raise this with the `conda-build` team? It's a little strange that it allowed this at one point (during the build) and disallowed it later (we use `conda-build` to parse the recipe in `conda-smithy`).

**Comment by vidartf** [comment]
@jakirkham I do not know how to report it, in that I don't know which repo is responsible for which bits of the process. I.e. what exactly did `conda-build` do wrong?

**Comment by jakirkham** [comment]
Sorry. Forgot that I actually raised this issue ( https://github.com/conda/conda-build/issues/2828 ). 😞

In any event, a linter PR to warn users about this would be most welcome. 😄

**Comment by jakirkham** [comment]
Have tweaked the title to make this a bit more obvious what it is referring to. Hope that is ok.

**Comment by carlodri** [comment]
[here](https://github.com/conda-forge/staged-recipes/pull/7261) is an example of a staged recipe where the presence of wrong requirements syntax like:

```yaml
    - sympy >= 1.2
    - funcsigs; python_version < '3.0'
```

leads to all CIs (and linter) silently passing without actually building anything (unless I'm missing something very obvious, which could also well be)

**Comment by scopatz** [comment]
This came up again: https://github.com/conda-forge/staged-recipes/pull/8321

**Comment by CJ-Wright** [comment]
I think this was fixed by https://github.com/conda-forge/conda-smithy/pull/1133

**Comment by kynan** [comment]
Should we actually be linting the version spec for a requirement? I recently had a typo in the spec (stray trailing `[`), which wasn't picked up by the linter but later [failed](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=296774&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d) conda's [`_parse_spec_str`](https://github.com/conda/conda/blob/master/conda/models/match_spec.py#L697). Could we use that function to parse version spec strings already in the linter?

Happy to open an new issue for this if you prefer.
