### ISSUE TITLE
Platform specific test requirements with noarch:python

### ISSUE THREAD

**Issue by CurtLH** [conda-forge/conda-smithy#816]
I recently created a [recipe](https://github.com/conda-forge/staged-recipes/pull/6115#discussion_r197663211) where the package was `noarch:python`, but the test required separate dependencies for OSX that are not available for Linux or Windows.  For this reason, I added `# [osx]` after the OSX-only test requirement.  

Is this a valid thing to do with a `noarch:python` recipe?  The recipe successfully built and the test ran as expected, but I just want to make sure I'm not causing problems down the line.

**Comment by isuruf** [comment]
That's totally fine, but remember that the tests are run in Linux only and aren't tested in OSX even though the recipes supports Linux and OSX
