### ISSUE TITLE
Detect `skip: True` and cancel relevant CI

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#82]
It would be nice if we checked if `skip: True` was set for a platform as early as possible and terminate CI.

**Comment by pelson** [comment]
Same solution as https://github.com/conda-forge/staged-recipes/issues/170.

:+1: on doing it though.

**Comment by pelson** [comment]
Closed by https://github.com/conda-forge/conda-smithy/pull/87#issuecomment-199705819.

Nice suggestion @jakirkham
