### ISSUE TITLE
maybe pkg-config, cmake shouldn't be put in the build env

### ISSUE THREAD

**Issue by minrk** [conda-forge/conda-smithy#821]
bringing up an issue coming from gitter:

cmake (often) and pkg-config (always?) are used as build dependencies to find libraries. `update-cb3` is moving them to the build environment, since they are rightly 'build tools' and not part of the required 'host environment'.

However, there's a missing piece: these packages only search for packages/dependencies in their own prefix by default. `PKG_CONFIG_PATH` and `CMAKE_PREFIX_PATH` (see https://github.com/conda-forge/toolchain-feedstock/pull/31 for cmake, there might be more than one env to set there) must be set to look in both $PREFIX and $BUILD_PREFIX for these to work as intended, so moving them to build-env only without taking additional steps ~always fails. CMake is the exception, because there are packages using CMake that don't look for any other packages with cmake. These work fine.

I see a few possible solutions to this:

1. define necessary search path env variables in build.sh (required for ~all packages that use pkg-config, ~all that use cmake to find dependencies). This is what's required now, since no common infrastructure makes cmake/pkg-config in the build env work. This puts the burden on all recipe maintainers to do it right.
2. define those env variables in toolchain to search both build and host. Or maybe even conda-build itself? (https://github.com/conda-forge/toolchain-feedstock/pull/31). This is the only option for making these packages Just Work™ in the build env without additional steps in every recipe.
3. skip moving them to the build env and leave these packages in host (seems simplest and most reliable at the moment, but might miss something I'm not aware of in the build env)
4. set `build.merge_build_and_host: true` (usually overkill, but really is the most robust, and really helps for packages that over-record paths used during build, e.g. petsc)

I've done 3 and 4 in updating to cb3 in my recipes. I haven't tried 1 or 2. In a few complicated packages, I've found the build and host env separation a battle not worth fighting and punted with `build.merge_build_and_host`, but I think most cases should be solvable with a less blunt instrument like one of the other options.

In the short-term, I'd recommend removing pkg-config and cmake from the `move-to-build` list in `conda-smithy update-cb3` (essentially option 3 until a decision is made for 1 or 2).

**Comment by scopatz** [comment]
I have seen this build issue with cmake in at least one feedstock. I think it was pugixml.

**Comment by isuruf** [comment]
@minrk, do you have a log? For each `<entry>/bin` in `PATH` CMake will look in `<entry>/lib`.

**Comment by minrk** [comment]
Maybe I was wrong about cmake. When I test a simple dependency, it seems to come out okay. It is true of pkg-config, at least. CMake will also need to be careful that things it finds in the build env (e.g. if a lib gets pulled in there by a dependency) *don't* get found in the build env, only in the host env. It would seem that installing ~everything in the host env seems a simpler and more reliable solution most of the time, only pulling out things where there is a real difference in how they should be handled (e.g. python)

@scopatz I think your build failure on Windows was due to a hardcoded abspath to host-env/cmake in `bld.bat`

**Comment by scopatz** [comment]
Ahh you are right @minrk - it was a cmake abspath issue.

**Comment by minrk** [comment]
I'm going to close this. I think everything behaves sensibly for pkg-config and cmake, and what I thought were issues caused by this and fixed by moving things back into host were total coincidences caused by unrelated things.
