### ISSUE TITLE
Relax `perl` pin in migration script

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#828]
Workarounds like [this]( https://github.com/conda-forge/gtk2-feedstock/blob/e8cd50e2892b82da964d29a15ae014e2fc0a8038/recipe/meta.yaml#L21 ) were often needed with `conda-build` 2 to avoid `perl` matrices ( https://github.com/conda-forge/conda-smithy/issues/415 ) being added unnecessarily. This was actually a quite common workaround as build tools frequently need `perl`. Would be good if the migration script picked up on this and dropped `perl` pins. This should actually also work if `perl` is a `run` dependency too.

**Comment by CJ-Wright** [comment]
I think we did the migration (at least I have a commit finishing it) https://github.com/regro/cf-scripts/commit/696a9854bbbf0d2599ef525d8a9729e977645202

**Comment by jakirkham** [comment]
Thanks CJ! 😄
