### ISSUE TITLE
CI still skips py2 after removing skip from build section

### ISSUE THREAD

**Issue by matham** [conda-forge/conda-smithy#839]
I'm trying to add support for python 2 to the kivy-feedstock (https://github.com/conda-forge/kivy-feedstock/pull/2). Previously there was `skip: True  # [py < 35]` in the `build` section, so I removed it. The problem is that the CI is still only building 3.5+ packages so I cannot test whether it works.

Would it need to be merged into master before it would add py2 support? Does that mean there's no way to test if the py2 build would fail from the PR and that I should merge and then try to fix issues? Or maybe something else is going on?

**Comment by scopatz** [comment]
Hi @matham - you need to run `conda smithy rerender` in the feedstock directory to regenerate new CI scripts.

**Comment by matham** [comment]
Oh, you're right. I did do that (https://github.com/conda-forge/kivy-feedstock/pull/2#issuecomment-405586132), and conda-forge-linter replied saying "I rerendered the feedstock and it seems to be already up-to-date.", and I confused that with the smithy response, but it was the linter, not smithy. But I see now that it rerendered it.

Thanks!

**Comment by dougalsutherland** [comment]
@matham, looks like the confusing message was because @isuruf edited your comment to remove a quote that you had apparently put in, and that triggered it twice. It did work out in the end though. :)

**Comment by CJ-Wright** [comment]
@scopatz would it be possible to have a rever activity for restarting the webservice? This seems like something that could use some automagic

**Comment by scopatz** [comment]
@CJ-Wright - yep definitely!  That would be preferable, infact. I just have no idea how to restart the webservice, but it is the sort of thing that should be scripted/documented as a rever activity. I would write this activity right in the `rever.xsh` file.

**Comment by isuruf** [comment]
Can we do it in python? No offence, but I find code written in xonsh confusing.

**Comment by scopatz** [comment]
xonsh is a super-set of Python, so you can write it in pure Python if you want. Also, you could write a side-car Python module that contains the activity and then import it / register it in the `rever.xsh`.

As for the confusion, I'd be very interested in having a separate discussion with you about what you find confusing exactly @isuruf :wink:
