### ISSUE TITLE
Add merge_build_host: True # [win] for R packages

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#840]

**Comment by ocefpaf** [comment]
@isuruf, just to confirm, the lint must fail if `merge_build_host: True # [win]` is not present for `R` packages on Windows, right? It is not a "suggestion."

**Comment by CJ-Wright** [comment]
Has there been any progress on this?

**Comment by ocefpaf** [comment]
I gave it a try but did not make any progress. (The day job is demanding my attention these days :-)

**Comment by CJ-Wright** [comment]
Ah ok
