### ISSUE TITLE
Specify numpy version

### ISSUE THREAD

**Issue by tritemio** [conda-forge/conda-smithy#843]
I am trying to update the [FRETBursts recipe](https://github.com/conda-forge/fretbursts-feedstock/pull/14) for version 0.7 and I have rerendered the recipe with conda-smithy 3.1.6.

I received the linter message about the new syntax to specify numpy version. I followed the [docs](https://conda-forge.org/docs/meta.html#building-against-numpy) and added:

```
host:
  - numpy
run:
  - {{ pin_compatible('numpy') }}
```

removing the old `numpy x.x` syntax.

Now I get the lint error: `The top level meta key host is unexpected`.
Am I missing something?

Also, should I add `- {{ pin_compatible('numpy') }}` to both `run` and `build` sections?

Thank you!

**Comment by tritemio** [comment]
Ok, I fixed the lint error. I was putting the host section outside requirements by mistake.

Still, I have the question about what to put in the build section `numpy` or `{{ pin_compatible('numpy') }}`?

**Comment by dougalsutherland** [comment]
`build` doesn't get anything `numpy`-related. `host` wants just `numpy`; `run` wants `{{ pin_compatible('numpy') }}`.

**Comment by tritemio** [comment]
@dougalsutherland, thanks for the clarification. 

I don't know if it's related but the [build](https://github.com/conda-forge/fretbursts-feedstock/pull/14) is still failing:

```
Packaging fretbursts
INFO:conda_build.build:Packaging fretbursts
Packaging fretbursts-0.7-py36h24bf2e0_0
INFO:conda_build.build:Packaging fretbursts-0.7-py36h24bf2e0_0
No files or script found for output fretbursts
WARNING:conda_build.build:No files or script found for output fretbursts
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 2184, in build_tree
    notest=notest,
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1570, in build
    built_package = bundlers[output_d.get('type', 'conda')](output_d, m, env, stats)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 914, in bundle_conda
    "run that executable.".format(dep, env_var_name))
conda_build.exceptions.CondaBuildException: Empty package; python present in build and host deps.  You probably picked up the build environment's python  executable.  You need to alter your recipe to  use the PYTHON env var in your recipe to run that executable.
```

Where is the best venue to ask for help?

**Comment by dougalsutherland** [comment]
Best thing is to ping `@conda-forge/core` in the PR where it's messing up. I'll go take a look now.
