### ISSUE TITLE
Fix linter bioconda warning

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#852]
Recently the linter failed to detect a recipe that was in bioconda and warn. Not sure if this is a `conda-smithy` issue or a `conda-forge-webservices` issue. Raising here for now.

cc @conda-forge/bioconda-recipes

xref: https://github.com/conda-forge/staged-recipes/pull/6338#issuecomment-408209449

**Comment by dougalsutherland** [comment]
Not a webservices problem, it happens for me locally too. Investigating.

**Comment by dougalsutherland** [comment]
It complains for me locally if I remember to pass `--conda-forge`:
```
$ conda smithy recipe-lint . --conda-forge
. has some lint:
  Feedstock with the same name exists in conda-forge
. also has some suggestions:
  Recipe with the same name exists in bioconda: please discuss with @conda-forge/bioconda-recipes.
```

**Comment by dougalsutherland** [comment]
It's a webservices bug when there's only hints and no errors. Fixed already, working on a test and then will PR.

**Comment by jakirkham** [comment]
Ah ok. So we were only getting hints as long as there was only one error. Got it. Thanks for figuring that out and working on this.
