### ISSUE TITLE
BUG: "Recipe maintainers should be a json list"

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#876]
Seeing the linter complaining about [the recipe maintainers not being a list]( https://github.com/conda-forge/gperftools-feedstock/pull/2#issuecomment-413905960 ). However not only they are a list and they have not changed in that PR, but the linter did not raise the issue earlier in the PR.

Edit: Seems to be [consistent]( https://github.com/conda-forge/gperftools-feedstock/pull/2#issuecomment-413914010 ) though.

cc @xmnlab

**Comment by CJ-Wright** [comment]
I think this error maybe from a change in `ruamel.yaml`?

**Comment by CJ-Wright** [comment]
the yaml is giving back `CommentedSeq` rather than list.

**Comment by CJ-Wright** [comment]
This needs a release and update to the webservices. I'll do the release now.

**Comment by jenzopr** [comment]
I assume the way to deal with it is re-linting once the webservice is updated? Can you let us know when this is the case?
Best and thanks,
Jens

**Comment by dougalsutherland** [comment]
@conda-forge-admin, please re-lint

**Comment by dougalsutherland** [comment]
@jenozpr, you can ask for a re-lint: https://github.com/conda-forge/satpy-feedstock/pull/2#issuecomment-414167645
