### ISSUE TITLE
Check the license string

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/conda-smithy#88]
- [X] check if the license is `unknown` (see #92).
- [ ] check if license is valid. Example BSD should fail as valid BSD licenses are `BSD 3-Clause` and `BSD 2-Clause`. (See source https://opensource.org/licenses/alphabetical.)

**Comment by pelson** [comment]
:+1:

**Comment by jakirkham** [comment]
Also, `BSD New` or  `BSD Revised` should be accepted. While they are a little less clear than specifying clause number IMHO, they do specify a specific BSD license, which one can google for info.

**Comment by ocefpaf** [comment]
> Also, `BSD New` or  `BSD Revised` should be accepted. While they are a little less clear than specifying clause number IMHO, they do specify a specific BSD license, which one can google for info.

That is one of the reasons why I think #93 is not ideal. My Linux distro enforces that syntax (and O have to confess that I like it), but we don't need to be that restrictive here.

**Comment by jakirkham** [comment]
> ...have to confess that I like it...

Me too. :smile:

> ...we don't need to be that restrictive here.

I think so also. Though maybe we can warn in these cases and say it is not the preferred syntax.

> That is one of the reasons why I think https://github.com/conda-forge/conda-smithy/pull/93 is not ideal.

Maybe not. Again really need time to take a look.

Regardless of what we decide, I really do appreciate that you got the ball rolling on this. I think it is really important that we can remove our focus from these minor details that the linter would be great at. So, we can focus on weird hacky things during review that the linter would totally miss (like running `git clone` in a build step). Maybe the linter can be expanded to include some of those other points, but still I think many of them will be warnings at best (e.g. not every `Makefile` has `make check` or at least calls it that).

**Comment by goanpeca** [comment]
How about:
- Checking the order, some people use `3-Clause BSD`
- Also it seems the use of the word `license` is discouraged, so if found in the string the linter should warn 

---

Question:

What are all the valid licenses strings for use that you can think of?, is this specified somewhere?

**Comment by jakirkham** [comment]
Yeah, actually after several months of reviewing recipes. I know we have come across things that it would be hard to teach the linter and have questionable valuable. While it is ok (and even good) for us to lint this, maybe we need to consider some simple skip syntax for when the linter is just off (like what pylint has).

**Comment by jakirkham** [comment]
> Also it seems the use of the word `license` is discouraged, so if found in the string the linter should warn 

Please see PR ( https://github.com/conda-forge/conda-smithy/pull/334 ).

**Comment by ocefpaf** [comment]
It would make the linter overly strict to check for the string. We should be flexible to accept things like `New BSD` and `BSD 3-Clause`.
