### ISSUE TITLE
Unparseable JSON Response in noarch badge

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#887]
Seeing the following issue with a noarch badge in a feedstock's README.

<img width="1552" alt="screen shot 2018-08-31 at 19 25 15" src="https://user-images.githubusercontent.com/3019665/44939473-76186080-ad53-11e8-9b4c-b1c92dc85529.png">

ref: https://github.com/conda-forge/dask-image-feedstock?s#current-build-status

**Comment by CJ-Wright** [comment]
It seems that circle is having some issues

**Comment by jakirkham** [comment]
Appears to have gone away. Closing...
