### ISSUE TITLE
Handling yum_requirements.txt in the new Docker image

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#890]
Currently it appears there is no `sudo` in the new Docker image. So installing packages with `yum` is problematic (e.g. using `yum_requirements.txt`). How would we like to address this?

xref: https://github.com/conda-forge/openspecfun-feedstock/pull/2
ref: https://circleci.com/gh/conda-forge/openspecfun-feedstock/6

**Comment by scopatz** [comment]
Are we effectively root in the container? I think commands can also be run via `su -c`

**Comment by isuruf** [comment]
I'm still not sure why we opted to go for the docker image by anaconda without adding on top the features in the linux-anvil image. (Running as non root user, adding sudo was a few.)

**Comment by jakirkham** [comment]
cc @conda-forge/core

**Comment by jakirkham** [comment]
Would point out the new Docker image is also building under `root`, which breaks things ( https://github.com/conda-forge/coreutils-feedstock/pull/3 ) and is generally viewed as problematic.

**Comment by jakirkham** [comment]
> Ok, is there a PR to fix that bug?

@CJ-Wright, answering over here to keep things easy to follow. Hope that is ok.

There is PR ( https://github.com/conda-forge/docker-images/pull/64 ), which would add a Docker image based on our existing one with `devtoolset` removed. We would need to make a minor changes to get it to build on CI and deploy. Some refactoring would also simplify the changeset, but could be dealt with orthogonally. There is a question about how that Docker image should be named as well. It should be relatively simple to switch the image used in `conda-smithy`.

**Comment by jakirkham** [comment]
Added PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/135 ), which will switch us over to the `condaforge/linux-anvil-comp7` Docker image for the new compiler rebuilds.
