### ISSUE TITLE
non-compiled packages should be uploading to gcc7

### ISSUE THREAD

**Issue by minrk** [conda-forge/conda-smithy#892]
With the gcc7 channel, rerenders of packages that use compilers are getting rebuilt and uploaded to gcc7. However, packages that *don't* use a compiler are not being uploaded to that channel. This currently makes it impossible for any package that has non-compiled dependencies to complete their migration (see https://github.com/conda-forge/mpich-feedstock/pull/24).

A possible fix that might be simplest:

When a package uses no compilers, upload to both main and gcc7. Nothing else should be modified, just have two upload targets instead of one (no additional matrix entries, just the addition of the upload destination).

I started looking into this, and the zip_keys seems to be getting in my way. I want to add to `channel_sources` *without* creating an additional matrix entry or creating a zip_keys conflict.

Another, more manual fix could be to manually re-upload (or relabel) existing packages that do not use compilers from conda-forge/main to conda-forge/gcc7 (or a dedicated, temporary conda-forge/gcc7-nocompile to keep things clear). I don't know how many packages fall into this category and if it's worth doing vs other, more systematic strategies.

**Comment by CJ-Wright** [comment]
Can I close, since we don't use the gcc7 label at this point?
