### ISSUE TITLE
conflict with conda_build_config.yaml and conda-forge.yml

### ISSUE THREAD

**Issue by gouarin** [conda-forge/conda-smithy#897]
By default, `conda-smithy` takes the `conda_build_config.yaml` in the miniconda path. In this file, we have 

```
channel_targets:
  - conda-forge main
```

Even if you add in `conda-forge.yml` the lines

```
channels:
  targets:
    - [gouarin, main]
```

it takes the target channel defined in `conda_build_config.yaml`. If I add my own `conda_build_config.yaml` in my recipe with the lines

```
channel_targets:
  - gouarin main
```

it works.

But I think that the configuration sets in the `conda-forge.yaml` shoud take the priority.

**Comment by gouarin** [comment]
After some investigations in the source code, I can confirm that the channels given in the `conda-forge.yaml` are never used. Only `conda_build_config.yaml` is read from the `conda-forge-pinning` package. So I propose to update the documentation accordingly by telling that if you want to change the default channel you have to create your own `conda_build_config.yaml` in your recipe with these one and update the part `Specify the feedstock channel and label` in the readme file.

What do you think ?

**Comment by sdvillal** [comment]
Not only that, I think smithy should scream out loud if channels is used in ```conda-forge.yml```.

**Comment by scopatz** [comment]
Improvee docs would be great to have!

**Comment by scopatz** [comment]
Also, conda-smithy is not strictly limited to conda-forge (at least in theory)

**Comment by jakirkham** [comment]
So this use to work correctly, but it was broken at some point when switching things around for the new compilers. It has caused us some pain as well around RC releases. Thought there was already an issue for that, but am not finding it ATM.

Arguably we should fix this as it was broken during a patch release and feedstocks depend on `conda-forge.yml` to support this. That said, agree there are two ways to specify this info, which is duplicative, and we should be phasing out the `conda-forge.yml` way given `conda-build` supports this. Probably fixing it is ok in the short term.

Alternatively as it is already broken and known to be, we could just phase it out entirely. Raising an error when using the "old" `conda-forge.yml` mechanism would be a good start.

**Comment by jjhelmus** [comment]
Just ran into this with a pre-release of python 3.8.0.  Not a big deal since I can relabel the packages after they get uploaded to Anaconda Cloud.  

My vote would be to remove this feature entirely from `conda-forge.yaml` and leave it this functionality to `conda_build_config.yaml`

**Comment by isuruf** [comment]
PRs are welcome. Note that the README still uses the conda-forge.yml so that should be fixed as well.

**Comment by jakirkham** [comment]
We will also want to remove this text, ["please edit conda-forge.yml to configure the upload channels"]( https://github.com/conda-forge/conda-smithy/blob/ae383567ff9c94fbee95940c99fc946822890a09/conda_smithy/cli.py#L119 ), from the code.

**Comment by leofang** [comment]
`channel_sources` also has the same problem (https://github.com/conda-forge/conda-forge.github.io/issues/1495).

**Comment by jdblischak** [comment]
> PRs are welcome. Note that the README still uses the conda-forge.yml so that should be fixed as well.

This is a crucial point. When uploading to a non-conda-forge channel, it's important to also edit the target channel in `conda-forge.yml` and then rerender the feedstock to update the auto-generated installation instructions in the README
