### ISSUE TITLE
Update toolchain lint to error

### ISSUE THREAD

**Issue by mariusvniekerk** [conda-forge/conda-smithy#907]
Using toolchain is really not safe anymore.  Recipes part of the migration have been merged since we don't point this out as an error.

```
Using toolchain directly in this manner is deprecated. Consider using the compilers outlined
```

**Comment by isuruf** [comment]
Examples?

**Comment by jakirkham** [comment]
IIUC what @mariusvniekerk is asking is that recipes should not explicitly use `toolchain`. They should use `{{ compiler("c") }}` or similar. Assuming I understand this correctly, I agree with that suggestion as well. The warning has been around for a while and many recipes already use the `compiler` syntax. There have been a few migration PRs created when `toolchain` was still in use explicitly, which confuses things and risks creating broken packages. Though the migration bot could also be a bit smarter in these cases as well.
