### ISSUE TITLE
CI failing on master

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#911]
As can be seen with [this build]( https://travis-ci.org/conda-forge/conda-smithy/jobs/446922237 ), the Python 3 CI case is failing on `master`. It looks like [this `conda-build` bug]( https://github.com/conda/conda-build/issues/3205 ), but [we are using `conda-build` 3.16.1]( https://travis-ci.org/conda-forge/conda-smithy/jobs/446922237#L546 ). Traceback from the log included below.

```python
$ py.test tests --cov conda_smithy
ImportError while loading conftest '/home/travis/build/conda-forge/conda-smithy/tests/conftest.py'.
tests/conftest.py:8: in <module>
    from conda_build.utils import copy_into
../../../conda/lib/python3.6/site-packages/conda_build/utils.py:10: in <module>
    import libarchive
../../../conda/lib/python3.6/site-packages/libarchive/__init__.py:1: in <module>
    from .entry import ArchiveEntry
../../../conda/lib/python3.6/site-packages/libarchive/entry.py:6: in <module>
    from . import ffi
../../../conda/lib/python3.6/site-packages/libarchive/ffi.py:108: in <module>
    errno = ffi('errno', [c_archive_p], c_int)
../../../conda/lib/python3.6/site-packages/libarchive/ffi.py:95: in ffi
    f = getattr(libarchive, 'archive_'+name)
../../../conda/lib/python3.6/ctypes/__init__.py:361: in __getattr__
    func = self.__getitem__(name)
../../../conda/lib/python3.6/ctypes/__init__.py:366: in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
E   AttributeError: /home/travis/conda/bin/python: undefined symbol: archive_errno
The command "py.test tests --cov conda_smithy" exited with 4.
```

**Comment by jakirkham** [comment]
Should add this is using the [latest `python-libarchive-c` package]( https://travis-ci.org/conda-forge/conda-smithy/jobs/446922237#L524 ) as well per PR ( https://github.com/conda-forge/python-libarchive-c-feedstock/pull/7 ).

**Comment by jakirkham** [comment]
Fixed in PR ( https://github.com/conda-forge/conda-smithy/pull/913 ).

**Comment by CJ-Wright** [comment]
That PR was super janky though, idk why that works.

**Comment by jakirkham** [comment]
Should we keep this open then?

**Comment by CJ-Wright** [comment]
I'd close it an either reopen this one or a new one if it fails again.
