### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by pkgw** [conda-forge/conda-smithy#927]
It's been a little while since the last one, and selfishly I want [my PR](https://github.com/conda-forge/conda-smithy/pull/888) to get rolled out. Maybe it's time to cut a new release?

**Edit**: specifics: 3.1.12 was August 19.

**Comment by jakirkham** [comment]
Yeah we added a pretty big Azure PR recently. We did some testing and some of the big issues were addressed through a few review cycles and some errata PRs after. That said, we could use some help from others experienced with conda-smithy (like yourself) in testing and fixing any remaining issues that may surface. This could also be a good opportunity to explore packages that are difficult to build on existing supported CIs (if that is of interest 😉).

**Comment by isuruf** [comment]
@conda-forge/core, any outstanding issues or PRs before a new release?

**Comment by mariusvniekerk** [comment]
We may still want to add yum support for azure. But that should not hold up the release

**Comment by scopatz** [comment]
Given that we are not waiting for azure, are we ready for a new release?

**Comment by CJ-Wright** [comment]
yes

**Comment by scopatz** [comment]
Alright! Let's do it then!

**Comment by scopatz** [comment]
v3.2.2 has been released
