### ISSUE TITLE
Why are packages labelled `broken` pulled in during build?

### ISSUE THREAD

**Issue by kohr-h** [conda-forge/conda-smithy#928]
I have [a build](https://github.com/conda-forge/python-xapian-feedstock/pull/5) (it's the Circle build for Python 2.7, [here](https://circleci.com/gh/conda-forge/python-xapian-feedstock/78?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) is the direct link) that fails because it pulls in [a broken package](https://github.com/conda-forge/typing-feedstock/issues/13) from anaconda.org.

The whole thing happens for the `gcc7` compiler label. The issue is that as of now, the broken package has both `gcc7` and `broken` labels, and the build happily pulls it.

So should I (and is there a way to) exclude packages labelled `broken`, or do you consider this a bug?

Also, I'm not really sure if this is the right place to raise this issue, but I haven't found a better one.

**Comment by isuruf** [comment]
Fixed now.
