### ISSUE TITLE
Increase timeout for CircleCI and Travis

### ISSUE THREAD

**Issue by astrofrog** [conda-forge/conda-smithy#940]
For the glue-core-feedstock I had to increase the timeout on CircleCI otherwise one of my builds always failed due to conda taking longer than 10 minutes to solve/install dependencies:

https://github.com/conda-forge/glue-core-feedstock/pull/19/files#diff-1d37e48f9ceff6d8030570cd36286a61R39

Specifically I added:

```
no_output_timeout: 60m
```

I think 60 minutes is overkill, but it definitely needed to be >10 min. So it might make sense to just do this by default, maybe setting the max to 30 minutes?

**Comment by astrofrog** [comment]
I've had to do this here too: https://github.com/conda-forge/glue-vispy-viewers-feedstock/pull/26

**Comment by scopatz** [comment]
Feel free to put in a PR for this @astrofrog!

**Comment by astrofrog** [comment]
Note that Travis needs something like this too:

https://github.com/conda-forge/glueviz-feedstock/pull/36/commits/a06c39b3863e8102b637ff238628db440db69ef2

I have no idea where to start in terms of a PR, but I'll take a look :)

**Comment by astrofrog** [comment]
@scopatz - done: https://github.com/conda-forge/conda-smithy/pull/942

**Comment by jakirkham** [comment]
Closing as this appears to be resolved with PR ( https://github.com/conda-forge/conda-smithy/pull/973 ).
