### ISSUE TITLE
Make azure opt-in instead of opt-out

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#941]
This can be done by making `azure: force: False`

**Comment by isuruf** [comment]
Is there a way for azure to not report a fail status if azure is enabled for the repo, but there's no azure pipelines yaml?

**Comment by jakirkham** [comment]
AFAIK that is not possible, but have not looked into it deeply myself and am only relaying what others have told me. That said, it does sound like a worthy avenue of exploration. Getting similar functionality out of other CIs required a fair bit of tweaking (e.g. CircleCI specifically). So may be possible with the right configuration file included.
