### ISSUE TITLE
`skip: True  # [not win]` rendering Circle Linux builds

### ISSUE THREAD

**Issue by scopatz** [conda-forge/conda-smithy#948]
As seen in https://github.com/conda-forge/pyqmix-feedstock/pull/1  - if the meta.yaml includes 

```yaml
skip: True  # [not win]
```

A CircleCI / Linux build will still be created.  In many cases this will fail, because the package wasn't supposed to be run on windows anyway.

**Comment by CJ-Wright** [comment]
Do you mean "supposed to be run on linux anyway"?

**Comment by isuruf** [comment]
conda-smithy generates an empty circle-ci file. otherwise it'll show error status. In your case, circle generated an error regardless. Try pushing an empty commit and see if it trigger circle-ci

**Comment by scopatz** [comment]
ie if you are skipping linux in a package, then the package probably isn't meant for linux.  I think I have a fix incoming.

**Comment by scopatz** [comment]
The error message is this:

```
#!/bin/sh -eo pipefail
# Job \"build\" has filters configured in the job definition. These filters are incompatible with workflows.
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false

Exited with code 1
```

So I am fixing the circle template
