### ISSUE TITLE
yum_requirements.txt not supported in azure pipelines

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#956]

**Comment by mariusvniekerk** [comment]
Do we still need this?

**Comment by isuruf** [comment]
There are some packages needing build time dependencies. We need this to build CDT packages as well.

**Comment by mariusvniekerk** [comment]
Is the long-term plan to have a specialized cdt building docker image?

**Comment by jakirkham** [comment]
For a use case, please see PR ( https://github.com/conda-forge/matplotlib-feedstock/pull/198 ).

**Comment by isuruf** [comment]
Fixed
