### ISSUE TITLE
Having the linter comment on PRs

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#97]
This may be a bit of work (so long term possibly), but it could be really useful. The linter will error our and point out something(s) wrong with the recipe in CI. I wonder if we could modify it so it actually makes these notes on the PR itself. That way it nicely integrates with the review process. As we add more functionality to the linter, I expect this will only become more valuable.

**Comment by jakirkham** [comment]
Maybe this needs to be at staged-recipes? Not sure.

**Comment by pelson** [comment]
Would be a great service. How is your heroku?

**Comment by jakirkham** [comment]
I guess I am thinking of staged-recipes first. Just because that is where every one is trying new things out. Normally, once the recipe is added, I figure it doesn't decay into spaghetti code that quickly (I hope I'm not wrong :wink:). Do you think it wouldn't be possible with the Travis CI matrix job that is doing the linting?

**Comment by pelson** [comment]
I see. So you put the job in the CI script, and *it* comments on its own PR based on linting information. I really like that! :+1:

**Comment by jakirkham** [comment]
Did you already do this?! I must say, I'm impressed at how quickly you got this up.

Would it be possible to get line comments on the diff up to say the latest commit that is on Travis CI? Having summary comments is still useful I think, but having context for individual changes is pretty nice.

**Comment by jakirkham** [comment]
Something we might want to consider, which could be a bit tricky, is to stop commenting if the PR is still in working order.

**Comment by pelson** [comment]
> Did you already do this?!

I taught myself heroku last night - I must say, it was an awful lot of fun! :smile: 

> Would it be possible to get line comments on the diff up to say the latest commit that is on Travis CI? 

Would you mind elaborating? I'm not entirely following :confused: 

> Something we might want to consider, which could be a bit tricky, is to stop commenting if the PR is still in working order.

Yes, agreed. It may be tricky. I was thinking of either updating the status (the things that show a tick when CI runs) of the PR if there are no problems. Might make the whole thing a little less intrusive (though it is quite fun that you get a comment back within 3 seconds of submitting a pr :smile:).

I'll be pushing the heroku code to another conda-forge repo either today or tomorrow. It is very lightweight.

**Comment by jakirkham** [comment]
> I taught myself heroku last night - I must say, it was an awful lot of fun! :smile:

Nice! It is pretty cool. Already it is quite helpful.

>> Would it be possible to get line comments on the diff up to say the latest commit that is on Travis CI?

> Would you mind elaborating? I'm not entirely following :confused:

Sure. Suppose I forgot the `extra/recipe-maintainers` section. The bot could make a comment on the last line of the PR diff noting that I need to add the maintainers. It could get a bit hairy I suppose. We could hash out the cases in a different issue if you would like.

>> Something we might want to consider, which could be a bit tricky, is to stop commenting if the PR is still in working order.

> Yes, agreed. It may be tricky. I was thinking of either updating the status (the things that show a tick when CI runs) of the PR if there are no problems. Might make the whole thing a little less intrusive (though it is quite fun that you get a comment back within 3 seconds of submitting a pr :smile:).

So, I thought about it and while not a totally bad idea I don't think it replaces the comments. What I really like about the comments is they summarizing the problems in the recipe(s). Statuses are better for if it is ok or not.

I suppose if you could check if the status has not changed and it was already passing that could be used to skip the comment. If that is what you're thinking...

> I'll be pushing the heroku code to another conda-forge repo either today or tomorrow. It is very lightweight.

Cool, I'd be curious to see. So, does it just wait for PR status updated?

<br>
All in all very nifty. Nice addition. Thanks @pelson.

**Comment by pelson** [comment]
> Sure. Suppose I forgot the extra/recipe-maintainers section. The bot could make a comment on the last line of the PR diff noting that I need to add the maintainers. It could get a bit hairy I suppose. We could hash out the cases in a different issue if you would like.

Whoa! Wow - that's a cool idea! :heart:
Our linter doesn't yet report the line number, but when it does, that would be totally possible!

> So, does it just wait for PR status updated?

Yes. It is hooked to pullrequestevent on v3 github api: https://developer.github.com/v3/activity/events/types/#pullrequestevent

**Comment by jakirkham** [comment]
Closing as this is already implemented. The ideas that haven't been implemented are issues on the relevant repo at this point ( https://github.com/conda-forge/conda-forge-webservices ).

**Comment by ReimarBauer** [comment]
had by this idea
{% set version = load_setup_py_data().version %}

conda-forge-linter telling:
Failed to even lint the recipe (might be a conda-smithy bug)
