### ISSUE TITLE
"Powered by NumFOCUS" seems to imply the package is connected to numfocus instead of conda-forge

### ISSUE THREAD

**Issue by moorepants** [conda-forge/conda-smithy#972]
![selection_358](https://user-images.githubusercontent.com/276007/50124532-ede29c00-0219-11e9-9d04-9f3e23682f2a.png)

Just noticed the new button. Seems to imply dash is powered by numfocus. Maybe it should be moved in a different location.

**Comment by scopatz** [comment]
PRs welcome that adjust this!
