### ISSUE TITLE
Using colorized text from linter

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#98]
To help make it stand out, maybe we should colorize the linter text using something like `termcolors`. Bare minimum would be to make fail red and pass green. Otherwise, we might want to colorize warnings or other relevant errors. Shouldn't be too bad, but will already be a huge asset for the review process.

**Comment by jakirkham** [comment]
Would you be ok with adding `termcolors` as a dependency? We could soften it to an optional dependency.

**Comment by pelson** [comment]
> Would you be ok with adding termcolors as a dependency?

Dependencies aren't a worry really - so long as the package being depended on can be packaged by some system that makes it easy to install :wink:

**Comment by jakirkham** [comment]
I believe `termcolors` is pure Python so packaging it in our ecosystem should be trivial. Though it looks like it hasn't been updated in awhile. Maybe we should figure out something that is being actively maintained.

**Comment by jakirkham** [comment]
Yeah, I think the answer here is `termcolors` with `colorama` for Windows.

**Comment by jakirkham** [comment]
Going to close this out for now. It is still a good idea and maybe we pursue it one day. If someone does want to try it, both `termcolors` and `colorama` are packaged at conda-forge.

When raising this my main interest was trying to identify what the linter said in the Travis CI build log in staged-recipes. Now that the linter is a proper service, there isn't as much of a strong need for this feature. This is due to the fact that the linter's comments are clear and I find myself not running the linter locally nearly as often.
