### ISSUE TITLE
The feedstock README recommends installing one of the outputs instead of the primary package

### ISSUE THREAD

**Issue by moorepants** [conda-forge/conda-smithy#990]
I just added an output to PyDy's meta.yaml for a metapackage. The README for the pydy-feedstock now recommends installing that metapackage instead of the primary package. I want it to recommend installing `conda install -c conda-forge pydy` not the metapacakge `pydy-optional`. It also shows the download count for the metapackage and not the main package. See:
![selection_413](https://user-images.githubusercontent.com/276007/51089116-e29d6600-171c-11e9-8679-7fc067e3782e.png)

Seems like ti should show all possible packages in the README or we should be able to select which one to display in the README.

**Comment by isuruf** [comment]
You need to add `pydy` as an output too. Currently your recipe is only building pydy-optional. conda-smithy will show both packages once that is done.

**Comment by moorepants** [comment]
Ok, so do I put the same requirements, etc in both the primary portion and the pydy outputs section?

**Comment by moorepants** [comment]
Also, what should I look for in the PR build output to know that both packages are being built?
